FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block monasca_grafana_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='monasca', homedir='/usr/share/grafana') }}

{% if base_package_type == 'rpm' %}
    {% set monasca_grafana_build_packages = [
        'golang',
        'git',
        'npm',
        'bzip2',
        'gcc-c++',
        'make',
        'ruby',
        'ruby-devel',
        'fontconfig',
        'rpm-build'
     ] %}
{% elif base_package_type == 'deb' %}
    {% set monasca_grafana_build_packages = [
        'golang',
        'git',
        'npm',
        'bzip2',
        'g++',
        'make',
        'ruby',
        'ruby-dev',
        'fontconfig',
        'rpm'
     ] %}
{% endif %}

{{ macros.install_packages(monasca_grafana_build_packages | customizable("packages")) }}

WORKDIR /usr/share/grafana

COPY grafana_sudoers /etc/sudoers.d/kolla_grafana_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start

ENV GO_PATH=/grafana
ENV monasca_grafana_build_path=${GO_PATH}/src/github.com/grafana/grafana
ARG monasca_grafana_version=grafana4
ARG monasca_grafana_url=https://github.com/monasca/grafana/archive/$monasca_grafana_version.tar.gz

{% block monasca_grafana_install %}
# NOTE(mgoddard): Pinning rake because rake 13.0.0 depends on Ruby 2.2, and CentOS 7 only provides
# Ruby 2.0.
# NOTE(yoctozepto): Update npm to 6.x version to avoid issues with metadata parsing.
# NPM installs itself in /usr/local/bin (the default in Ubuntu) which is not in the PATH.
# This is forced for all distros to avoid conflicts with native packages.
# NOTE(mgoddard): childprocess 3.0.0 and ffi 1.13.0 depend on Ruby 2.3.
# NOTE(yoctozepto): pinning git because fpm started requiring git and git started requiring Ruby 2.3
RUN gem install rake:"~>12" ffi:"<1.13.0" childprocess:"<2.0.0" git:"~>1.7.0" fpm \
    && curl -sSL -o /tmp/monasca-grafana.tgz ${monasca_grafana_url} \
    && mkdir -p ${monasca_grafana_build_path} \
    && tar --strip 1 -xvf /tmp/monasca-grafana.tgz -C ${monasca_grafana_build_path} \
    && rm -f /tmp/monasca-grafana.tgz \
    && cd ${monasca_grafana_build_path} \
    && go run build.go setup \
    && npm config set prefix /usr/local -g \
    && npm install npm@6.x -g \
    && /usr/local/bin/npm install \
    && go run build.go build package \
    && mv ${monasca_grafana_build_path}/dist /grafana_pkgs \
    && rm -rf /grafana

{% if base_package_type == 'rpm' %}
  {% set monasca_grafana_packages = ['/grafana_pkgs/grafana*.rpm'] %}
{% elif base_package_type == 'deb' %}
  {% set monasca_grafana_packages = ['/grafana_pkgs/grafana*.deb'] %}
{% endif %}

{{ macros.install_packages(monasca_grafana_packages | customizable("packages")) }}

{% endblock %}

RUN grafana-cli plugins install monasca-datasource \
    && chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/kolla_grafana_sudoers \
    && chmod 755 /usr/local/bin/kolla_extend_start

{% block monasca_grafana_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER monasca
