FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block octavia_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.enable_extra_repos(['openvswitch']) }}
{{ macros.configure_user(name='octavia') }}

{% if base_package_type == 'rpm' %}

    {% set octavia_base_packages = [
        'python3-openvswitch${KOLLA_RPM_OVS_VERSION}'
    ] %}

{% elif base_package_type == 'deb' %}

    {% set octavia_base_packages = [
        'python3-openvswitch'
    ] %}

{% endif %}

{{ macros.install_packages(octavia_base_packages | customizable("packages")) }}

ADD octavia-base-archive /octavia-base-source

{% set octavia_base_pip_packages = [
    '/octavia'
] %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN ln -s /octavia-base-source/* octavia \
    && {{ macros.install_pip(octavia_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/octavia \
    && cp -r /octavia/etc/* /etc/octavia/ \
    && cp /octavia/etc/audit/octavia_api_audit_map.conf.sample /etc/octavia/octavia_api_audit_map.conf \
    && touch /usr/local/bin/kolla_octavia_extend_start \
    && chmod 644 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_octavia_extend_start

{{ macros.kolla_patch_sources() }}

{% block octavia_base_footer %}{% endblock %}
