FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block octavia_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='octavia') }}

{% if install_type == 'binary' %}
    {% if base_package_type == 'rpm' %}
        {% set octavia_base_packages = [
            'openstack-octavia-common'
        ] %}
    {% elif base_package_type == 'deb' %}
        {% set octavia_base_packages = [
            'octavia-common'
        ] %}
    {% endif %}

{{ macros.install_packages(octavia_base_packages | customizable("packages")) }}

{% elif install_type == 'source' %}
ADD octavia-base-archive /octavia-base-source

{% set octavia_base_pip_packages = [
    '/octavia'
] %}

RUN ln -s /octavia-base-source/* octavia \
    && {{ macros.install_pip(octavia_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/octavia \
    && cp -r /octavia/etc/* /etc/octavia/ \
    && chown -R octavia: /etc/octavia
{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN touch /usr/local/bin/kolla_octavia_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_octavia_extend_start

{% block octavia_base_footer %}{% endblock %}
