FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block trove_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}

    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}
        {% set trove_base_packages = ['openstack-trove-common'] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set trove_base_packages = ['trove-common'] %}
    {% endif %}

{{ macros.install_packages(trove_base_packages | customizable("packages")) }}

{% elif install_type == 'source' %}

ADD trove-base-archive /trove-base-source
RUN ln -s trove-base-source/* trove \
    && useradd --user-group trove \
    && /var/lib/kolla/venv/bin/pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt /trove \
    && mkdir -p /etc/trove /var/log/trove /home/trove \
    && cp -r /trove/etc/* /etc/trove/ \
    && chown -R trove: /etc/trove /var/log/trove /home/trove

{% endif %}

RUN usermod -a -G kolla trove

{% block trove_base_footer %}{% endblock %}
{% block footer %}{% endblock %}
