FROM {{ namespace }}/{{ infra_image_prefix }}base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block qdrouterd_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='qdrouterd') }}

{{ macros.enable_extra_repos(['qdrouterd']) }}

{% block qdrouterd_install %}
{% if base_package_type == 'rpm' %}
    {% set qdrouterd_packages = [
        'cyrus-sasl-lib',
        'cyrus-sasl-plain',
        'qpid-dispatch-router',
        'qpid-dispatch-tools'
    ] %}

{% if base_distro in ['centos'] %}
# make sure qpid is pulled from centos-openstack-RELEASE (RDO) repo
{{ macros.disable_extra_repos(['extras', 'opstools']) }}
{% endif %}

{{ macros.install_packages(qdrouterd_packages | customizable("packages")) }}

{% endif %}
{% endblock %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
COPY qdrouterd_sudoers /etc/sudoers.d/kolla_qdrouterd_sudoers
RUN chmod 755 /usr/local/bin/kolla_extend_start \
    && chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/kolla_qdrouterd_sudoers

{% block qdrouterd_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER qdrouterd
