FROM {{ namespace }}/{{ image_prefix }}sensu-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block sensu_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% block sensu_api_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER sensu
