---
- name: Starting mariadb container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ mariadb_image_full }}"
    name: "mariadb"
    volumes:
      - "{{ node_config_directory }}/mariadb/:{{ container_config_directory }}/:ro"
      - "mariadb:/var/lib/mysql"
      - "kolla_logs:/var/log/kolla/"
  when: delegate_host != 'None' or
        ( groups['mariadb'] | length ) == 1 or
        ( delegate_host == 'None' and inventory_hostname != groups['mariadb'][0] )

- name: Waiting for MariaDB service to be ready
  wait_for:
    host: "{{ hostvars[inventory_hostname]['ansible_' + api_interface]['ipv4']['address'] }}"
    port: "{{ mariadb_port }}"
    connect_timeout: 1
    timeout: 60
    search_regex: "MariaDB"
