FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

# Install required packages
RUN yum install -y \
        ebtables \
        openstack-neutron-linuxbridge \
    && yum clean all

    {% elif base_distro in ['ubuntu'] %}

RUN apt-get install -y --no-install-recommends \
        ebtables \
        neutron-plugin-linuxbridge-agent \
    && apt-get clean

    {% endif %}
{% elif install_type == 'source' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

# Install required packages
RUN yum install -y \
        ebtables \
        bridge-utils \
    && yum clean all

    {% elif base_distro in ['ubuntu'] %}
RUN apt-get install -y \
        ebtables \
        bridge-utils \
    && apt-get clean

    {% endif %}
{% endif %}

{{ include_footer }}

USER neutron
