FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block neutron_linuxbridge_agent_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}

        {% set neutron_linuxbridge_agent_packages = [
            'ebtables',
            'openstack-neutron-linuxbridge'
        ] %}

    {% elif base_distro in ['ubuntu'] %}

        {% set neutron_linuxbridge_agent_packages = [
            'ebtables',
            'neutron-plugin-linuxbridge-agent'
        ] %}

    {% endif %}

{% elif install_type == 'source' %}

    {% set neutron_linuxbridge_agent_packages = [
        'bridge-utils',
        'ebtables'
    ] %}

{% endif %}

{{ macros.install_packages(neutron_linuxbridge_agent_packages | customizable("packages")) }}

{% block neutron_linuxbridge_agent_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
