FROM {{ namespace }}/{{ image_prefix }}octavia-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block octavia_health_manager_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set octavia_health_manager_packages = [
                'openstack-octavia-health-manager'
        ] %}
    {% elif base_distro in ['ubuntu'] %}
RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
            && /bin/false
    {% endif %}

{{ macros.install_packages(octavia_health_manager_packages | customizable("packages")) }}

{% endif %}

{% block octavia_health_manager_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER octavia
