FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block ironic_inspector_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='ironic-inspector') }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set ironic_inspector_packages = ['openstack-ironic-inspector'] %}
    {% elif base_distro in ['debian', 'ubuntu'] %}
        {% set ironic_inspector_packages = [
            'iptables',
            'ironic-inspector'
        ] %}
    {% endif %}

{{ macros.install_packages(ironic_inspector_packages | customizable("packages")) }}

{% elif install_type == 'source' %}
    {% if base_distro in ['debian', 'ubuntu'] %}
        {% set ironic_inspector_packages = ['iptables'] %}
    {% endif %}

{{ macros.install_packages(ironic_inspector_packages | customizable("packages")) }}

ADD ironic-inspector-archive /ironic-inspector-source

{% set ironic_inspector_pip_packages = [
    '/ironic-inspector'
] %}

RUN ln -s ironic-inspector-source/* ironic-inspector \
    && {{ macros.install_pip(ironic_inspector_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/ironic-inspector \
    && cp /ironic-inspector/rootwrap.conf /etc/ironic-inspector/ \
    && cp -r /ironic-inspector/rootwrap.d/ /etc/ironic-inspector/ \
    && sed -i 's|^exec_dirs.*|exec_dirs=/var/lib/kolla/venv/bin,/sbin,/usr/sbin,/bin,/usr/bin,/usr/local/bin,/usr/local/sbin|g' /etc/ironic-inspector/rootwrap.conf

ADD ironic_inspector_sudoers /etc/sudoers.d/kolla_ironic_inspector_sudoers
RUN chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/kolla_ironic_inspector_sudoers

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN chmod 755 /usr/local/bin/kolla_extend_start \
    && chown -R ironic-inspector: /etc/ironic-inspector

{% block ironic_inspector_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER ironic-inspector
