FROM {{ namespace }}/{{ image_prefix }}octavia-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block octavia_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set octavia_api_packages = [
            'openstack-octavia-api'
        ] %}
    {% elif base_distro in ['debian', 'ubuntu'] %}
RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
            && /bin/false
    {% endif %}

{{ macros.install_packages(octavia_api_packages | customizable("packages")) }}

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_octavia_extend_start
RUN chmod 755 /usr/local/bin/kolla_octavia_extend_start

{% block octavia_api_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER octavia
