FROM {{ namespace }}/{{ image_prefix }}monasca-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block monasca_log_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

ADD monasca-log-api-archive /monasca-log-api-source
RUN ln -s monasca-log-api-source/* monasca-log \
    && {{ macros.install_pip(['/monasca-log'] | customizable("pip_packages")) }}

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_monasca_extend_start
RUN chmod 755 /usr/local/bin/kolla_monasca_extend_start

{% block monasca_log_api_footer %}{% endblock %}

{% block footer %}{% endblock %}


