FROM {{ namespace }}/{{ image_prefix }}tacker-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block tacker_conductor_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.kolla_patch_sources() }}

{% block tacker_conductor_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER tacker
