FROM {{ namespace }}/{{ image_prefix }}nova-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        openstack-nova-compute \
    && yum clean all

    {% elif base_distro in ['ubuntu'] %}

RUN apt-get install -y --no-install-recommends \
        nova-compute \
    && apt-get clean

RUN rm /etc/nova/nova-compute.conf

    {% endif %}
{% endif %}

{{ include_footer }}

USER nova
