FROM {{ namespace }}/{{ image_prefix }}nova-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block nova_compute_ironic_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

        {% set nova_compute_ironic_packages = [
            'openstack-nova-compute'
        ] %}

{{ macros.install_packages(nova_compute_ironic_packages | customizable("packages")) }}

    {% elif base_distro in ['ubuntu'] %}

        {% set nova_compute_ironic_packages = [
            'nova-compute'
        ] %}

{{ macros.install_packages(nova_compute_ironic_packages | customizable("packages")) }}

RUN rm /etc/nova/nova-compute.conf

    {% endif %}
{% endif %}

{% block nova_compute_ironic_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER nova
