FROM {{ namespace }}/{{ image_prefix }}nova-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block nova_compute_ironic_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% set nova_compute_ironic_packages = ['genisoimage'] %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}

        {% set nova_compute_ironic_packages = nova_compute_ironic_packages + [
            'nvme-cli',
            'openstack-nova-compute'
        ] %}
{{ macros.install_packages(nova_compute_ironic_packages | customizable("packages")) }}

    {% elif base_distro in ['debian', 'ubuntu'] %}

        {% set nova_compute_ironic_packages = nova_compute_ironic_packages + [
            'nova-compute'
        ] %}
{{ macros.install_packages(nova_compute_ironic_packages | customizable("packages")) }}

RUN rm /etc/nova/nova-compute.conf

    {% endif %}

{% elif install_type == 'source'  %}

{{ macros.install_packages(nova_compute_ironic_packages | customizable("packages")) }}

{% endif %}

{% block nova_compute_ironic_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER nova
