FROM {{ namespace }}/{{ image_prefix }}masakari-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block masakari_engine_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.kolla_patch_sources() }}

{% block masakari_engine_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER masakari
