FROM {{ namespace }}/{{ image_prefix }}designate-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block designate_sink_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}
       {% set designate_sink_packages = [
            'openstack-designate-sink',
            'python-designateclient'
        ] %}
    {% elif base_distro in ['ubuntu'] %}
       {% set designate_sink_packages = [
            'designate-sink',
            'python-designateclient'
        ] %}
    {% endif %}
{{ macros.install_packages(designate_sink_packages | customizable("packages")) }}
{% endif %}

{% block designate_sink_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER designate
