FROM {{ namespace }}/{{ image_prefix }}designate-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum install -y \
        openstack-designate-sink \
        python-designateclient \
    && yum clean all

    {% endif %}
{% endif %}

{{ include_footer }}

USER designate
