FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block searchlight_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='searchlight') }}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

ADD searchlight-base-archive /searchlight-base-source

{% set searchlight_base_pip_packages = [
    '/searchlight'
] %}

RUN ln -s searchlight-base-source/* searchlight \
    && {{ macros.install_pip(searchlight_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/searchlight \
    && cp -r /searchlight/etc/* /etc/searchlight \
    && chown -R searchlight: /etc/searchlight

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN touch /usr/local/bin/kolla_searchlight_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_searchlight_extend_start

{% block searchlight_base_footer %}{% endblock %}
