---
prelude: >
    In Newton cycle we included means to change various things in Kolla images
    using override file. Full customization guide can be found here
    https://docs.openstack.org/kolla/latest/image-building.html#dockerfile-customisation
features:
    - Customization mechanism for dockerfile
    - Customization implemented in most of OpenStack services
    - Ability to modify repositories, packages installed and keys installed
    - Ability to inject or override code in certain placess across dockerfiles
