FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        openstack-aodh-common \
    && yum clean all

    {% elif base_distro in ['ubuntu'] %}

RUN apt-get install -y --no-install-recommends \
        aodh-common \
    && apt-get clean

    {% endif %}

{% elif install_type == 'source' %}

ADD aodh-base-archive /aodh-base-source
RUN ln -s aodh-base-source/* aodh \
    && useradd --user-group aodh \
    && /var/lib/kolla/venv/bin/pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt /aodh \
    && mkdir -p /etc/aodh /var/log/aodh /home/aodh \
    && cp -r /aodh/etc/* /etc/aodh/ \
    && chown -R aodh: /etc/aodh /var/log/aodh /home/aodh

{% endif %}

RUN usermod -a -G kolla aodh
