FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-nova-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        novnc \
        openstack-nova-novncproxy \
    && yum clean all

    {% endif %}
{% elif install_type == 'source' %}

ADD nova-novncproxy-archive /usr/share/nova-novncproxy-source
RUN cd /usr/share && ln -s nova-novncproxy-source/* novnc

{% endif %}

COPY start.sh /

CMD ["/start.sh"]

{{ include_footer }}
