FROM {{ namespace }}/{{ image_prefix }}nova-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block nova_novncproxy_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

        {% set nova_novncproxy_packages = [
            'novnc',
            'openstack-nova-novncproxy'
        ] %}

    {% elif base_distro in ['ubuntu'] %}

        {% set nova_novncproxy_packages = [
            'nova-novncproxy'
        ] %}

    {% endif %}

{{ macros.install_packages(nova_novncproxy_packages | customizable("packages")) }}

{% elif install_type == 'source' %}

ADD nova-novncproxy-archive /usr/share/nova-novncproxy-source
RUN cd /usr/share \
    && ln -s nova-novncproxy-source/* novnc \
    && chown -R nova: /usr/share/nova-novncproxy-source

{% endif %}

{% block nova_novncproxy_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER nova
