FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block heat_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='heat') }}

{% if install_type == 'binary' %}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
    {% set heat_base_packages = ['openstack-heat-common'] %}
{% elif base_distro in ['ubuntu'] %}
    {% set heat_base_packages = ['heat-common'] %}
{% endif %}
{{ macros.install_packages(heat_base_packages | customizable("packages")) }}

{% elif install_type == 'source' %}

ADD heat-base-archive /heat-base-source
RUN ln -s heat-base-source/* heat \
    && /var/lib/kolla/venv/bin/pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt /heat \
    && mkdir -p /etc/heat \
    && cp -r /heat/etc/heat/* /etc/heat/ \
    && chown -R heat: /etc/heat

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN touch /usr/local/bin/kolla_heat_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_heat_extend_start

{% block heat_base_footer %}{% endblock %}
