FROM {{ namespace }}/{{ image_prefix }}vitrage-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block vitrage_notifier_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% block vitrage_notifier_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER vitrage
