FROM {{ namespace }}/{{ image_prefix }}vitrage-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block vitrage_notifier_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}

    {% if base_package_type == 'rpm' %}

        {% set vitrage_notifier_packages = [
            'openstack-vitrage-notifier'
        ] %}

{{ macros.install_packages(vitrage_notifier_packages | customizable("packages")) }}

    {% elif base_package_type == 'deb' %}
    {% if base_distro == 'debian' %}

        {% set vitrage_notifier_packages = [
            'vitrage-notifier'
        ] %}

{{ macros.install_packages(vitrage_notifier_packages | customizable("packages")) }}

    {% else %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

    {% endif %}
    {% endif %}

{% endif %}

{% block vitrage_notifier_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER vitrage
