FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block senlin_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='senlin') }}

{% if install_type == 'binary' %}
    {% if base_package_type == 'rpm' %}
        {% set senlin_base_packages = ['openstack-senlin-common'] %}

    {% elif base_package_type == 'deb' %}
        {% set senlin_base_packages = ['senlin-common'] %}
    {% endif %}

{{ macros.install_packages(senlin_base_packages | customizable("packages")) }}

{% elif install_type == 'source' %}

ADD senlin-base-archive /senlin-base-source

{% set senlin_base_pip_packages = [
    '/senlin'
] %}

RUN ln -s senlin-base-source/* senlin \
    && {{ macros.install_pip(senlin_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/senlin \
    && cp -r /senlin/etc/senlin/* /etc/senlin \
    && chown -R senlin: /etc/senlin

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN touch /usr/local/bin/kolla_senlin_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_senlin_extend_start

{% block senlin_base_footer %}{% endblock %}
