FROM {{ namespace }}/{{ image_prefix }}redis-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block redis_sentinel_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'rpm' %}
    {% set redis_sentinel_packages = ['redis'] %}
{% elif base_package_type == 'deb' %}
    {% set redis_sentinel_packages = ['redis-sentinel'] %}
{% endif %}
{{ macros.install_packages(redis_sentinel_packages | customizable("packages")) }}

{% block redis_sentinel_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER redis
