FROM {{ namespace }}/{{ image_prefix }}redis-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block redis_sentinel_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'rpm' %}
    {% set redis_sentinel_packages = ['redis'] %}
{% elif base_package_type == 'deb' %}
    {% set redis_sentinel_packages = ['redis-sentinel'] %}
{% endif %}
{{ macros.install_packages(redis_sentinel_packages | customizable("packages")) }}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 644 /usr/local/bin/kolla_extend_start

{{ macros.kolla_patch_sources() }}

{% block redis_sentinel_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER redis
