FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block nova_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='nova', groups='qemu') }}

{% if base_package_type == 'rpm' %}

{{ macros.enable_extra_repos(['openvswitch']) }}

    {% set nova_base_packages = [
            'openvswitch${KOLLA_RPM_OVS_VERSION}',
            'python3-openvswitch${KOLLA_RPM_OVS_VERSION}'
    ] %}
    {% if base_arch == 'x86_64' %}
        {% set nova_base_packages = nova_base_packages + [
            'edk2-ovmf'
        ] %}
    {% elif base_arch == 'aarch64' %}
        {% set nova_base_packages = nova_base_packages + [
            'edk2-aarch64'
        ] %}
    {% endif %}

{% elif base_package_type == 'deb' %}

    {% set nova_base_packages = [
        'dnsmasq',
        'ebtables',
        'iproute2',
        'iptables',
        'openssh-client',
        'openvswitch-switch',
        'python3-libvirt',
        'python3-openvswitch'
    ] %}
    {% if base_arch == 'x86_64' %}
        {% set nova_base_packages = nova_base_packages + [
            'ovmf'
        ] %}
    {% elif base_arch == 'aarch64' %}
        {% set nova_base_packages = nova_base_packages + [
            'qemu-efi-aarch64',
        ] %}
    {% endif %}

{% endif %}

{{ macros.install_packages(nova_base_packages | customizable("packages")) }}

ADD nova-base-archive /nova-base-source
ADD plugins-archive /

{% set nova_base_pip_packages = [
    '/nova'
] %}

{% set nova_base_plugins_pip_packages = [
    '/plugins/*'
] %}

COPY nova_sudoers /etc/sudoers.d/kolla_nova_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN ln -s nova-base-source/* nova \
    && {{ macros.install_pip(nova_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/nova/ \
    && cp -r /nova/etc/nova/* /etc/nova/ \
    && cp /var/lib/kolla/venv/etc/pycadf/nova_api_audit_map.conf /etc/nova/ \
    && sed -i 's|^exec_dirs.*|exec_dirs=/var/lib/kolla/venv/bin,/sbin,/usr/sbin,/bin,/usr/bin,/usr/local/bin,/usr/local/sbin|g' /etc/nova/rootwrap.conf \
    && if [ "$(ls /plugins)" ]; then \
        {{ macros.install_pip(nova_base_plugins_pip_packages) }}; \
       fi \
    && chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/kolla_nova_sudoers \
    && touch /usr/local/bin/kolla_nova_extend_start \
    && chmod 644 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_nova_extend_start

{{ macros.kolla_patch_sources() }}

{% block nova_base_footer %}{% endblock %}
