---
- name: Ensuring config directory exists
  file:
    path: "{{ node_config_directory }}/glance-api"
    state: "directory"
  when: inventory_hostname in groups['glance-api']

- name: Copying over config(s)
  template:
    src: roles/ceph/templates/ceph.conf.j2
    dest: "{{ node_config_directory }}/glance-api/ceph.conf"
  when: inventory_hostname in groups['glance-api']

- include: ../../ceph_pools.yml
  vars:
    pool_name: "{{ glance_pool_name }}"
    pool_type: "{{ glance_pool_type }}"
    cache_mode: "{{ glance_cache_mode }}"

# TODO(SamYaple): Improve changed_when tests
- name: Pulling cephx keyring
  command: docker exec ceph_mon ceph auth get-or-create client.glance mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool={{ ceph_glance_pool_name }}, allow rwx pool={{ ceph_glance_pool_name }}-cache'
  register: cephx_key
  delegate_to: "{{ groups['ceph-mon'][0] }}"
  changed_when: False
  run_once: True

- name: Pushing cephx keyring
  copy:
    content: "{{ cephx_key.stdout }}\n\r"
    dest: "{{ node_config_directory }}/glance-api/ceph.client.glance.keyring"
    mode: "0600"
  when: inventory_hostname in groups['glance-api']
