FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block neutron_bgp_dragent_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel']  %}
        {% set neutron_bgp_dragent_packages = [
            'openstack-neutron-bgp-dragent'
        ] %}

    {% elif base_distro in ['ubuntu', 'debian'] %}
        {% set neutron_bgp_dragent_packages = [
            'neutron-bgp-dragent'
        ] %}
    {% endif %}

{{ macros.install_packages(neutron_bgp_dragent_packages | customizable("packages")) }}

{% elif install_type == 'source'  %}

ADD neutron-bgp-dragent-archive /neutron-bgp-dragent-source

    {% set neutron_bgp_dragent_pip_packages = [
        '/neutron_dynamic_routing'
    ] %}

RUN ln -s neutron-bgp-dragent-source/* neutron_dynamic_routing \
    && {{ macros.install_pip(neutron_bgp_dragent_pip_packages | customizable("pip_packages")) }}

{% endif %}

{% block neutron_bgp_dragent_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
