FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block neutron_bgp_dragent_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

ADD neutron-bgp-dragent-archive /neutron-bgp-dragent-source

    {% set neutron_bgp_dragent_pip_packages = [
        '/neutron_dynamic_routing'
    ] %}

RUN ln -s neutron-bgp-dragent-source/* neutron_dynamic_routing \
    && {{ macros.install_pip(neutron_bgp_dragent_pip_packages | customizable("pip_packages")) }}

{{ macros.kolla_patch_sources() }}

{% block neutron_bgp_dragent_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
