FROM {{ namespace }}/{{ image_prefix }}ironic-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN pip install ironic-discoverd
# discoverd no longer in delorean 9/28/2015, switch to inspector on TODO
#RUN yum -y install \
#    openstack-ironic-discoverd \
#    && yum clean all

    {% endif %}

{% elif install_type == 'source' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% endif %}

COPY start.sh /

CMD ["/start.sh"]

{{ include_footer }}
