FROM {{ namespace }}/{{ image_prefix }}congress-base:{{ tag }}
LABEL maintainer="{{ maintainer }}"

{% block congress_policy_engine_header %}{% endblock %}

{% block congress_policy_engine_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER congress
