FROM {{ namespace }}/{{ image_prefix }}congress-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block congress_policy_engine_header %}{% endblock %}

{% block congress_policy_engine_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER congress
