FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install openstack-manila \
    && yum clean all

    {% endif %}
{% elif install_type == 'source' %}

ADD manila-base-archive /manila-base-source
RUN ln -s manila-base-source/* manila \
    && useradd --user-group manila \
    && /var/lib/kolla/venv/bin/pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt /manila \
    && mkdir -p /etc/manila /var/lib/manila /var/cache/manila /home/manila \
    && cp -r /manila/etc/manila/* /etc/manila/ \
    && chown -R manila: /etc/manila /var/lib/manila /var/cache/manila /home/manila \
    && sed -i 's|^exec_dirs.*|exec_dirs=/var/lib/kolla/venv/bin,/sbin,/usr/sbin,/bin,/usr/bin,/usr/local/bin,/usr/local/sbin|g' /etc/manila/rootwrap.conf

COPY manila_sudoers /etc/sudoers.d/manila_sudoers
RUN chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/manila_sudoers

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN touch /usr/local/bin/kolla_manila_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_manila_extend_start

RUN usermod -a -G kolla manila
