FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block manila_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='manila') }}

{% if base_package_type == 'rpm' %}

{{ macros.enable_extra_repos(['openvswitch']) }}

    {% set manila_base_packages = ['openvswitch${KOLLA_RPM_OVS_VERSION}'] %}

{% elif base_package_type == 'deb' %}

    {% set manila_base_packages = ['openvswitch-switch'] %}

{% endif %}

{{ macros.install_packages(manila_base_packages | customizable("packages")) }}

ADD manila-base-archive /manila-base-source

{% set manila_base_pip_packages = [
    '/manila'
] %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
COPY manila_sudoers /etc/sudoers.d/kolla_manila_sudoers

RUN ln -s manila-base-source/* manila \
    && {{ macros.install_pip(manila_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/manila /var/cache/manila \
    && cp -r /manila/etc/manila/* /etc/manila/ \
    && chown -R manila: /var/cache/manila \
    && sed -i 's|^exec_dirs.*|exec_dirs=/var/lib/kolla/venv/bin,/sbin,/usr/sbin,/bin,/usr/bin,/usr/local/bin,/usr/local/sbin|g' /etc/manila/rootwrap.conf \
    && chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/kolla_manila_sudoers \
    && touch /usr/local/bin/kolla_manila_extend_start \
    && chmod 644 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_manila_extend_start

{{ macros.kolla_patch_sources() }}

{% block manila_base_footer %}{% endblock %}
