FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

ENV KUBERNETES_VERSION=v1.5.1

ENV KUBERNETES_DOWNLOAD_ROOT=https://storage.googleapis.com/kubernetes-release/release/${KUBERNETES_VERSION}/bin/linux/amd64

{% block kube_base_header %}{% endblock %}

{% block kube_base_footer %}{% endblock %}
