FROM {{ namespace }}/{{ image_prefix }}keystone-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block keystone_fernet_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'rpm' %}
    {% set keystone_fernet_packages = [
        'cronie',
        'openssh-clients',
        'rsync'
    ] %}
{% elif base_package_type == 'deb' %}
    {% set keystone_fernet_packages = [
        'cron',
        'openssh-client',
        'rsync'
    ] %}
{% endif %}
{{ macros.install_packages(keystone_fernet_packages | customizable("packages")) }}

COPY fetch_fernet_tokens.py /usr/bin/
COPY keystone_bootstrap.sh /usr/local/bin/kolla_keystone_bootstrap
COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_keystone_bootstrap /usr/bin/fetch_fernet_tokens.py

{% block keystone_fernet_footer %}{% endblock %}
{% block footer %}{% endblock %}
