FROM {{ namespace }}/{{ image_prefix }}ceilometer-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block ceilometer_api_header %}{% endblock %}

COPY extend_start.sh /usr/local/bin/kolla_ceilometer_extend_start
RUN chmod 755 /usr/local/bin/kolla_ceilometer_extend_start

{% block ceilometer_api_footer %}{% endblock %}
{% block footer %}{% endblock %}
