#!/bin/bash
file_path=$1
limit_seconds=$2

# if the file doesn't exist, return 1
if [ ! -f $file_path ]; then
    echo "${file_path} does not exist for file modification check"
    exit 1
fi
curr_time=$(date +%s)
last_mod=$(stat -c '%Y' $file_path)
limit_epoch=$(( curr_time-limit_seconds ))
if [ ${limit_epoch} -gt ${last_mod} ]; then
    exit 1
fi
