FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block vmtp_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='vmtp') }}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

{% set vmtp_pip_packages = [
    '/vmtp'
] %}

ADD vmtp-archive /vmtp-source
RUN ln -s vmtp-source/* vmtp \
    && {{ macros.install_pip(vmtp_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/vmtp \
    && chown -R vmtp: /etc/vmtp

{% endif %}

COPY vmtp_sudoers /etc/sudoers.d/kolla_vmtp_sudoers
RUN chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/kolla_vmtp_sudoers

{% block vmtp_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER vmtp
