---
- project-template:
    name: kolla-scenario-prometheus-opensearch
    check:
      jobs:
        - kolla-ansible-debian-trixie-prometheus-opensearch: &files
            files: ^kolla/docker/(base|fluentd|grafana|opensearch|prometheus)/
        - kolla-ansible-debian-trixie-prometheus-opensearch-upgrade: *files
        - kolla-ansible-rocky-10-prometheus-opensearch: *files
        - kolla-ansible-rocky-10-prometheus-opensearch-upgrade: *files
        - kolla-ansible-ubuntu-noble-prometheus-opensearch: *files
        - kolla-ansible-ubuntu-noble-prometheus-opensearch-upgrade: *files
