FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-nova-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['fedora', 'centos', 'oraclelinux'] %}

RUN yum -y install openstack-nova-api \
    && yum clean all

    {% endif %}
{% endif %}

COPY start.sh /
COPY config-external.sh /opt/kolla/

CMD ["/start.sh"]

{{ include_footer }}
