FROM {{ namespace }}/{{ image_prefix }}placement-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block placement_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_package_type == 'rpm' %}

        {% set placement_api_packages = [
            'httpd',
            'mod_ssl',
            'openstack-placement-api',
            'python3-mod_wsgi'
        ] %}

{{ macros.install_packages(placement_api_packages | customizable("packages")) }}
RUN sed -i -r 's,^(Listen 80),#\1,' /etc/httpd/conf/httpd.conf \
    && sed -i -r 's,^(Listen 443),#\1,' /etc/httpd/conf.d/ssl.conf

    {% elif base_package_type == 'deb' %}

        {% set placement_api_packages = [
            'apache2',
            'libapache2-mod-wsgi-py3',
            'placement-api'
        ] %}

{{ macros.install_packages(placement_api_packages | customizable("packages")) }}
RUN truncate -s 0 /etc/apache2/ports.conf \
    && rm -f /etc/apache2/sites-enabled/placement-api.conf

    {% endif %}
{% elif install_type == 'source' %}
    {% if base_package_type == 'rpm' %}

        {% set placement_api_packages = [
            'httpd',
            'mod_ssl',
            'python3-mod_wsgi'
        ] %}

{{ macros.install_packages(placement_api_packages | customizable("packages")) }}
RUN sed -i -r 's,^(Listen 80),#\1,' /etc/httpd/conf/httpd.conf \
    && sed -i -r 's,^(Listen 443),#\1,' /etc/httpd/conf.d/ssl.conf
    {% elif base_package_type == 'deb' %}

        {% set placement_api_packages = [
            'apache2',
            'libapache2-mod-wsgi-py3'
        ] %}

{{ macros.install_packages(placement_api_packages | customizable("packages")) }}
RUN truncate -s 0 /etc/apache2/ports.conf

    {% endif %}
{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_placement_extend_start

{% block placement_api_footer %}{% endblock %}
{% block footer %}{% endblock %}
