FROM {{ namespace }}/{{ image_prefix }}prometheus-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block mysqld_exporter_header %}{% endblock %}

{% block mysqld_exporter_install %}
ADD prometheus-mysqld-exporter-archive /prometheus-mysqld-exporter-source

RUN ln -s /prometheus-mysqld-exporter-source/* prometheus-mysqld-exporter \ 
    && mkdir -p /opt/mysqld_exporter \
    && cp /prometheus-mysqld-exporter/mysqld_exporter /opt/mysqld_exporter/
{% endblock %}

{% block mysqld_exporter_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER prometheus
