FROM {{ namespace }}/{{ image_prefix }}watcher-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block watcher_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set watcher_api_packages = ['openstack-watcher-api'] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set watcher_api_packages = ['watcher-api'] %}
    {% endif %}
{{ macros.install_packages(watcher_api_packages | customizable("packages")) }}
{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_watcher_extend_start
RUN chmod 755 /usr/local/bin/kolla_watcher_extend_start

{% block watcher_api_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER watcher
