FROM {{ namespace }}/{{ image_prefix }}redis-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block redis_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'rpm' %}
    {% set redis_packages = ['redis'] %}
{% elif base_package_type == 'deb' %}
    {% set redis_packages = ['redis-server'] %}
{% endif %}
{{ macros.install_packages(redis_packages | customizable("packages")) }}

{{ macros.kolla_patch_sources() }}

{% block redis_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER redis
