FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block neutron_networking_sfc_agent_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

ADD neutron-sfc-agent-archive /neutron-sfc-agent-source

{% set neutron_sfc_agent_pip_packages = [
    '/neutron-sfc-agent'
] %}

RUN ln -s neutron-sfc-agent-source/* neutron-sfc-agent \
    && {{ macros.install_pip(neutron_sfc_agent_pip_packages | customizable("pip_packages")) }}

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_neutron_extend_start
RUN chmod 755 /usr/local/bin/kolla_neutron_extend_start

{% block neutron_sfc_agent_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
