# TODO(egonzalez): SFC image is deprecated and will be removed during Queens release
FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block neutron_networking_sfc_agent_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

COPY extend_start.sh /usr/local/bin/kolla_neutron_extend_start
RUN chmod 755 /usr/local/bin/kolla_neutron_extend_start

{% block neutron_sfc_agent_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
