FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block neutron_networking_sfc_agent_header %}{% endblock %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

ADD neutron-sfc-agent-archive /neutron-sfc-agent-source
RUN ln -s neutron-sfc-agent-source/* neutron-sfc-agent \
    && /var/lib/kolla/venv/bin/pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt /neutron-sfc-agent

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_neutron_extend_start
RUN chmod 755 /usr/local/bin/kolla_neutron_extend_start

{% block neutron_sfc_agent_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
