FROM {{ namespace }}/{{ image_prefix }}searchlight-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block searchlight_api_header %}{% endblock %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_searchlight_extend_start
RUN chmod 755 /usr/local/bin/kolla_searchlight_extend_start

{% block searchlight_api_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER searchlight
