- project:
    name: openstack/kolla
    check:
      jobs:
        - kolla-build-centos-binary
        - kolla-build-centos-source
        - kolla-build-ubuntu-binary
        - kolla-build-ubuntu-source
        - kolla-build-oraclelinux-binary
        - kolla-build-oraclelinux-source
        - kolla-ansible-centos-source:
            required-projects:
              - openstack/kolla-ansible
              - openstack/requirements
        - kolla-ansible-centos-binary:
            required-projects:
              - openstack/kolla-ansible
              - openstack/requirements
        - kolla-ansible-ubuntu-source:
            required-projects:
              - openstack/kolla-ansible
              - openstack/requirements
        - kolla-ansible-ubuntu-binary:
            required-projects:
              - openstack/kolla-ansible
              - openstack/requirements
        - kolla-ansible-oraclelinux-source:
            required-projects:
              - openstack/kolla-ansible
              - openstack/requirements
        - kolla-ansible-oraclelinux-binary:
            required-projects:
              - openstack/kolla-ansible
              - openstack/requirements
    gate:
      jobs:
        - kolla-build-centos-source
        - kolla-build-ubuntu-source
        - kolla-build-oraclelinux-source
    periodic-stable:
      jobs:
        - kolla-publish-centos-source
        - kolla-publish-centos-binary
        - kolla-publish-ubuntu-source
        - kolla-publish-ubuntu-binary
        - kolla-publish-oraclelinux-source
        - kolla-publish-oraclelinux-binary
    release:
      jobs:
        - kolla-publish-centos-source
        - kolla-publish-centos-binary
        - kolla-publish-ubuntu-source
        - kolla-publish-ubuntu-binary
        - kolla-publish-oraclelinux-source
        - kolla-publish-oraclelinux-binary

- secret:
    name: kolla_dockerhub_creds_pike
    data:
      password: !encrypted/pkcs1-oaep
        - QLe52Ymma5HJg3K2kgeSEMp7TwarkH8AbEiwcnDTqZ276BUF9wrt+5gPJRfVU1BYty2lq
          CCzhawJJ09TV0WU2SEUKlicWoXQ/hcbYWNlOHVL6/gm9UxZP/GC8d1eyQfbCS7UUHfiHF
          BP5Vbrn5vmK6DHhaVc9cEdXpcrA9cghLINpH6EeLE6ujD9gH5Apol30Qvj0IcpildWCYC
          1rJqc8e/6BwOcLiPhli+A/bbpWxUzJgnFqogEiHLPvUTRyHDA8aCLv9Q6uryzaA0pzt7I
          VY4JcNeM3J43QSTa6G7FxCGDiNOhEDvS31EyoxGZCdDAsN3Yh2nWPCfqr2X8vDk1Sbou7
          ouiU+fKV+sv0f2+2fWNh+bLUOcOpp2gKvFKxpIxt7j5Zm6KBpHRxZelp4wVEPyEyecDN1
          /fV7H4Z4QzH+Lah1F3H19IPvz1FPPaEFdrK5HWsbxa1aS9AY2hn+Th9TPJQSn/jxQvn8D
          IT1GtO+Lr1SNUzrJJXzAdLmnyD9iVFOujzGsVfEbFpMlSetoBTNJl0MxrsYp6cJOqMRSS
          sQZ56jPLxjCBTXoof2E81wbatOXWTLBpBzI5mtTfbcJnWfO93ZB9z2or6PMkWmTtYVji8
          J1xFe2GTCHuPYjrETCPj5k0eCT3DS0PJ71N2mvRnPv5mKJKjhKBokhWscpuq1k=
      user: !encrypted/pkcs1-oaep
        - oRkTqW+FpsUy89wPVYJYk0ZU92yt5C6BKJr7ixVZo9ybcXfYwKDeZCoOeugYNkewJo1hV
          ksCtqbqMc4v2r1cblJK003XCWkXroU5Vx5h/rzFjhxtDK59xUIYS8GzG2OThduqabzyKz
          xm883COjULKPMEL8Q8OxmOvOJ4FcdJnToRWJO9lBQJKLaKleKCor6aadslkSACkDXIcC3
          INIn0t02MZCL96VSBI9RtXaQ5VeyZDzv5QBIquouKYP8/j/yNUb4ilNXJKCJa8kYgo8O8
          sEDtzITJuHorIYxTUc1syzAs9v1BlJF7SUqxTvR2YMFMlV6VADa7r8X4iyyWPmFL5O9c7
          aN9JZhLNGgFLLAK4FISyOsNLZQS/JRjjGT5h9rsslZJsbco4q/Wwj51ezb78NJFhNY7lM
          IpjKWByqSjg2k+1rEXpo6msgZskwYIHPi3xH3njP76127o3adeZQCT72LSnc4LIV6en/G
          tIDqK72tkJpuwiA6u6ti764xXmIhl8Njfhn49cm6Fex9F8YieqPOj3t9mxMzdEZ7gd4Go
          Oz6nUZlML6sEyT0vilbDpo1RRweinE5J8mU+8joxeDpCHXBUYekFmgXDlpg58XmSp96fM
          C/rWcxTKlGJjjlVFZfhRHHy6gWBYH/SoozkbpkWbk0g43SLSxAuITy7nqLggOU=

- job:
    name: kolla-base
    parent: base
    timeout: 10200
    post-timeout: 3600
    pre-run: tests/playbooks/pre.yml
    run: tests/playbooks/run.yml
    post-run: tests/playbooks/post.yml
    attempts: 1
    required-projects:
      - openstack/kolla-ansible
      - openstack/requirements
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*
    vars:
      publisher: false

- job:
    name: kolla-build-centos-binary
    parent: kolla-base
    nodeset: kolla-centos
    voting: false
    vars:
      action: build
      base_distro: centos
      install_type: binary

- job:
    name: kolla-publish-centos-binary
    parent: kolla-build-centos-binary
    post-run: tests/playbooks/publish.yml
    vars:
      publisher: true
    secrets:
      - kolla_dockerhub_creds_pike

- job:
    name: kolla-build-centos-source
    parent: kolla-base
    nodeset: kolla-centos
    vars:
      action: build
      base_distro: centos
      install_type: source

- job:
    name: kolla-publish-centos-source
    parent: kolla-build-centos-source
    post-run: tests/playbooks/publish.yml
    vars:
      publisher: true
    secrets:
      - kolla_dockerhub_creds_pike

- job:
    name: kolla-build-ubuntu-binary
    parent: kolla-base
    nodeset: kolla-ubuntu
    voting: false
    vars:
      action: build
      base_distro: ubuntu
      install_type: binary

- job:
    name: kolla-publish-ubuntu-binary
    parent: kolla-build-ubuntu-binary
    post-run: tests/playbooks/publish.yml
    vars:
      publisher: true
    secrets:
      - kolla_dockerhub_creds_pike

- job:
    name: kolla-build-ubuntu-source
    parent: kolla-base
    nodeset: kolla-ubuntu
    vars:
      action: build
      base_distro: ubuntu
      install_type: source

- job:
    name: kolla-publish-ubuntu-source
    parent: kolla-build-ubuntu-source
    post-run: tests/playbooks/publish.yml
    vars:
      publisher: true
    secrets:
      - kolla_dockerhub_creds_pike

- job:
    name: kolla-build-oraclelinux-binary
    parent: kolla-base
    nodeset: kolla-centos
    voting: false
    vars:
      action: build
      base_distro: oraclelinux
      install_type: binary

- job:
    name: kolla-publish-oraclelinux-binary
    parent: kolla-build-oraclelinux-binary
    post-run: tests/playbooks/publish.yml
    vars:
      publisher: true
    secrets:
      - kolla_dockerhub_creds_pike

- job:
    name: kolla-build-oraclelinux-source
    parent: kolla-base
    nodeset: kolla-centos
    vars:
      action: build
      base_distro: oraclelinux
      install_type: source

- job:
    name: kolla-publish-oraclelinux-source
    parent: kolla-build-oraclelinux-source
    post-run: tests/playbooks/publish.yml
    vars:
      publisher: true
    secrets:
      - kolla_dockerhub_creds_pike
