FROM {{ namespace }}/{{ image_prefix }}karbor-base:{{ tag }}
LABEL maintainer="{{ maintainer }}"

{% block karbor_operationengine_header %}{% endblock %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% endif %}

{% block karbor_operationengine_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER karbor
