FROM {{ namespace }}/{{ image_prefix }}ovn-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block ovn_sb_db_server_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'rpm' %}
    {% set ovn_sb_db_server_packages = [
        'ovn${KOLLA_RPM_OVN_VERSION}-central',
    ] %}

{% elif base_package_type == 'deb' %}
    {% set ovn_sb_db_server_packages = [
        'ovn-central',
    ] %}

{% endif %}
{{ macros.install_packages(ovn_sb_db_server_packages | customizable("packages")) }}

COPY start_sb_db_server.sh /usr/local/bin/start-sb-db-server
RUN chmod 755 /usr/local/bin/start-sb-db-server
COPY extend_start.sh /usr/local/bin/kolla_ovn_extend_start
RUN chmod 644 /usr/local/bin/kolla_ovn_extend_start

{{ macros.kolla_patch_sources() }}

{% block ovn_sb_db_server_footer %}{% endblock %}
{% block footer %}{% endblock %}
