FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block grafana_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.enable_extra_repos(['grafana']) }}

{% set grafana_packages = ['grafana'] %}

{{ macros.configure_user(name='grafana', homedir='/usr/share/grafana') }}

{{ macros.install_packages(grafana_packages | customizable("packages")) }}

WORKDIR /usr/share/grafana

COPY grafana_sudoers /etc/sudoers.d/kolla_grafana_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start

{% block grafana_plugins_install %}

RUN grafana-cli plugins install gnocchixyz-gnocchi-datasource \
    && grafana-cli plugins install grafana-opensearch-datasource

{% endblock %}

RUN chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/kolla_grafana_sudoers \
    && chmod 644 /usr/local/bin/kolla_extend_start

{% block grafana_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER grafana
