FROM {{ namespace }}/{{ image_prefix }}senlin-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block senlin_engine_header %}{% endblock %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% endif %}

{% block senlin_engine_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER senlin
