FROM {{ namespace }}/{{ image_prefix }}mistral-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block mistral_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% set mistral_api_packages = [
] %}
{{ macros.install_packages(mistral_api_packages | customizable("packages")) }}

COPY extend_start.sh /usr/local/bin/kolla_mistral_extend_start
RUN chmod 644 /usr/local/bin/kolla_mistral_extend_start

{{ macros.kolla_patch_sources() }}

{% block mistral_api_footer %}{% endblock %}
{% block footer %}{% endblock %}
