FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"
{% endblock %}

{% block neutron_mlnx_agent_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.kolla_enable_base_repos() }}

{% set neutron_mlnx_agent_packages = [
    'python3-libvirt',
] %}

{{ macros.install_packages(neutron_mlnx_agent_packages | customizable("packages")) }}

{% set neutron_mlnx_agent_pip_packages = [
    'networking-mlnx',
] %}

RUN {{ macros.install_pip(neutron_mlnx_agent_pip_packages | customizable("pip_packages")) }}

{{ macros.kolla_patch_sources() }}

{% block neutron_mlnx_agent_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ macros.kolla_cleanup_repos() }}

USER neutron
