FROM {{ namespace }}/{{ image_prefix }}qinling-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block qinling_api_header %}{% endblock %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_qinling_extend_start
RUN chmod 755 /usr/local/bin/kolla_qinling_extend_start

{% block qinling_api_footer %}{% endblock %}
{% block footer %}{% endblock %}
