FROM {{ namespace }}/{{ image_prefix }}panko-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block panko_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_package_type == 'rpm' %}
        {% set panko_api_packages = [
            'openstack-panko-api'
        ] %}

        {% if distro_python_version.startswith('3') %}
        {% set panko_api_packages = panko_api_packages + [
            'python3-pymongo'
        ] %}
        {% else %}
        {% set panko_api_packages = panko_api_packages + [
            'python-pymongo'
        ] %}
        {% endif %}
    {% elif base_package_type == 'deb' %}
        {% set panko_api_packages = [
            'panko-api',
            'python3-pymongo'
        ] %}

    {% endif %}
{{ macros.install_packages(panko_api_packages | customizable("packages")) }}
{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_panko_extend_start
RUN chmod 755 /usr/local/bin/kolla_panko_extend_start

{% block panko_api_footer %}{% endblock %}
{% block footer %}{% endblock %}
