FROM {{ namespace }}/{{ image_prefix }}panko-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block panko_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
       {% set panko_api_packages = [
            'openstack-panko-api',
            'python-pymongo'
        ] %}

    {% elif base_distro in ['debian', 'ubuntu'] %}
        {% set panko_api_packages = [
            'panko-api',
            'python-pymongo'
        ] %}

    {% endif %}
{{ macros.install_packages(panko_api_packages | customizable("packages")) }}
{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_panko_extend_start
RUN chmod 755 /usr/local/bin/kolla_panko_extend_start

{% block panko_api_footer %}{% endblock %}
{% block footer %}{% endblock %}
