FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if base_distro in ['fedora', 'centos', 'oraclelinux'] %}

RUN yum install -y \
        MariaDB-Galera-server \
        MariaDB-client \
        rsync \
        galera \
        socat \
        hostname \
        percona-xtrabackup \
        pv \
        tar \
        expect \
    && rm -rf /var/lib/mysql/*

{% elif base_distro in ['ubuntu', 'debian'] %}

# At the end of this run statement we symlink two folders to match the folder
# structure of the RPM family for mysql configs. This allows us to not change
# the config-external.sh code
# TODO(SamYaple): Remove that symlink once config-external is updated
RUN apt-get install -y --no-install-recommends \
        mariadb-galera-server \
        percona-xtrabackup \
        socat \
        expect \
    && apt-get clean \
    && rm -rf /var/lib/mysql/* \
    && ln -s /etc/mysql/conf.d/ /etc/my.cnf.d

{% endif %}

COPY config-galera.sh /opt/kolla/config/
COPY config-external.sh /opt/kolla/
COPY start.sh /

CMD ["/start.sh"]
