FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if base_distro in ['fedora', 'centos', 'oraclelinux'] %}

RUN echo "[mariadb]" > /etc/yum.repos.d/MariaDB.repo && \
    echo "name = MariaDB" >> /etc/yum.repos.d/MariaDB.repo && \
    echo "baseurl = http://yum.mariadb.org/10.0/centos7-amd64" >> /etc/yum.repos.d/MariaDB.repo && \
    echo "gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB" >> /etc/yum.repos.d/MariaDB.repo && \
    echo "gpgcheck=1" >> /etc/yum.repos.d/MariaDB.repo

RUN yum install -y http://www.percona.com/redir/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm \
    && sed -i 's|$releasever|centos/latest|g' /etc/yum.repos.d/percona-release.repo \
    && yum install -y \
        MariaDB-Galera-server \
        MariaDB-client \
        rsync \
        galera \
        socat \
        hostname \
        percona-xtrabackup \
        pv \
        tar \
        expect

{% elif base_distro in ['ubuntu', 'debian'] %}

RUN ["/bin/false"]

{% endif %}

COPY config-galera.sh /opt/kolla/config/
COPY config-external.sh /opt/kolla/
COPY start.sh /

CMD ["/start.sh"]
