FROM {{ namespace }}/{{ image_prefix }}nova-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block nova_serialproxy_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_package_type == 'rpm' %}
        {% set nova_serialproxy_packages = [
             'openstack-nova-serialproxy'
         ] %}
    {% elif base_package_type == 'deb' %}
        {% set nova_serialproxy_packages = [
             'nova-serialproxy'
         ] %}
    {% endif %}

{{ macros.install_packages(nova_serialproxy_packages | customizable("packages")) }}

{% endif %}

{% block nova_serialproxy_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER nova
