FROM {{ namespace }}/{{ image_prefix }}hacluster-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block hacluster_corosync_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% set hacluster_corosync_packages = ['corosync'] %}
{{ macros.install_packages(hacluster_corosync_packages | customizable("packages")) }}

{{ macros.kolla_patch_sources() }}

{% block hacluster_corosync_footer %}{% endblock %}
