FROM {{ namespace }}/{{ image_prefix }}swift-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net.kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux'] %}

RUN yum -y install \
        openstack-swift-container \
    && yum clean all

    {% endif %}
{% endif %}

COPY start.sh /

CMD ["/start.sh"]

{{ include_footer }}
