FROM {{ namespace }}/{{ image_prefix }}venus-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block venus_manager_header %}{% endblock %}

RUN chmod 644 /usr/local/bin/kolla_venus_extend_start

{% block venus_manager_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER venus
