FROM {{ namespace }}/{{ image_prefix }}hacluster-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block hacluster_pacemaker_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% set hacluster_pacemaker_packages = ['pacemaker'] %}
{% if base_package_type == 'deb' %}
    {% set hacluster_pacemaker_packages = hacluster_pacemaker_packages + [
        'pacemaker-cli-utils'
    ] %}
{% endif %}

{{ macros.install_packages(hacluster_pacemaker_packages | customizable("packages")) }}

{{ macros.kolla_patch_sources() }}

{% block hacluster_pacemaker_footer %}{% endblock %}
