FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block collectd_header %}{% endblock %}
{% import "macros.j2" as macros with context %}
{% set collectd_packages = [
    'collectd'
] %}

{{ macros.install_packages(collectd_packages | customizable("packages")) }}
COPY collectd_sudoers /etc/sudoers.d/kolla_collectd_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN useradd -r -m collectd \
    && chmod 755 /usr/local/bin/kolla_extend_start \
    && chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/kolla_collectd_sudoers \
    && usermod -a -G kolla collectd \
    && chown -R collectd /var/lib/collectd \
    && chown -R collectd /etc/collectd* \
    && chown -R collectd /var/run/

{% block collectd_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER collectd
