FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block solum_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='solum') }}

ADD solum-base-archive /solum-base-source

{% set solum_base_pip_packages = [
    '/solum'
] %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN ln -s solum-base-source/* solum \
    && {{ macros.install_pip(solum_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/solum \
    && cp -r /solum/etc/solum/* /etc/solum/ \
    && touch /usr/local/bin/kolla_solum_extend_start \
    && chmod 644 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_solum_extend_start

{% block solum_base_footer %}{% endblock %}
