FROM {{ namespace }}/{{ image_prefix }}cloudkitty-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block cloudkitty_processor_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% endif %}

{% block cloudkitty_processor_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER cloudkitty
