FROM {{ namespace }}/{{ image_prefix }}keystone-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block keystone_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

COPY keystone_bootstrap.sh /usr/local/bin/kolla_keystone_bootstrap
COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_keystone_bootstrap

{% if install_type == 'source' %}
ADD plugins-archive /

{% set keystone_plugins_pip_packages = [
    '/plugins/*'
] %}

RUN if [ "$(ls /plugins)" ]; then \
        {{ macros.install_pip(keystone_plugins_pip_packages | customizable("pip_packages")) }}; \
    fi

{% endif %}

{% block keystone_footer %}{% endblock %}
{% block footer %}{% endblock %}
