FROM {{ namespace }}/{{ image_prefix }}solum-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block solum_deployer_header %}{% endblock %}

{% block solum_deployer_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER solum
