FROM {{ namespace }}/{{ image_prefix }}solum-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block solum_deployer_header %}{% endblock %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% endif %}

{% block solum_deployer_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER solum
