FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        haproxy \
    && yum clean all

{% elif base_distro == 'ubuntu' %}

RUN apt-get install -y --no-install-recommends -t trusty-backports haproxy \
    && apt-get clean

{% elif base_distro == 'debian' %}

RUN apt-get install -y --no-install-recommends haproxy \
    && apt-get clean

{% endif %}

COPY ensure_latest_config.sh /opt/kolla/

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start /opt/kolla/ensure_latest_config.sh

{{ include_footer }}
