FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        haproxy \
    && yum clean all

{% elif base_distro == 'ubuntu' %}

RUN apt-get install -y --no-install-recommends -t trusty-backports haproxy \
    && apt-get clean

{% elif base_distro == 'debian' %}

RUN apt-get install -y --no-install-recommends haproxy \
    && apt-get clean

{% endif %}

COPY start.sh /
COPY ensure_latest_config.sh /opt/kolla/

CMD ["/start.sh"]

{{ include_footer }}
