FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        haproxy \
    && yum clean all

{% elif base_distro in ['debian', 'ubuntu'] %}

RUN apt-get -y install --no-install-recommends \
        haproxy \
    && apt-get clean

{% endif %}

RUN usermod -a -G kolla haproxy \
    && mkdir -p /var/lib/kolla/haproxy \
    && chown -R haproxy: /var/lib /run

COPY ensure_latest_config.sh /usr/local/bin/kolla_ensure_haproxy_latest_config
RUN chmod 755 /usr/local/bin/kolla_ensure_haproxy_latest_config

{{ include_footer }}
