FROM {{ namespace }}/{{ image_prefix }}designate-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block designate_central_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_package_type == 'rpm' %}
       {% set designate_central_packages = ['openstack-designate-central'] %}
    {% elif base_package_type == 'deb'%}
       {% set designate_central_packages = ['designate-central'] %}
    {% endif %}
{{ macros.install_packages(designate_central_packages | customizable("packages")) }}
{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_designate_extend_start
RUN chmod 755 /usr/local/bin/kolla_designate_extend_start

{% block designate_central_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER designate
