FROM {{ namespace }}/{{ image_prefix }}designate-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block designate_central_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}
       {% set designate_central_packages = ['openstack-designate-central'] %}
    {% elif base_distro in ['ubuntu']%}
       {% set designate_central_packages = ['designate-central'] %}
    {% endif %}
{{ macros.install_packages(designate_central_packages | customizable("packages")) }}
{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block designate_central_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER designate
