FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-openstack-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}


RUN yum -y install \
        openstack-glance \
        python-oslo-i18n \
    && yum clean all

    {% elif base_distro in ['ubuntu', 'debian'] %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

    {% endif %}
{% elif install_type == 'source' %}

ADD glance-base-archive /glance-base-source
RUN ln -s glance-base-source/* glance \
    && useradd --user-group glance \
    && pip --no-cache-dir install /glance \
    && mkdir -p /etc/glance /var/log/glance /home/glance \
    && cp -r /glance/etc/* /etc/glance/ \
    && chown -R glance: /etc/glance /var/log/glance /home/glance

{% endif %}
