FROM {{ namespace }}/{{ image_prefix }}designate-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block designate_producer_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_package_type == 'rpm' %}
       {% set designate_producer_packages = ['openstack-designate-producer'] %}
    {% elif base_package_type == 'deb' %}
       {% set designate_producer_packages = ['designate-producer'] %}
    {% endif %}
{{ macros.install_packages(designate_producer_packages | customizable("packages")) }}
{% endif %}

{% block designate_producer_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER designate
