FROM {{ namespace }}/{{ image_prefix }}swift-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block swift_object_expirer_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% block swift_object_expirer_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER swift
