FROM {{ namespace }}/{{ image_prefix }}swift-object-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net.kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        openstack-swift-proxy \
        openstack-swift-container \
    && yum clean all

    {% endif %}
{% endif %}

{{ include_footer }}
