FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if install_type == 'binary' %}
     {% if base_distro in ['ubuntu', 'debian'] %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
  && /bin/false

    {% endif %}
{% elif install_type == 'source' %}

ADD ./ceilometer.tar /
RUN ln -s /ceilometer-* /ceilometer

RUN cd /ceilometer \
    && useradd --user-group ceilometer \
    && pip install -r requirements.txt \
    && pip install /ceilometer \
    && mkdir /etc/ceilometer /var/log/ceilometer \
    && cp -r /ceilometer/etc/* /etc/ceilometer/ \
    && rm -rf /root/.cache

{% endif %}
