FROM {{ namespace }}/{{ image_prefix }}glance-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block glance_registry_header %}{% endblock %}

{% block glance_registry_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER glance
