FROM {{ namespace }}/{{ image_prefix }}rsyslog-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block rsyslog_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
    {% set rsyslog_packages = [
        'rsyslog-elasticsearch',
        'rsyslog-gnutls',
        'rsyslog-mmjsonparse',
        'rsyslog-mmnormalize'
    ] %}
{% elif base_distro in ['debian', 'ubuntu'] %}
    {% set rsyslog_packages = [
        'rsyslog-gnutls'
    ] %}
{% endif %}

{{ macros.install_packages(rsyslog_packages | customizable("packages")) }}

{% block rsyslog_footer %}{% endblock %}
{% block footer %}{% endblock %}
