FROM {{ namespace }}/{{ infra_image_prefix }}rsyslog-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block rsyslog_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'rpm' %}
    {% set rsyslog_packages = [
        'rsyslog-elasticsearch',
        'rsyslog-gnutls',
        'rsyslog-mmjsonparse',
        'rsyslog-mmnormalize'
    ] %}
{% elif base_package_type == 'deb' %}
    {% set rsyslog_packages = [
        'rsyslog-gnutls'
    ] %}
{% endif %}

{{ macros.install_packages(rsyslog_packages | customizable("packages")) }}

{% block rsyslog_footer %}{% endblock %}
{% block footer %}{% endblock %}
