FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block qinling_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='qinling') }}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

ADD qinling-base-archive /qinling-base-source

{% set qinling_base_pip_packages = [
    '/qinling'
] %}

RUN ln -s qinling-base-source/* qinling \
    && {{ macros.install_pip(qinling_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/qinling \
    && cp -r /qinling/etc/policy.json.sample /etc/qinling/policy.json \
    && chown -R qinling: /etc/qinling

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN touch /usr/local/bin/kolla_qinling_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_qinling_extend_start

{% block qinling_base_footer %}{% endblock %}
