FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block qinling_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='qinling') }}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

    {% if base_package_type == 'rpm' %}

        {% set qinling_base_packages = [
        ] %}

    {% elif base_package_type == 'deb' %}

        {% set qinling_base_packages = [
        ] %}

    {% endif %}

{{ macros.install_packages(qinling_base_packages | customizable("packages")) }}
RUN mkdir -p /var/www/cgi-bin/qinling

ADD qinling-base-archive /qinling-base-source

{% set qinling_base_pip_packages = [
    '/qinling'
] %}

RUN ln -s qinling-base-source/* qinling \
    && {{ macros.install_pip(qinling_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/qinling /var/www/cgi-bin/qinling \
    && cp -r /qinling/etc/policy.json.sample /etc/qinling/policy.json \
    && cp /qinling/qinling/api/wsgi.py /var/www/cgi-bin/qinling \
    && chown -R qinling: /etc/qinling /var/www/cgi-bin/qinling

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN touch /usr/local/bin/kolla_qinling_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_qinling_extend_start \
    && chmod 755 /var/www/cgi-bin/qinling

{% block qinling_base_footer %}{% endblock %}
