FROM {{ namespace }}/{{ image_prefix }}nova-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block nova_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}

        {% set nova_api_packages = [
            'openstack-nova-api',
            'httpd',
            'mod_wsgi'
        ] %}

    {% elif base_distro in ['ubuntu'] %}

        {% set nova_api_packages = [
            'nova-api',
            'python-memcache',
            'apache2',
            'libapache2-mod-wsgi'
        ] %}

    {% endif %}
{{ macros.install_packages(nova_api_packages | customizable("packages")) }}

{% elif install_type == 'source' %}

    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}

        {% set nova_api_packages = [
            'httpd',
            'mod_wsgi'
        ] %}

    {% elif base_distro in ['ubuntu'] %}

        {% set nova_api_packages = [
            'apache2',
            'libapache2-mod-wsgi'
        ] %}

    {% endif %}

{{ macros.install_packages(nova_api_packages | customizable("packages")) }}

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_nova_extend_start
RUN chmod 755 /usr/local/bin/kolla_nova_extend_start

{% block nova_api_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER nova
