FROM {{ namespace }}/{{ image_prefix }}cloudkitty-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"
{% endblock %}

{% block cloudkitty_processor_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.kolla_enable_base_repos() }}

{% set cloudkitty_processor_packages = [
] %}

{{ macros.install_packages(cloudkitty_processor_packages | customizable("packages")) }}

{{ macros.kolla_patch_sources() }}

{% block cloudkitty_processor_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ macros.kolla_cleanup_repos() }}

USER cloudkitty
