FROM {{ namespace }}/{{ image_prefix }}openvswitch-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block ovn_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'rpm' %}
    {% set ovn_base_packages = [
        'ovn${KOLLA_RPM_OVN_VERSION}',
    ] %}

{% elif base_package_type == 'deb' %}
    {% set ovn_base_packages = [
        'ovn-common',
    ] %}

{% endif %}
{{ macros.install_packages(ovn_base_packages | customizable("packages")) }}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN chmod 644 /usr/local/bin/kolla_extend_start

{{ macros.kolla_patch_sources() }}

{% block ovn_base_footer %}{% endblock %}
