FROM {{ namespace }}/{{ image_prefix }}ceph-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block ceph_rgw_header %}{% endblock %}

{% block ceph_rgw_footer %}{% endblock %}
{% block footer %}{% endblock %}
