FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux'] %}

RUN curl -L https://trunk.rdoproject.org/centos7/current/delorean.repo -o /etc/yum.repos.d/delorean.repo \
    && yum install -y openstack-magnum-common \
    && yum clean all

    {% endif %}
{% elif install_type == 'source' %}

ADD magnum-base-archive /magnum-base-source
RUN ln -s magnum-base-source/* magnum \
    && useradd --user-group magnum \
    && /var/lib/kolla/venv/bin/pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt /magnum \
    && mkdir -p /etc/magnum /home/magnum \
    && cp -r /magnum/etc/magnum/* /etc/magnum \
    && chown -R magnum: /etc/magnum /home/magnum

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN usermod -a -G kolla magnum \
    && touch /usr/local/bin/kolla_magnum_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_magnum_extend_start
