FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos'] %}

RUN curl -L https://copr.fedoraproject.org/coprs/sdake/openstack-magnum/repo/epel-7/sdake-openstack-magnum-epel-7.repo -o /etc/yum.repos.d/sdake-openstack-magnum-epel-7.repo \
    && rpm --import https://copr-be.cloud.fedoraproject.org/results/sdake/openstack-magnum/pubkey.gpg \
    && yum install -y openstack-magnum-common \
    && yum clean all

    {% elif base_distro in ['fedora'] %}

RUN curl -L https://copr.fedoraproject.org/coprs/sdake/openstack-magnum/repo/fedora-22/sdake-openstack-magnum-fedora-22.repo -o /etc/yum.repos.d/sdake-openstack-magnum-f22.repo \
    && rpm --import https://copr-be.cloud.fedoraproject.org/results/sdake/openstack-magnum/pubkey.gpg \
    && yum install -y openstack-magnum-common \
    && yum clean all

     {% elif base_distro in ['oraclelinux'] %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

    {% endif %}
{% elif install_type == 'source' %}

ADD magnum-base-archive /magnum-base-source
RUN ln -s magnum-base-source/* magnum \
    && useradd --user-group magnum \
    && /var/lib/kolla/venv/bin/pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt /magnum \
    && mkdir -p /etc/magnum /var/log/magnum /home/magnum \
    && cp -r /magnum/etc/magnum/* /etc/magnum \
    && chown -R magnum: /etc/magnum /var/log/magnum /home/magnum

{% endif %}

RUN usermod -a -G kolla magnum
