FROM {{ namespace }}/{{ image_prefix }}heat-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block heat_api_cloudwatch_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set heat_api_cloudwatch_packages = ['openstack-heat-api-cloudwatch'] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set heat_api_cloudwatch_packages = ['heat-api-cloudwatch'] %}
    {% endif %}
{{ macros.install_packages(heat_api_cloudwatch_packages | customizable("packages")) }}
{% endif %}

{% block heat_api_cloudwatch_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER heat
