FROM {{ namespace }}/{{ image_prefix }}aodh-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block aodh_notifier_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_package_type == 'rpm' %}
       {% set aodh_notifier_packages = ['openstack-aodh-notifier'] %}
    {% elif base_package_type == 'deb' %}
        {% set aodh_notifier_packages = ['aodh-notifier'] %}
    {% endif %}
{{ macros.install_packages(aodh_notifier_packages | customizable("packages")) }}

{% endif %}
{% block aodh_notifier_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER aodh
