FROM {{ namespace }}/{{ image_prefix }}aodh-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block aodh_notifier_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
       {% set aodh_notifier_packages = ['openstack-aodh-notifier'] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set aodh_notifier_packages = ['aodh-notifier'] %}
    {% endif %}
{{ macros.install_packages(aodh_notifier_packages | customizable("packages")) }}

{% endif %}
{% block aodh_notifier_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER aodh
