FROM {{ namespace }}/{{ image_prefix }}octavia-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block octavia_worker_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_package_type == 'rpm' %}
        {% set octavia_worker_packages = [
            'openstack-octavia-worker'
        ] %}
    {% elif base_package_type == 'deb' %}
RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
            && /bin/false
    {% endif %}

{{ macros.install_packages(octavia_worker_packages | customizable("packages")) }}

{% endif %}

{% block octavia_worker_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER octavia
