FROM {{ namespace }}/{{ image_prefix }}trove-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block trove_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}
       {% set trove_api_packages = ['openstack-trove-api'] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set trove_api_packages = ['trove-api'] %}
    {% endif %}

{{ macros.install_packages(trove_api_packages | customizable("packages")) }}

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block trove_api_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER trove
