FROM {{ namespace }}/{{ image_prefix }}trove-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block trove_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_package_type == 'rpm' %}
       {% set trove_api_packages = ['openstack-trove-api'] %}
    {% elif base_package_type == 'deb' %}
        {% set trove_api_packages = ['trove-api'] %}
    {% endif %}

{{ macros.install_packages(trove_api_packages | customizable("packages")) }}

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_trove_extend_start
RUN chmod 755 /usr/local/bin/kolla_trove_extend_start

{% block trove_api_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER trove
