FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['fedora', 'centos', 'oraclelinux'] %}

RUN yum -y install openstack-zaqar && yum clean all

    {% elif base_distro in ['ubuntu', 'debian'] %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

    {% endif %}
{% elif install_type == 'source' %}

ADD zaqar.tar /
RUN ln -s /zaqar-* zaqar \
    && useradd --user-group zaqar \
    && pip --no-cache-dir install /zaqar \
    && mkdir -p /etc/zaqar /var/log/zaqar /home/zaqar \
    && cp -r /zaqar/etc/* /etc/zaqar/ \
    && chown -R zaqar: /etc/zaqar /var/log/zaqar /home/zaqar

{% endif %}

COPY start.sh /
COPY config-external.sh /opt/kolla/

CMD ["/start.sh"]
