FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['fedora', 'centos', 'oraclelinux'] %}

RUN yum -y install openstack-zaqar && yum clean all

    {% elif base_distro in ['ubuntu', 'debian'] %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

ADD ./zaqar.tar /
RUN ln -s /zaqar-* /zaqar

RUN cd /zaqar \
    && useradd --user-group zaqar \
    && pip install -r requirements.txt \
    && pip install /zaqar \
    && mkdir /etc/zaqar /var/log/zaqar \
    && cp -r /zaqar/etc/* /etc/zaqar/ \
    && rm -rf /root/.cache

{% endif %}

COPY ./start.sh /start.sh

COPY config-external.sh /opt/kolla/

CMD ["/start.sh"]
