FROM {{ namespace }}/{{ image_prefix }}manila-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block manila_share_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{# NOTE(mnasiadka): glusterfs-fuse missing in CentOS 10 Stream - temporarily from Kolla COPR #}
{{ macros.enable_extra_repos(['ceph', 'epel', 'kolla_el10']) }}

{% if base_package_type == 'rpm' %}
    {% set manila_share_packages = [
        'ceph-common',
        'sqlite',
    ] %}
{% elif base_package_type == 'deb' %}
    {% set manila_share_packages = [
        'ceph-common',
        'glusterfs-client',
        'python3-cephfs',
        'python3-rados',
        'python3-rbd',
        'sqlite3'
    ] %}

{% endif %}

{{ macros.install_packages(manila_share_packages | customizable("packages")) }}

{{ macros.kolla_patch_sources() }}

{% block manila_share_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER manila
