FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net.kolla)

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum install -y \
        openvswitch \
        supervisor \
    && yum clean all

COPY supervisord.conf /etc/

{% elif base_distro in ['ubuntu', 'debian'] %}

RUN apt-get install -y --no-install-recommends supervisor \
    && apt-get clean

COPY supervisord.conf /etc/supervisor/

{% endif %}

# TODO: SamYaple FWaaS is part of the l3-agent, not a seperate agent that is
# why this file is needed. To support FWaaS we cannot have a seperate container
# I need to figure out the best way to make this work together
#
# This file _does_ _not_ need to exist, you must remove referencing it from the
# exec line in the start script. Also all these config options can exist in the
# main neutron.conf if we wish
COPY fwaas_driver.ini /etc/neutron/

COPY neutron-dhcp-agent/ /opt/kolla/neutron-dhcp-agent
COPY neutron-l3-agent/ /opt/kolla/neutron-l3-agent
COPY neutron-metadata-agent/ /opt/kolla/neutron-metadata-agent

COPY start.sh /

CMD ["/start.sh"]

{{ include_footer }}
