FROM {{ namespace }}/{{ image_prefix }}prometheus-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block prometheus_msteams_header %}{% endblock %}

{% block prometheus_msteams_repository_version %}
ARG prometheus_msteams_version=1.5.2
ARG prometheus_msteams_sha256sum=0f4df9ee31e655d1ec876ea2c53ab5ae5b07143ef21b9190e61b4d52839e135c
ARG prometheus_msteams_url=https://github.com/prometheus-msteams/prometheus-msteams/releases/download/v${prometheus_msteams_version}/prometheus-msteams-linux-{{debian_arch}}
{% endblock %}

{% block prometheus_msteams_install %}
RUN curl -o /tmp/prometheus-msteams ${prometheus_msteams_url} \
    && echo "${prometheus_msteams_sha256sum} /tmp/prometheus-msteams" | sha256sum -c \
    && mv /tmp/prometheus-msteams /opt \
    && chmod 0755 /opt/prometheus-msteams \
    && mkdir -p /etc/msteams
{% endblock %}

{% block prometheus_msteams_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER prometheus
