FROM {{ namespace }}/{{ image_prefix }}prometheus-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block prometheus_msteams_header %}{% endblock %}

{% block prometheus_msteams_install %}
ADD prometheus-msteams-archive /prometheus-msteams-source

RUN cp /prometheus-msteams-source /opt/prometheus-msteams \
    && chmod 0755 /opt/prometheus-msteams \
    && mkdir -p /etc/msteams
{% endblock %}

{% block prometheus_msteams_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER prometheus
