FROM {{ namespace }}/{{ image_prefix }}ceilometer-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"
{% endblock %}

{% block ceilometer_ipmi_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.kolla_enable_base_repos() }}

{% if base_package_type == 'rpm' %}
    {% set ceilometer_ipmi_packages = [
        'ipmitool'
    ] %}
{% elif base_package_type == 'deb' %}
    {% set ceilometer_ipmi_packages = [
        'ipmitool'
    ] %}
{% endif %}

{{ macros.install_packages(ceilometer_ipmi_packages | customizable("packages")) }}

{{ macros.kolla_patch_sources() }}

{% block ceilometer_ipmi_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ macros.kolla_cleanup_repos() }}

USER ceilometer
