FROM {{ namespace }}/{{ image_prefix }}watcher-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block watcher_applier_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.kolla_patch_sources() }}

{% block watcher_applier_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER watcher
