FROM {{ namespace }}/{{ image_prefix }}watcher-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block watcher_applier_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set watcher_applier_packages = ['openstack-watcher-applier'] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set watcher_applier_packages = ['watcher-applier'] %}
    {% endif %}
{{ macros.install_packages(watcher_applier_packages | customizable("packages")) }}
{% endif %}

{% block watcher_applier_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER watcher
