FROM {{ namespace }}/{{ image_prefix }}mariadb-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block mariadb_clustercheck_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
COPY socat_wrapper.sh /usr/local/bin/socat_wrapper

RUN chmod 644 /usr/local/bin/kolla_extend_start && \
    chmod 755 /usr/local/bin/socat_wrapper

{{ macros.kolla_patch_sources() }}

{% block mariadb_clustercheck_footer %}{% endblock %}
{% block footer %}{% endblock %}
