FROM {{ namespace }}/{{ image_prefix }}gnocchi-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block gnocchi_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
       {% set gnocchi_api_packages = [
            'openstack-gnocchi-api',
            'openstack-gnocchi-indexer-sqlalchemy'
        ] %}
    {% elif base_distro in ['debian', 'ubuntu'] %}
        {% set gnocchi_api_packages = ['gnocchi-api'] %}
    {% endif %}
{{ macros.install_packages(gnocchi_api_packages | customizable("packages")) }}

    {% if base_distro in ['debian', 'ubuntu'] %}
RUN rm -rf /etc/apache2/sites-enabled/gnocchi-api.conf
    {% endif %}
{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_gnocchi_extend_start
RUN chmod 755 /usr/local/bin/kolla_gnocchi_extend_start

{% block gnocchi_api_footer %}{% endblock %}
{% block footer %}{% endblock %}
