FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-ovs-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

COPY start.sh /
COPY ovs_ensure_configured.sh config-external.sh /opt/kolla/

CMD ["/start.sh"]
