FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block neutron_mlnx_agent_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.enable_extra_repos(['libvirt']) }}

{% set neutron_mlnx_agent_packages = [
    'python3-libvirt',
    'python3-ethtool',
] %}

{{ macros.install_packages(neutron_mlnx_agent_packages | customizable("packages")) }}

{% set neutron_mlnx_agent_pip_packages = [
    'networking-mlnx',
] %}

RUN {{ macros.install_pip(neutron_mlnx_agent_pip_packages | customizable("pip_packages")) }}

{% block neutron_mlnx_agent_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
