FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-ovs-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

COPY start.sh /
COPY config-external.sh /opt/kolla/

CMD ["/start.sh"]

{{ include_footer }}
