FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block monasca_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='monasca') }}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

    {% if base_package_type == 'rpm' %}
        {% set monasca_base_packages = [
            'httpd',
            'mod_ssl',
        ] %}
        {% if distro_python_version.startswith('3') %}
        {% set monasca_base_packages = monasca_base_packages + ['python3-mod_wsgi'] %}
        {% else %}
        {% set monasca_base_packages = monasca_base_packages + ['mod_wsgi'] %}
        {% endif %}

{{ macros.install_packages(monasca_base_packages | customizable("packages")) }}
RUN sed -i -r 's,^(Listen 80),#\1,' /etc/httpd/conf/httpd.conf \
    && sed -i -r 's,^(Listen 443),#\1,' /etc/httpd/conf.d/ssl.conf
    {% elif base_package_type == 'deb' %}

        {% set monasca_base_packages = [
            'apache2',
            'libapache2-mod-wsgi',
            'librdkafka-dev'
        ] %}

{{ macros.install_packages(monasca_base_packages | customizable("packages")) }}
RUN truncate -s 0 /etc/apache2/ports.conf

    {% endif %}

{% block monasca_source_install %}

{% set monasca_base_pip_packages = [
] %}

RUN {{ macros.install_pip(monasca_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/monasca \
    && chown -R monasca: /etc/monasca
{% endblock %}

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN touch /usr/local/bin/kolla_monasca_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_monasca_extend_start

{% block monasca_base_footer %}{% endblock %}
