FROM {{ namespace }}/{{ image_prefix }}zaqar-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block zaqar_wsgi_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

COPY extend_start.sh /usr/local/bin/kolla_zaqar_extend_start
RUN chmod 755 /usr/local/bin/kolla_zaqar_extend_start

{% block zaqar_wsgi_footer %}{% endblock %}
{% block footer %}{% endblock %}
