FROM {{ namespace }}/{{ image_prefix }}swift-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block swift_object_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}
        {% set swift_object_packages = ['openstack-swift-object'] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set swift_object_packages = ['swift-object'] %}
    {% endif %}

{{ macros.install_packages(swift_object_packages | customizable("packages")) }}

{% endif %}

{% block swift_object_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER swift
