FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block tacker_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='tacker') }}

{% if install_type == 'binary' %}

    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set tacker_base_packages = [
            'openstack-tacker-common'
        ] %}

    {% elif base_distro in ['debian', 'ubuntu'] %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

    {% endif %}

{{ macros.install_packages(tacker_base_packages | customizable("packages")) }}

{% elif install_type == 'source' %}

ADD tacker-base-archive /tacker-base-source

{% set tacker_base_pip_packages = [
    '/tacker'
] %}

RUN ln -s tacker-base-source/* tacker \
    && {{ macros.install_pip(tacker_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/tacker \
    && cp -r /tacker/etc/tacker/* /etc/tacker \
    && chown -R tacker: /etc/tacker

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN touch /usr/local/bin/kolla_tacker_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_tacker_extend_start

{% block tacker_base_footer %}{% endblock %}
