FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block tacker_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.enable_extra_repos(['openvswitch']) }}
{{ macros.configure_user(name='tacker') }}

ADD tacker-base-archive /tacker-base-source
ADD plugins-archive /

{% set tacker_base_pip_packages = [
    '/tacker'
] %}

{% set tacker_base_plugins_pip_packages = [
    '/plugins/*'
] %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN ln -s tacker-base-source/* tacker \
    && {{ macros.install_pip(tacker_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/tacker \
    && cp -r /tacker/etc/tacker/* /etc/tacker \
    && if [ "$(ls /plugins)" ]; then \
        {{ macros.install_pip(tacker_base_plugins_pip_packages) }}; \
       fi \
    && touch /usr/local/bin/kolla_tacker_extend_start \
    && chmod 644 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_tacker_extend_start

{% block tacker_base_footer %}{% endblock %}
