FROM {{ namespace }}/{{ image_prefix}}openstack-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block congress_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='congress') }}

{% if install_type == 'binary' %}
    {% if base_package_type == 'deb' %}
        {% set congress_base_packages = [
            'congress-common',
            'congress-server']
         %}
    {% elif base_package_type == 'rpm' %}
        {% set congress_base_packages = [
            'openstack-congress']
        %}
    {% endif %}

{{ macros.install_packages(congress_base_packages | customizable("packages")) }}

{% elif install_type == 'source' %}

{% set congress_base_pip_packages = [
    '/congress'
] %}

ADD congress-base-archive /congress-base-source
RUN ln -s congress-base-source/* congress \
    && {{ macros.install_pip(congress_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/congress \
    && cp -r /congress/etc/* /etc/congress/ \
    && chown -R congress: /etc/congress

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN touch /usr/local/bin/kolla_congress_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_congress_extend_start

{% block congress_base_footer %}{% endblock %}
