FROM {{ namespace }}/{{ image_prefix }}cinder-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block cinder_scheduler_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.kolla_patch_sources() }}

{% block cinder_scheduler_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER cinder
