FROM {{ namespace }}/{{ image_prefix }}cinder-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block cinder_scheduler_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['ubuntu'] %}

        {% set cinder_scheduler_packages = [
                'cinder-scheduler'
        ] %}

{{ macros.install_packages(cinder_scheduler_packages | customizable("packages")) }}

    {% endif %}
{% endif %}

{% block cinder_scheduler_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER cinder
