FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if install_type == 'binary' %}
     {% if base_distro in ['ubuntu', 'debian'] %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
  && /bin/false

    {% endif %}
{% elif install_type == 'source' %}

ADD ceilometer-base.tar /
RUN ln -s /ceilometer-* ceilometer \
    && useradd --user-group ceilometer \
    && pip --no-cache-dir install /ceilometer \
    && mkdir -p /etc/ceilometer /var/log/ceilometer /home/ceilometer \
    && cp -r /ceilometer/etc/* /etc/ceilometer/ \
    && chown -R ceilometer: /etc/ceilometer /var/log/ceilometer /home/ceilometer

{% endif %}
