FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        openstack-ceilometer-common \
        python-tooz \
        python-oslo-db \
    && yum clean all

    {% elif base_distro in ['ubuntu'] %}

RUN apt-get -y install --no-install-recommends \
        ceilometer-common \
    && apt-get clean

    {% endif %}

{% elif install_type == 'source' %}

ADD ceilometer-base-archive /ceilometer-base-source
RUN ln -s ceilometer-base-source/* ceilometer \
    && useradd --user-group ceilometer \
    && /var/lib/kolla/venv/bin/pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt /ceilometer pymongo \
    && mkdir -p /etc/ceilometer /var/log/ceilometer /home/ceilometer \
    && cp -r /ceilometer/etc/ceilometer/* /etc/ceilometer/ \
    && chown -R ceilometer: /etc/ceilometer /var/log/ceilometer /home/ceilometer \
    && sed -i 's|^exec_dirs.*|exec_dirs=/var/lib/kolla/venv/bin,/sbin,/usr/sbin,/bin,/usr/bin,/usr/local/bin,/usr/local/sbin|g' /etc/ceilometer/rootwrap.conf

COPY ceilometer_sudoers /etc/sudoers.d/ceilometer_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/ceilometer_sudoers \
    && touch /usr/local/bin/kolla_ceilometer_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_ceilometer_extend_start

{% endif %}

RUN usermod -a -G kolla ceilometer
