FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-openstack-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if install_type == 'source' %}

ADD ceilometer-base-archive /ceilometer-base-source
RUN ln -s ceilometer-base-source/* ceilometer \
    && useradd --user-group ceilometer \
    && pip --no-cache-dir install /ceilometer \
    && mkdir -p /etc/ceilometer /var/log/ceilometer /home/ceilometer \
    && cp -r /ceilometer/etc/* /etc/ceilometer/ \
    && chown -R ceilometer: /etc/ceilometer /var/log/ceilometer /home/ceilometer

{% endif %}
