FROM {{ namespace }}/{{ image_prefix }}ironic-conductor:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

USER root

{% block ironic_prometheus_exporter_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'rpm' %}

    {% set ironic_prometheus_exporter_packages = [
        'httpd',
        'mod_ssl',
    ] %}

{{ macros.install_packages(ironic_prometheus_exporter_packages | customizable("packages")) }}
RUN sed -i -r 's,^(Listen 80),#\1,' /etc/httpd/conf/httpd.conf \
    && sed -i -r 's,^(Listen 443),#\1,' /etc/httpd/conf.d/ssl.conf

{% elif base_package_type == 'deb' %}
    {% set ironic_prometheus_exporter_packages = [
        'apache2',
    ] %}

{{ macros.install_packages(ironic_prometheus_exporter_packages | customizable("packages")) }}
RUN echo > /etc/apache2/ports.conf

{% endif %}

ENV IRONIC_CONFIG /etc/ironic/ironic.conf

{{ macros.kolla_patch_sources() }}

{% block ironic_prometheus_exporter_footer %}{% endblock %}
{% block footer %}{% endblock %}
