FROM {{ namespace }}/{{ image_prefix }}octavia-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block octavia_housekeeping_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_package_type == 'rpm' %}
        {% set octavia_housekeeping_packages = [
            'openstack-octavia-housekeeping'
        ] %}
    {% elif base_package_type == 'deb' %}
        {% set octavia_housekeeping_packages = [
            'octavia-housekeeping'
        ] %}
    {% endif %}

{{ macros.install_packages(octavia_housekeeping_packages | customizable("packages")) }}

{% endif %}

{% block octavia_housekeeping_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER octavia
