FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block iscsid_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}
    {% set iscsid_packages = [
        'iscsi-initiator-utils',
        'targetcli',
        'python-rtslib'
    ] %}

{% elif base_distro in ['ubuntu', 'debian'] %}
    {% set iscsid_packages = [
        'open-iscsi',
        'targetcli',
        'python-rtslib'
    ] %}

{% endif %}

{{ macros.install_packages(iscsid_packages | customizable("packages"))  }}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start \
    && rm /etc/iscsi/initiatorname.iscsi

{% block iscsid_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}
