FROM {{ namespace }}/{{ image_prefix }}ceilometer-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block ceilometer_notification_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set ceilometer_notification_packages = ['openstack-ceilometer-notification'] %}
    {% elif base_distro in ['debian', 'ubuntu'] %}
        {% set ceilometer_notification_packages = ['ceilometer-agent-notification'] %}
    {% endif %}

{{ macros.install_packages(ceilometer_notification_packages | customizable("packages")) }}

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_ceilometer_extend_start
RUN chmod 755 /usr/local/bin/kolla_ceilometer_extend_start

{% block ceilometer_notification_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER ceilometer
