FROM {{ namespace }}/{{ image_prefix }}ironic-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}
    {% set ironic_pxe_packages = [
        'tftp-server',
        'syslinux-tftpboot'
    ] %}
{% elif base_distro in ['ubuntu', 'debian'] %}
    {% set ironic_pxe_packages = [
        'tftpd-hpa',
        'syslinux-common',
        'syslinux'
    ] %}
{% endif %}

{{ macros.install_packages(ironic_pxe_packages | customizable("packages")) }}

COPY tftp-map-file /map-file
COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block ironic_pxe_footer %}{% endblock %}
{{ include_footer }}
