FROM {{ namespace }}/{{ image_prefix }}cinder-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block cinder_backup_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set cinder_backup_packages = [
                'nfs-utils'
        ] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set cinder_backup_packages = [
                'nfs-common',
                'cinder-backup'
        ] %}
    {% endif %}

{% elif install_type == 'source' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set cinder_backup_packages = [
                'nfs-utils'
        ] %}
     {% elif base_distro in ['ubuntu', 'debian'] %}
        {% set cinder_backup_packages = [
                'nfs-common'
        ] %}
    {% endif %}

{% endif %}

{{ macros.install_packages(cinder_backup_packages | customizable("packages")) }}

{% block cinder_backup_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER cinder
