FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block cinder_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='cinder') }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set cinder_base_packages = [
                'openstack-cinder',
                'python-automaton',
                'lvm2',
                'ceph-common'
        ] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set cinder_base_packages = [
                'cinder-common',
                'ceph-common',
                'lvm2'
        ] %}
    {% endif %}
{{ macros.install_packages(cinder_base_packages | customizable("packages")) }}

{% elif install_type == 'source' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set cinder_base_packages = [
                'lvm2',
                'qemu-img',
                'ceph-common'
        ] %}
     {% elif base_distro in ['ubuntu', 'debian'] %}
        {% set cinder_base_packages = [
                'lvm2',
                'qemu-utils',
                'ceph-common'
        ] %}
    {% endif %}
{{ macros.install_packages(cinder_base_packages | customizable("packages")) }}

ADD cinder-base-archive /cinder-base-source
RUN ln -s cinder-base-source/* cinder \
    && /var/lib/kolla/venv/bin/pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt /cinder \
    && mkdir -p /etc/cinder \
    && cp -r /cinder/etc/cinder/* /etc/cinder/ \
    && chown -R cinder: /etc/cinder \
    && sed -i 's|^exec_dirs.*|exec_dirs=/var/lib/kolla/venv/bin,/sbin,/usr/sbin,/bin,/usr/bin,/usr/local/bin,/usr/local/sbin|g' /etc/cinder/rootwrap.conf

{% endif %}

COPY cinder_sudoers /etc/sudoers.d/kolla_cinder_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/kolla_cinder_sudoers \
    && touch /usr/local/bin/kolla_cinder_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_cinder_extend_start

{% block cinder_base_footer %}{% endblock %}
