FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install openstack-cinder \
    python-automaton \
    lvm2 \
    ceph-common \
  && yum clean all \
  && mkdir -p /etc/ceph \
  && sed -i "s|udev_rules = 1|udev_rules = 0|g" /etc/lvm/lvm.conf \
  && sed -i "s|udev_sync = 1|udev_sync = 0|g" /etc/lvm/lvm.conf

# NOTE(sdake): The sed operations make LVM tools work inside a container - see
# https://groups.google.com/forum/#!topic/docker-user/n4Xtvsb4RAw

    {% endif %}
{% elif install_type == 'source' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install lvm2 \
   && yum clean all

     {% elif base_distro in ['ubuntu', 'debian'] %}

RUN apt-get install -y --no-install-recommends \
        lvm2 \
        ceph-common \
    && apt-get clean \
    && mkdir -p /etc/ceph

    {% endif %}

ADD cinder-base-archive /cinder-base-source
RUN ln -s cinder-base-source/* cinder \
    && useradd --user-group cinder \
    && pip --no-cache-dir install -c requirements/upper-constraints.txt /cinder \
    && mkdir -p /etc/cinder /var/log/cinder /home/cinder \
    && cp -r /cinder/etc/cinder/* /etc/cinder/ \
    && chown -R cinder: /etc/cinder /var/log/cinder /home/cinder \
    && sed -i "s|udev_rules = 1|udev_rules = 0|g" /etc/lvm/lvm.conf \
    && sed -i "s|udev_sync = 1|udev_sync = 0|g" /etc/lvm/lvm.conf

# NOTE(sdake): The sed operations make LVM tools work inside a container - see
# https://groups.google.com/forum/#!topic/docker-user/n4Xtvsb4RAw

{% endif %}
