FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block cinder_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='cinder') }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set cinder_base_packages = [
                'ceph-common',
                'lvm2',
                'cryptsetup',
                'openstack-cinder',
                'python-automaton',
                'python-oslo-vmware'
        ] %}
    {% elif base_distro in ['debian', 'ubuntu'] %}
        {% set cinder_base_packages = [
                'ceph-common',
                'cinder-common',
                'lvm2',
                'cryptsetup',
                'python-oslo.vmware'
        ] %}
    {% endif %}
{{ macros.install_packages(cinder_base_packages | customizable("packages")) }}

{% elif install_type == 'source' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set cinder_base_packages = [
                'ceph-common',
                'lvm2',
                'cryptsetup',
        ] %}
        {% if base_distro in ['centos', 'oraclelinux'] %}
            {% set cinder_base_packages = cinder_base_packages + [
                'qemu-img-ev'
            ] %}
        {% else %}
            {% set cinder_base_packages = cinder_base_packages + [
                 'qemu-img'
            ] %}
        {% endif %}
    {% elif base_distro in ['debian', 'ubuntu'] %}
        {% set cinder_base_packages = [
                'ceph-common',
                'lvm2',
                'cryptsetup',
                'qemu-utils'
        ] %}
    {% endif %}
{{ macros.install_packages(cinder_base_packages | customizable("packages")) }}

{% set cinder_base_pip_packages = [
    '/cinder'
] %}

ADD cinder-base-archive /cinder-base-source
RUN ln -s cinder-base-source/* cinder \
    && {{ macros.install_pip(cinder_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/cinder \
    && cp -r /cinder/etc/cinder/* /etc/cinder/ \
    && chown -R cinder: /etc/cinder \
    && sed -i 's|^exec_dirs.*|exec_dirs=/var/lib/kolla/venv/bin,/sbin,/usr/sbin,/bin,/usr/bin,/usr/local/bin,/usr/local/sbin|g' /etc/cinder/rootwrap.conf

{% endif %}

COPY cinder_sudoers /etc/sudoers.d/kolla_cinder_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/kolla_cinder_sudoers \
    && touch /usr/local/bin/kolla_cinder_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_cinder_extend_start

{% block cinder_base_footer %}{% endblock %}
