FROM {{ namespace }}/{{ infra_image_prefix }}base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block chrony_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='chrony') }}

{% set chrony_packages = ['chrony'] %}

{{ macros.install_packages(chrony_packages | customizable("packages")) }}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block chrony_footer %}{% endblock %}
{% block footer %}{% endblock %}
