FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block chrony_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='chrony') }}

{% set chrony_packages = ['chrony'] %}

{{ macros.install_packages(chrony_packages | customizable("packages")) }}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block chrony_footer %}{% endblock %}
{% block footer %}{% endblock %}
