---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  when: inventory_hostname in groups['compute'] or
        inventory_hostname in groups['storage']
  with_items:
    - "iscsid"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  when: inventory_hostname in groups['compute'] or
        inventory_hostname in groups['storage']
  with_items:
    - "iscsid"

- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  when: inventory_hostname in groups['tgtd']
  with_items:
    - "tgtd"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  when: inventory_hostname in groups['tgtd']
  with_items:
    - "tgtd"
