FROM {{ namespace }}/{{ image_prefix }}senlin-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block senlin_conductor_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% block senlin_conductor_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER senlin
