FROM {{ namespace }}/{{ image_prefix }}senlin-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block senlin_conductor_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_package_type == 'rpm' %}
        {% set senlin_conductor_packages = ['openstack-senlin-conductor'] %}

    {% elif base_package_type == 'deb' %}
        {% set senlin_conductor_packages = ['senlin-conductor'] %}
    {% endif %}

{{ macros.install_packages(senlin_conductor_packages | customizable("packages")) }}

{% endif %}

{% block senlin_conductor_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER senlin
