FROM {{ namespace }}/{{ base_distro }}-{{ install_type  }}-cinder-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

RUN mkdir -p /opt/data
VOLUME [ "/opt/data" ]

# Command needed to start the data container.
# Note: data containers do not need to be persistent.
CMD ["/bin/true"]
