FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block sahara_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}
    {% set sahara_base_packages = ['openstack-sahara-common'] %}
{% elif base_distro in ['ubuntu'] %}
    {% set sahara_base_packages = ['sahara-common'] %}
{% endif %}
{{ macros.install_packages(sahara_base_packages | customizable("packages")) }}

{% elif install_type == 'source' %}

ADD sahara-base-archive /sahara-base-source
RUN ln -s sahara-base-source/* sahara \
    && useradd --user-group sahara \
    && /var/lib/kolla/venv/bin/pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt /sahara \
    && mkdir -p /etc/sahara /var/log/sahara /home/sahara \
    && cp -r /sahara/etc/sahara/* /etc/sahara/ \
    && chown -R sahara: /etc/sahara /var/log/sahara /home/sahara \
    && sed -i 's|^exec_dirs.*|exec_dirs=/var/lib/kolla/venv/bin,/sbin,/usr/sbin,/bin,/usr/bin,/usr/local/bin,/usr/local/sbin|g' /etc/sahara/rootwrap.conf

{% endif %}

RUN usermod -a -G kolla sahara

COPY sahara_sudoers /etc/sudoers.d/kolla_sahara_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN usermod -a -G kolla sahara \
    && chmod 750 /etc/sudoers.d \
    && chmod 640 /etc/sudoers.d/kolla_sahara_sudoers \
    && touch /usr/local/bin/kolla_sahara_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_sahara_extend_start

{% block sahara_base_footer %}{% endblock %}
