FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block sahara_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='sahara') }}

{% if base_package_type == 'rpm' %}
    {% set sahara_base_packages = ['openssh'] %}
{% elif base_package_type == 'deb' %}
    {% set sahara_base_packages = ['openssh-client'] %}
{% endif %}
{{ macros.install_packages(sahara_base_packages | customizable("packages")) }}

ADD sahara-base-archive /sahara-base-source
ADD plugins-archive /

{% set sahara_base_pip_packages = [
    '/sahara'
] %}
{% set sahara_base_plugins_pip_packages = [
    '/plugins/*',
] %}

COPY sahara_sudoers /etc/sudoers.d/kolla_sahara_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN ln -s sahara-base-source/* sahara \
    && {{ macros.install_pip(sahara_base_pip_packages | customizable("pip_packages")) }} \
    && if [ "$(ls /plugins)" ]; then \
        {{ macros.install_pip(sahara_base_plugins_pip_packages) }}; \
    fi \
    && mkdir -p /etc/sahara \
    && cp -r /sahara/etc/sahara/* /etc/sahara/ \
    && sed -i 's|^exec_dirs.*|exec_dirs=/var/lib/kolla/venv/bin,/sbin,/usr/sbin,/bin,/usr/bin,/usr/local/bin,/usr/local/sbin|g' /etc/sahara/rootwrap.conf \
    && chmod 750 /etc/sudoers.d \
    && chmod 640 /etc/sudoers.d/kolla_sahara_sudoers \
    && touch /usr/local/bin/kolla_sahara_extend_start \
    && chmod 644 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_sahara_extend_start

{% block sahara_base_footer %}{% endblock %}
