FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block horizon_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='horizon') }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set horizon_packages = [
                'gettext',
                'httpd',
                'mod_ssl',
                'mod_wsgi',
                'openstack-cloudkitty-ui',
                'openstack-dashboard',
                'openstack-designate-ui',
                'openstack-heat-ui',
                'openstack-ironic-ui',
                'openstack-magnum-ui',
                'openstack-manila-ui',
                'openstack-mistral-ui',
                'openstack-murano-ui',
                'openstack-neutron-lbaas-ui',
                'openstack-octavia-ui',
                'openstack-sahara-ui',
                'openstack-trove-ui',
                'openstack-vitrage-ui'
        ] %}

{{ macros.install_packages(horizon_packages | customizable("packages")) }}

{% block horizon_redhat_binary_setup %}
RUN sed -i -r 's,^(Listen 80),#\1,' /etc/httpd/conf/httpd.conf \
    && sed -i -r 's,^(Listen 443),#\1,' /etc/httpd/conf.d/ssl.conf \
    && ln -s /usr/share/openstack-dashboard/openstack_dashboard /usr/lib/python2.7/site-packages/openstack_dashboard \
    && ln -s /usr/share/openstack-dashboard/static /usr/lib/python2.7/site-packages/static \
    && chown -R horizon: /etc/openstack-dashboard /usr/share/openstack-dashboard \
    && chown -R apache: /usr/share/openstack-dashboard/static \
    && sed -i "s|WEBROOT = '/dashboard/'|WEBROOT = '/'|" /etc/openstack-dashboard/local_settings \
    && cp /usr/share/openstack-dashboard/manage.py /usr/bin/manage.py \
    && rm -f /usr/share/openstack-dashboard/openstack_dashboard/local/enabled/?[^_]*.py* \
    && rm -f /usr/lib/python2.7/site-packages/openstack_dashboard/local/enabled/?[^_]*.py* \
    && for locale in /usr/lib/python2.7/site-packages/*/locale; do \
           (cd ${locale%/*} && /usr/bin/python /usr/bin/manage.py compilemessages) \
       done
{% endblock %}

    {% elif base_distro in ['debian', 'ubuntu'] %}
        {% set horizon_packages = [
                'apache2',
                'gettext',
                'libapache2-mod-wsgi',
                'locales',
                'openstack-dashboard',
                'python-designate-dashboard',
                'python-heat-dashboard',
                'python-manila-ui',
                'python-murano-dashboard',
                'python-neutron-lbaas-dashboard',
                'python-sahara-dashboard',
                'python-trove-dashboard',
                'tzdata'
        ] %}

{{ macros.install_packages(horizon_packages | customizable("packages")) }}

{% block horizon_ubuntu_binary_setup %}
RUN echo > /etc/apache2/ports.conf \
    && sed -i 's|\(ServerTokens \)OS|\1Prod|' /etc/apache2/conf-available/security.conf \
    && ln -s ../mods-available/headers.load  /etc/apache2/mods-enabled/headers.load \
    && ln -s ../mods-available/expires.load  /etc/apache2/mods-enabled/expires.load \
    && cp /usr/share/openstack-dashboard/openstack_dashboard/conf/*.json /etc/openstack-dashboard \
    && cp /usr/share/openstack-dashboard/manage.py /usr/bin/manage.py \
    && rm /etc/apache2/conf-enabled/openstack-dashboard.conf \
    && rm /etc/openstack-dashboard/local_settings.py \
    && ln -s /etc/openstack-dashboard/local_settings /etc/openstack-dashboard/local_settings.py \
    && for locale in /usr/lib/python2.7/site-packages/*/locale; do \
           (cd ${locale%/*} && /usr/bin/python /usr/bin/manage.py compilemessages) \
       done
{% endblock %}

    {% endif %}
{% elif install_type == 'source' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}

        {% set horizon_packages = [
                'gettext',
                'httpd',
                'mod_ssl',
                'mod_wsgi'
        ] %}

{{ macros.install_packages(horizon_packages | customizable("packages")) }}

{% block horizon_redhat_source_setup %}
RUN sed -i -r 's,^(Listen 80),#\1,' /etc/httpd/conf/httpd.conf \
    && sed -i -r 's,^(Listen 443),#\1,' /etc/httpd/conf.d/ssl.conf
{% endblock %}

    {% elif base_distro in ['debian', 'ubuntu'] %}

        {% set horizon_packages = [
                'apache2',
                'gettext',
                'libapache2-mod-wsgi',
                'locales',
                'tzdata'
        ] %}

{{ macros.install_packages(horizon_packages | customizable("packages")) }}

{% block horizon_ubuntu_source_setup %}
RUN echo > /etc/apache2/ports.conf \
    && ln -s ../mods-available/headers.load  /etc/apache2/mods-enabled/headers.load
{% endblock %}

    {% endif %}

ADD horizon-archive /horizon-source
ADD plugins-archive /

{% set horizon_pip_packages = [
    '/horizon'
] %}

{% set horizon_plugins_pip_packages = [
    '/plugins/*'
] %}

# NOTE(hrw): to install horizon from unpacked sources we cannot have it in upper-constraints.txt
RUN ln -s horizon-source/* horizon \
    && sed -i /^horizon=/d /requirements/upper-constraints.txt \
    && {{ macros.install_pip(horizon_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/openstack-dashboard \
    && cp -r /horizon/openstack_dashboard/conf/* /etc/openstack-dashboard/ \
    && cp /horizon/openstack_dashboard/local/local_settings.py.example /etc/openstack-dashboard/local_settings \
    && cp /horizon/manage.py /var/lib/kolla/venv/bin/manage.py \
    && if [ "$(ls /plugins)" ]; then \
           {{ macros.install_pip(horizon_plugins_pip_packages) }}; \
       fi \
    && for locale in  /var/lib/kolla/venv/lib/python2.7/site-packages/*/locale; do \
           (cd ${locale%/*} && /var/lib/kolla/venv/bin/python /var/lib/kolla/venv/bin/manage.py compilemessages) \
       done \
    && chown -R horizon: /etc/openstack-dashboard /var/lib/kolla/venv/lib/python2.7/site-packages/static

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block horizon_footer %}{% endblock %}
{% block footer %}{% endblock %}
