FROM {{ namespace }}/{{ image_prefix }}designate-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block designate_worker_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

# The bind9 package here is only to provide the rndc binary.
{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
       {% set designate_worker_packages = [
            'bind',
            'openstack-designate-worker'
        ] %}
    {% elif base_distro in ['ubuntu'] %}
       {% set designate_worker_packages = [
            'bind9',
            'designate-worker'
        ] %}
    {% endif %}
{% elif install_type == 'source' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
       {% set designate_worker_packages = [
            'bind'
        ] %}
    {% elif base_distro in ['ubuntu'] %}
       {% set designate_worker_packages = [
            'bind9'
        ] %}
    {% endif %}
{% endif %}
{{ macros.install_packages(designate_worker_packages | customizable("packages")) }}

{% block designate_worker_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER designate
