FROM {{ namespace }}/{{ image_prefix }}barbican-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block barbican_keystone_listener_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.kolla_patch_sources() }}

{% block barbican_keystone_listener_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER barbican
