FROM {{ namespace }}/{{ image_prefix }}nova-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block nova_ssh_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='nova', shell='/bin/bash') }}

{% set nova_ssh_packages = [
    'openssh-server'
] %}

{% if base_package_type == 'rpm' %}

# NOTE(mgoddard): The centos:8 image contains a /run/nologin file, which
# prevents SSH access to it.
RUN rm -f /run/nologin

{% elif base_package_type == 'deb' %}

RUN mkdir -p /var/run/sshd \
    && chmod 0755 /var/run/sshd

{% endif %}

{{ macros.install_packages(nova_ssh_packages | customizable("packages")) }}

RUN sed -ri 's/session(\s+)required(\s+)pam_loginuid.so/session\1optional\2pam_loginuid.so/' /etc/pam.d/sshd

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block nova_ssh_footer %}{% endblock %}
{% block footer %}{% endblock %}
