FROM {{ namespace }}/{{ image_prefix }}nova-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block nova_ssh_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% set nova_ssh_packages = [
    'openssh-server'
] %}

{% if base_distro in ['ubuntu', 'debian'] %}

RUN mkdir -p /var/run/sshd \
    && chmod 0755 /var/run/sshd

{% endif %}

{{ macros.install_packages(nova_ssh_packages | customizable("packages")) }}

RUN chsh -s /bin/bash nova

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block nova_ssh_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}
