FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block tempest_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['fedora', 'centos', 'oraclelinux', 'rhel'] %}
        {% set tempest_packages = ['openstack-tempest'] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set tempest_packages = ['tempest'] %}
    {% endif %}

{{ macros.install_packages(tempest_packages | customizable("packages")) }}

{% elif install_type == 'source' %}

ADD tempest-archive /tempest-source
# NOTE(Jeffrey4l): remove the tempest version constraint in the
# upper-constrains.txt file. Otherwise, it will be failed.
RUN ln -s tempest-source/* tempest \
    && sed -i 's/^tempest===.*$//' requirements/upper-constraints.txt \
    && /var/lib/kolla/venv/bin/pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt /tempest \
    && mkdir -p /etc/tempest /var/log/tempest /etc/tempest/tempest_lock

WORKDIR /tempest

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block tempest_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}
