FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['ubuntu', 'debian'] %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

    {% endif %}
{% elif install_type == 'source' %}

ADD ./gnocchi.tar /
RUN ln -s /gnocchi-* /gnocchi

RUN cd /gnocchi \
    && useradd --user-group gnocchi \
    && pip install -r requirements.txt \
    && pip install /gnocchi \
    && mkdir /etc/gnocchi /var/log/gnocchi \
    && cp -r /gnocchi/etc/* /etc/gnocchi/ \
    && rm -rf /root/.cache

{% endif %}
