FROM {{ namespace }}/{{ image_prefix }}skydive-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block skydive_agent_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% block skydive_agent_install %}
{% if base_package_type == 'rpm' %}
    {% set skydive_agent_packages = [
        'openvswitch',
        'skydive-agent'
    ] %}
{% elif base_package_type == 'deb' %}
    {% set skydive_agent_packages = ['openvswitch-common'] %}
{% endif %}
{{ macros.install_packages(skydive_agent_packages | customizable("packages")) }}
{% endblock %}

{% block skydive_agent_footer %}{% endblock %}
{% block footer %}{% endblock %}
