FROM {{ namespace }}/{{ image_prefix }}kube-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

ENV KUBERNETES_COMPONENT=kube-controller-manager

{% block kube_controller_manager_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'rpm' %}
   {% set ceph_support_packages = [
        'ceph-common'
    ] %}
{% elif base_package_type == 'deb' %}
   {% set ceph_support_packages = [
        'ceph-common'
    ] %}
{% endif %}
{{ macros.install_packages(ceph_support_packages | customizable("packages")) }}

{% block kube_controller_manager_install %}
RUN true \
    && curl -L ${KUBERNETES_DOWNLOAD_ROOT}/${KUBERNETES_COMPONENT} -o /usr/bin/${KUBERNETES_COMPONENT} \
    && chmod +x /usr/bin/${KUBERNETES_COMPONENT}
{% endblock %}

# Clear any customisation by Kolla to entrypoint & command
ENTRYPOINT []
CMD []

{% block kube_controller_manager_footer %}{% endblock %}
{% block footer %}{% endblock %}
