FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block hacluster_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type =='rpm' %}

{{ macros.enable_extra_repos(['hacluster']) }}

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN chmod 644 /usr/local/bin/kolla_extend_start

{{ macros.kolla_patch_sources() }}

{% block hacluster_base_footer %}{% endblock %}
