FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

RUN useradd -r -m --user-group kibana \
    && usermod -a -G kolla kibana

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        kibana \
    && yum clean all

{% elif base_distro in ['ubuntu', 'debian'] %}

RUN apt-get install -y --no-install-recommends \
        kibana \
    && apt-get clean

{% endif %}

{{ include_footer }}

USER kibana
