FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block kibana_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN useradd -r -m --user-group kibana \
    && usermod -a -G kolla kibana \
    && chmod 755 /usr/local/bin/kolla_extend_start

{% set kibana_packages = ['kibana'] %}
{{ macros.install_packages(kibana_packages | customizable("packages")) }}

{% block kibana_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER kibana
