FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block haproxy_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='haproxy') }}

{% set haproxy_packages = [
    'haproxy'
] %}
{{ macros.install_packages(haproxy_packages | customizable("packages")) }}

COPY ensure_latest_config.sh /usr/local/bin/kolla_ensure_haproxy_latest_config

RUN mkdir -p /var/lib/kolla/haproxy \
    && chown -R haproxy: /var/lib /run \
    && chmod 755 /usr/local/bin/kolla_ensure_haproxy_latest_config

{{ macros.kolla_patch_sources() }}

{% block haproxy_footer %}{% endblock %}
{% block footer %}{% endblock %}
