FROM {{ namespace }}/{{ image_prefix }}solum-base:{{ tag }}
LABEL maintainer="{{ maintainer }}"

{% block solum_worker_header %}{% endblock %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% endif %}

{% block solum_worker_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER solum
