FROM {{ namespace }}/{{ image_prefix }}cinder-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block cinder_rpcbind_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

        {% set cinder_rpcbind_packages = [
                'nfs-utils',
                'nfs-utils-lib'
        ] %}

{% elif base_distro in ['ubuntu', 'debian'] %}

        {% set cinder_rpcbind_packages = [
                'rpcbind'
        ] %}

{% endif %}

{{ macros.install_packages(cinder_rpcbind_packages | customizable("packages")) }}

{% block cinder_rpcbind_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER cinder
