FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if base_distro in ['fedora', 'centos', 'oraclelinux'] %}

RUN yum -y install memcached \
    && yum clean all

{% elif base_distro in ['ubuntu', 'debian'] %}

RUN apt-get install -y --no-install-recommends memcached \
    && apt-get clean

{% endif %}

COPY start.sh /
COPY config-external.sh /opt/kolla/

CMD ["/start.sh"]
