FROM {{ namespace }}/{{ image_prefix }}neutron-server:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block neutron_server_ovn %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% block neutron_server_ovn_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
