FROM {{ namespace }}/{{ image_prefix }}swift-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install openstack-swift-account \
    && yum clean all

    {% endif %}
{% endif %}

{{ include_footer }}
