FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block dnsmasq_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% set dnsmasq_packages = ['dnsmasq'] %}
{{ macros.install_packages(dnsmasq_packages| customizable("packages")) }}

{% block dnsmasq_footer %}{% endblock %}
{% block footer %}{% endblock %}
