FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block freezer_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='freezer') }}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}
    {% set freezer_base_packages = [
        'trickle'
    ] %}
{{ macros.install_packages(freezer_base_packages | customizable("packages")) }}

ADD freezer-base-archive /freezer-base-source

{% set freezer_base_pip_packages = [
    '/freezer'
] %}

RUN ln -s freezer-base-source/* freezer \
    && mkdir -p /etc/freezer \
    && chown -R freezer: /etc/freezer \
    && {{ macros.install_pip(freezer_base_pip_packages | customizable("pip_packages")) }} \
    && cp -r /freezer/etc/* /etc/freezer

{% endif %}

COPY freezer_sudoers /etc/sudoers.d/kolla_freezer_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN chmod 750 /etc/sudoers.d \
    && chmod 640 /etc/sudoers.d/kolla_freezer_sudoers \
    && touch /usr/local/bin/kolla_freezer_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_freezer_extend_start

{% block freezer_base_footer %}{% endblock %}
