FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block blazar_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='blazar') }}

ADD blazar-base-archive /blazar-base-source

{% set blazar_base_pip_packages = [
    '/blazar'
] %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN ln -s blazar-base-source/* blazar \
    && {{ macros.install_pip(blazar_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/blazar \
    && cp -r /blazar/etc/blazar/* /etc/blazar \
    && touch /usr/local/bin/kolla_blazar_extend_start \
    && chmod 644 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_blazar_extend_start

{{ macros.kolla_patch_sources() }}

{% block blazar_base_footer %}{% endblock %}
