FROM {{ namespace }}/{{ image_prefix }}nova-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block nova_conductor_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}

        {% set nova_conductor_packages = [
            'openstack-nova-conductor'
        ] %}

    {% elif base_distro in ['ubuntu'] %}

        {% set nova_conductor_packages = [
            'nova-conductor'
        ] %}

    {% endif %}

{{ macros.install_packages(nova_conductor_packages | customizable("packages")) }}

{% endif %}

{% block nova_conductor_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER nova
