FROM {{ namespace }}/{{ image_prefix }}nova-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block nova_conductor_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_package_type == 'rpm' %}

        {% set nova_conductor_packages = [
            'openstack-nova-conductor'
        ] %}

    {% elif base_package_type == 'deb' %}

        {% set nova_conductor_packages = [
            'nova-conductor'
        ] %}

    {% endif %}

{{ macros.install_packages(nova_conductor_packages | customizable("packages")) }}

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_nova_extend_start
RUN chmod 755 /usr/local/bin/kolla_nova_extend_start

{% block nova_conductor_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER nova
