FROM {{ namespace }}/{{ image_prefix }}nova-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block nova_placement_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_package_type == 'rpm' %}

        {% set nova_placement_api_packages = [
            'httpd',
            'mod_ssl',
            'openstack-nova-placement-api'
        ] %}
        {% if distro_python_version.startswith('3') %}
        {% set nova_placement_api_packages = nova_placement_api_packages + ['python3-mod_wsgi'] %}
        {% else %}
        {% set nova_placement_api_packages = nova_placement_api_packages + ['mod_wsgi'] %}
        {% endif %}

{{ macros.install_packages(nova_placement_api_packages | customizable("packages")) }}
RUN sed -i -r 's,^(Listen 80),#\1,' /etc/httpd/conf/httpd.conf \
    && sed -i -r 's,^(Listen 443),#\1,' /etc/httpd/conf.d/ssl.conf

    {% elif base_package_type == 'deb' %}

        {% set nova_placement_api_packages = [
                'apache2',
                'libapache2-mod-wsgi-py3',
                'nova-placement-api'
        ] %}

{{ macros.install_packages(nova_placement_api_packages | customizable("packages")) }}
RUN truncate -s 0 /etc/apache2/ports.conf

    {% endif %}
{% elif install_type == 'source' %}
    {% if base_package_type == 'rpm' %}

        {% set nova_placement_api_packages = [
            'httpd',
            'mod_ssl',
        ] %}
        {% if distro_python_version.startswith('3') %}
        {% set nova_placement_api_packages = nova_placement_api_packages + ['python3-mod_wsgi'] %}
        {% else %}
        {% set nova_placement_api_packages = nova_placement_api_packages + ['mod_wsgi'] %}
        {% endif %}

{{ macros.install_packages(nova_placement_api_packages | customizable("packages")) }}
RUN sed -i -r 's,^(Listen 80),#\1,' /etc/httpd/conf/httpd.conf \
    && sed -i -r 's,^(Listen 443),#\1,' /etc/httpd/conf.d/ssl.conf
    {% elif base_package_type == 'deb' %}

        {% set nova_placement_api_packages = [
                'apache2',
                'libapache2-mod-wsgi'
        ] %}

{{ macros.install_packages(nova_placement_api_packages | customizable("packages")) }}
RUN truncate -s 0 /etc/apache2/ports.conf

    {% endif %}
{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_nova_extend_start
RUN chmod 755 /usr/local/bin/kolla_nova_extend_start

{% block nova_placement_api_footer %}{% endblock %}
{% block footer %}{% endblock %}
