FROM {{ namespace }}/{{ image_prefix }}heat-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block heat_api_cfn_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set heat_api_cfn_packages = ['openstack-heat-api-cfn'] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set heat_api_cfn_packages = ['heat-api-cfn'] %}
    {% endif %}
{{ macros.install_packages(heat_api_cfn_packages | customizable("packages")) }}
{% endif %}

{% block heat_api_cfn_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER heat
