FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-heat-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install openstack-heat-api-cfn \
    && yum clean all

    {% endif %}
{% endif %}

COPY start.sh /

CMD ["/start.sh"]

{{ include_footer }}
