FROM {{ namespace }}/{{ image_prefix }}venus-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block venus_api_header %}{% endblock %}

{% block venus_api_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER venus
