FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net.kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux'] %}

RUN yum -y install openstack-swift && yum clean all

   {% elif base_distro in ['ubuntu', 'debian'] %}

RUN echo '{{ install_type}} not yet available for {{ base_distro }}' \
    && /bin/false

    {% endif %}

{% elif install_type == 'source' %}

ADD swift.tar /
RUN ln -s /swift-* swift \
    && useradd --user-group swift \
    && pip --no-cache-dir install /swift \
    && mkdir -p /etc/swift /var/log/swift /home/swift \
    && cp -r /swift/etc/* /etc/swift/ \
    && chown -R swift: /etc/swift /var/log/swift /home/swift

{% endif %}

COPY config-swift.sh build-swift-ring.py /opt/kolla/
RUN mkdir /opt/swift
