FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block zun_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

ADD zun-base-archive /zun-base-source

{% set zun_base_pip_packages = [
    '/zun'
] %}

RUN ln -s zun-base-source/* zun \
    && useradd --user-group --create-home --home-dir /var/lib/zun zun \
    && {{ macros.install_pip(zun_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/zun \
    && cp -r /zun/etc/* /etc/zun/ \
    && chown -R zun: /etc/zun

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN usermod -a -G kolla zun \
    && touch /usr/local/bin/kolla_zun_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_zun_extend_start

{% block zun_base_footer %}{% endblock %}
