FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-neutron-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net.kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux'] %}

# Install required packages
RUN yum install -y openstack-neutron-openvswitch \
                   openvswitch \
    && yum clean all

    {% endif %}

{% elif install_type == 'source' %}

# Install required packages
RUN yum install -y \
        #TODO: will be addressed later
        https://rdoproject.org/repos/openstack-kilo/rdo-release-kilo.rpm \
        openvswitch \
    && yum clean all

{% endif %}

COPY start.sh /
COPY config-external.sh /opt/kolla/

CMD ["/start.sh"]
