FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block zookeeper_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='zookeeper') }}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
    {% set zookeeper_packages = [
        'zookeeper',
    ] %}
{% elif base_distro in ['ubuntu', 'debian'] %}
    {% set zookeeper_packages = [
        'zookeeper',
    ] %}
{% endif %}

{{ macros.install_packages(zookeeper_packages | customizable("packages")) }}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block zookeeper_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER zookeeper
