FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if base_distro in ['fedora', 'centos', 'oraclelinux'] %}

RUN yum -y install \
        hostname \
        rabbitmq-server \
    && yum clean all

{% elif base_distro in ['ubuntu', 'debian'] %}

RUN apt-get install -y --no-install-recommends \
        hostname \
        rabbitmq-server \
    && apt-get clean

{% endif %}

RUN /usr/lib/rabbitmq/bin/rabbitmq-plugins enable rabbitmq_management

COPY start.sh /
COPY config-rabbit.sh config-external.sh /opt/kolla/

CMD ["/start.sh"]
