FROM {{ namespace }}/{{ image_prefix }}searchlight-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block searchlight_listener_header %}{% endblock %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% endif %}

{% block searchlight_listener_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER searchlight
