FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block neutron_dhcp_agent_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'deb' %}
    {% if install_type == 'binary' %}
        {% set neutron_dhcp_agent_packages = [
            'neutron-dhcp-agent'
        ] %}
    {% endif %}
{% endif %}

{{ macros.install_packages(neutron_dhcp_agent_packages | customizable("packages")) }}

{% block neutron_dhcp_agent_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
