FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block ceph_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}
   {% set ceph_base_packages = [
        'ceph',
        'ceph-radosgw',
        'parted',
        'hdparm',
        'btrfs-progs',
        'xfsprogs',
        'e2fsprogs'
    ] %}
{% elif base_distro in ['ubuntu', 'debian'] %}
   {% set ceph_base_packages = [
        'ceph',
        'radosgw',
        'parted',
        'hdparm',
        'btrfs-tools',
        'xfsprogs',
        'e2fsprogs'
    ] %}
{% endif %}
{{ macros.install_packages(ceph_base_packages | customizable("packages")) }}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start \
    && usermod -a -G kolla ceph

{% block ceph_base_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}
