FROM {{ namespace }}/{{ image_prefix }}mistral-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        openstack-mistral-engine \
    && yum clean all

    {% endif %}
{% endif %}

{{ include_footer }}

USER mistral
