FROM {{ namespace }}/{{ image_prefix }}mistral-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block mistral_engine_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set mistral_engine_packages = ['openstack-mistral-engine'] %}
    {% elif base_distro in ['debian', 'ubuntu'] %}
        {% set mistral_engine_packages = ['mistral-engine'] %}
    {% endif %}
{{ macros.install_packages(mistral_engine_packages | customizable("packages")) }}

{% endif %}
{% block mistral_engine_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER mistral
