FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block dind_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}

# Since the gate cannot do DinD on centos due to the age of the kernel, we don't
# build a true DinD image. Should the time come that we get a newer kernel in
# the centos gate and we want to do multinode we can populate this container
RUN /bin/true

{% elif base_distro in ['ubuntu', 'debian'] %}
    {% set dind_packages = [
         'btrfs-tools',
         'docker-engine',
         'openssh-server'
    ] %}
{{ macros.install_packages(dind_packages | customizable("packages")) }}
RUN pip --no-cache-dir install --upgrade docker-py

{% endif %}

COPY start.sh /usr/local/bin/kolla_start
RUN chmod 755 /usr/local/bin/kolla_start

{% block dind_footer %}{% endblock %}
{% block footer %}{% endblock %}
