FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block dind_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'rpm' %}

# Since the gate cannot do DinD on centos due to the age of the kernel, we don't
# build a true DinD image. Should the time come that we get a newer kernel in
# the centos gate and we want to do multinode we can populate this container
RUN /bin/true

{% elif base_package_type == 'deb' %}
    {% set dind_packages = [
         'btrfs-progs',
         'openssh-server'
    ] %}

    {% if base_distro in ['debian'] %}
        {% set dind_packages = dind_packages + [
             'docker-ce'
        ] %}
    {% else %}
        {% set dind_packages = dind_packages + [
             'docker.io'
        ] %}
    {% endif %}

    {% if install_type == 'binary' %}
        {% set dind_packages = dind_packages + [
             'python-setuptools'
        ] %}
    {% endif %}
{{ macros.install_packages(dind_packages | customizable("packages")) }}

{% set dind_pip_packages = [
    'docker'
] %}

RUN {{ macros.install_pip(dind_pip_packages | customizable("pip_packages"), constraints = false) }}

{% endif %}

COPY start.sh /usr/local/bin/kolla_start
RUN chmod 755 /usr/local/bin/kolla_start

{% block dind_footer %}{% endblock %}
{% block footer %}{% endblock %}
