FROM {{ namespace }}/{{ image_prefix }}murano-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['ubuntu'] %}

RUN apt-get install -y --no-install-recommends \
        murano-engine \
    && apt-get clean

    {% endif %}
{% endif %}

{{ include_footer }}

USER murano
