FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block keepalived_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}
    {% set keepalived_packages = [
        'hostname',
        'keepalived',
        'socat'
    ] %}
{% elif base_distro in ['ubuntu', 'debian'] %}
    {% set keepalived_packages = [
        'keepalived',
        'socat'
    ] %}
{% endif %}
{{ macros.install_packages(keepalived_packages | customizable("packages")) }}

COPY check_alive.sh /

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start /check_alive.sh

{% block keepalived_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}
