FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['fedora', 'centos', 'oraclelinux'] %}

RUN yum -y install \
    python-oslo-reports \
    && yum clean all

    {% elif base_distro in ['ubuntu', 'debian'] %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

    {% endif %}
{% elif install_type == 'source' %}

ADD ./heat.tar /
RUN ln -s /heat-* /heat

RUN cd /heat \
    && useradd --user-group heat \
    && pip install -r requirements.txt \
    && pip install /heat \
    && mkdir /etc/heat /var/www/cgi-bin/heat \
    && cp -r /heat/etc/* /etc/heat/ \
    && cp -a httpd/heat.py /var/www/cgi-bin/heat/admin \
    && cp -a httpd/heat.py /var/www/cgi-bin/heat/main

{% endif %}
