FROM {{ namespace }}/{{ image_prefix }}kube-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

ENV KUBERNETES_COMPONENT=kube-proxy

{% block kube_proxy_header %}{% endblock %}

{% block kube_proxy_install %}
RUN true \
    && curl -L ${KUBERNETES_DOWNLOAD_ROOT}/${KUBERNETES_COMPONENT} -o /usr/bin/${KUBERNETES_COMPONENT} \
    && chmod +x /usr/bin/${KUBERNETES_COMPONENT}
{% endblock %}

# Clear any customisation by Kolla to entrypoint & command
ENTRYPOINT []
CMD []

{% block kube_proxy_footer %}{% endblock %}
{% block footer %}{% endblock %}
