#!/bin/sh

for image in glance-base glance-api glance-registry; do
(
	cd $image
	docker build -t docker.usersys.redhat.com/larsks/${image}:latest .
	docker push docker.usersys.redhat.com/larsks/${image}:latest
)
done

