FROM {{ namespace }}/{{ image_prefix }}ovn-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block ovn_controller_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
    {% set ovn_controller_packages = [
        'openvswitch-ovn-host'
    ] %}

{% elif base_distro in ['debian', 'ubuntu'] %}
    {% set ovn_controller_packages = [
        'ovn-host'
    ] %}

{% endif %}
{{ macros.install_packages(ovn_controller_packages | customizable("packages")) }}

{% block ovn_controller_footer %}{% endblock %}
{% block footer %}{% endblock %}
