FROM {{ namespace }}/{{ infra_image_prefix }}ovn-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block ovn_controller_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'rpm' %}
    {% set ovn_controller_packages = [
        'openvswitch-ovn-host'
    ] %}

{% elif base_package_type == 'deb' %}
    {% set ovn_controller_packages = [
        'ovn-host'
    ] %}

{% endif %}
{{ macros.install_packages(ovn_controller_packages | customizable("packages")) }}

{% block ovn_controller_footer %}{% endblock %}
{% block footer %}{% endblock %}
