FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block cloudkitty_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='cloudkitty') }}

{% if install_type == 'binary' %}
    {% if base_package_type == 'rpm' %}

        {% set cloudkitty_base_packages = [
                'openstack-cloudkitty-common',
        ] %}

    {% elif base_package_type == 'deb' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

    {% endif %}

{{ macros.install_packages(cloudkitty_base_packages | customizable("packages")) }}

{% elif install_type == 'source' %}

{% set cloudkitty_base_pip_packages = [
    '/cloudkitty'
] %}

ADD cloudkitty-base-archive /cloudkitty-base-source
RUN ln -s cloudkitty-base-source/* cloudkitty \
    && {{ macros.install_pip(cloudkitty_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/cloudkitty  \
    && cp -r /cloudkitty/etc/cloudkitty/* /etc/cloudkitty/ \
    && chown -R cloudkitty: /etc/cloudkitty

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN touch /usr/local/bin/kolla_cloudkitty_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_cloudkitty_extend_start

{% block cloudkitty_base_footer %}{% endblock %}
