FROM {{ namespace }}/{{ image_prefix }}senlin-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_senlin_extend_start
RUN chmod 755 /usr/local/bin/kolla_senlin_extend_start

{{ include_footer }}

USER senlin
