---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "cloudkitty-api"
    - "cloudkitty-processor"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "cloudkitty-api"
    - "cloudkitty-processor"

- name: Copying over cloudkitty.conf
  merge_configs:
    vars:
      service_name: "{{ item }}"
    sources:
      - "{{ role_path }}/templates/cloudkitty.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/database.conf"
      - "{{ node_custom_config }}/messaging.conf"
      - "{{ node_custom_config }}/cloudkitty.conf"
      - "{{ node_custom_config }}/cloudkitty/{{ item }}.conf"
      - "{{ node_custom_config }}/cloudkitty/{{ inventory_hostname }}/cloudkitty.conf"
    dest: "{{ node_config_directory }}/{{ item }}/cloudkitty.conf"
  with_items:
    - "cloudkitty-api"
    - "cloudkitty-processor"

- name: Check if policies shall be overwritten
  local_action: stat path="{{ node_custom_config }}/cloudkitty/policy.json"
  register: cloudkitty_policy

- name: Copying over existing policy.json
  template:
    src: "{{ node_custom_config }}/cloudkitty/policy.json"
    dest: "{{ node_config_directory }}/cloudkitty/policy.json"
  when:
    cloudkitty_policy.stat.exists
