FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block kafka_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='kafka', homedir='/opt/kafka') }}

{% if base_package_type == 'rpm' %}
    {% set kafka_packages = [
        'java-1.8.0-openjdk-headless',
    ] %}
{% elif base_package_type == 'deb' %}
    {% set kafka_packages = [
        'default-jre-headless',
    ] %}
{% endif %}

{{ macros.install_packages(kafka_packages | customizable("packages")) }}

{% block kafka_version %}
ENV kafka_version=2.1.0
ENV kafka_scala_version=2.12
ENV kafka_url=http://apache.osuosl.org/kafka/${kafka_version}/kafka_${kafka_scala_version}-${kafka_version}.tgz
ENV kafka_pkg_sha512sum=05a07e928c439b1084a6b3f6835f067f9636ac47f9473dcaaf7040d339cbd0a4561b7478531b237aa69e27f50fe3a2e7f4d0f2ba99a6422592a89ecf1187fa25
{% endblock %}

{% block kafka_install %}
RUN curl -sSL -o /tmp/kafka.tgz ${kafka_url} \
    && echo "${kafka_pkg_sha512sum} /tmp/kafka.tgz" | sha512sum -c \
    && tar --strip 1 -xvf /tmp/kafka.tgz -C /opt/kafka \
    && rm -f /tmp/kafka.tgz
{% endblock %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block kafka_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER kafka
