FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block kafka_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif base_distro in ['ubuntu', 'debian'] %}
    {% set kafka_packages = [
        'default-jre',
    ] %}
{% endif %}

{{ macros.install_packages(kafka_packages | customizable("packages")) }}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
ADD kafka-archive /
RUN ln -s kafka* kafka \
    && useradd --user-group --home-dir /kafka kafka \
    && chmod 755 /usr/local/bin/kolla_extend_start \
    && usermod -a -G kolla kafka \
    && chown -R kafka: /kafka

{% block kafka_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER kafka
