FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block zaqar_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='zaqar') }}

{% if install_type == 'binary' %}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
    {% set zaqar_packages = [
        'httpd',
        'mod_ssl',
        'mod_wsgi',
        'openstack-zaqar'
    ] %}
{{ macros.install_packages(zaqar_packages | customizable("packages")) }}
RUN sed -i -r 's,^(Listen 80),#\1,' /etc/httpd/conf/httpd.conf \
    && sed -i -r 's,^(Listen 443),#\1,' /etc/httpd/conf.d/ssl.conf
{% elif base_distro in ['debian', 'ubuntu'] %}
    {% set zaqar_packages = [
        'apache2',
        'libapache2-mod-wsgi',
        'zaqar-common',
        'zaqar-server'
    ] %}
{{ macros.install_packages(zaqar_packages | customizable("packages")) }}
RUN echo > /etc/apache2/ports.conf
{% endif %}

{% elif install_type == 'source' %}
{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}

    {% set zaqar_packages = [
        'httpd',
        'mod_ssl',
        'mod_wsgi'
    ] %}
{{ macros.install_packages(zaqar_packages | customizable("packages")) }}
RUN sed -i -r 's,^(Listen 80),#\1,' /etc/httpd/conf/httpd.conf \
    && sed -i -r 's,^(Listen 443),#\1,' /etc/httpd/conf.d/ssl.conf

{% elif base_distro in ['debian', 'ubuntu'] %}

    {% set zaqar_packages = [
        'apache2',
        'libapache2-mod-wsgi'
    ] %}

{{ macros.install_packages(zaqar_packages | customizable("packages")) }}
RUN echo > /etc/apache2/ports.conf
{% endif %}

ADD zaqar-archive /zaqar-source

{% set zaqar_pip_packages = [
    'pymongo',
    '/zaqar'
] %}

RUN ln -s zaqar-source/* zaqar \
    && {{ macros.install_pip(zaqar_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/zaqar \
    && cp -r /zaqar/etc/* /etc/zaqar/ \
    && chown -R zaqar: /etc/zaqar

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block zaqar_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER zaqar
