FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install openstack-zaqar \
    && yum clean all

    {% endif %}
{% elif install_type == 'source' %}

ADD zaqar-archive /zaqar-source
RUN ln -s zaqar-source/* zaqar \
    && useradd --user-group zaqar \
    && /var/lib/kolla/venv/bin/pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt /zaqar \
    && mkdir -p /etc/zaqar /var/log/zaqar /home/zaqar \
    && cp -r /zaqar/etc/* /etc/zaqar/ \
    && chown -R zaqar: /etc/zaqar /var/log/zaqar /home/zaqar

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start \
    && usermod -a -G kolla zaqar

{{ include_footer }}

USER zaqar
