FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block zaqar_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='zaqar') }}

{% if install_type == 'binary' %}

    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set zaqar_packages = ['openstack-zaqar'] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set zaqar_packages = [
            'zaqar-common',
            'zaqar-server'
        ] %}
    {% endif %}
{{ macros.install_packages(zaqar_packages | customizable("packages")) }}

{% elif install_type == 'source' %}
ADD zaqar-archive /zaqar-source
RUN ln -s zaqar-source/* zaqar \
    && /var/lib/kolla/venv/bin/pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt pymongo /zaqar \
    && mkdir -p /etc/zaqar \
    && cp -r /zaqar/etc/* /etc/zaqar/ \
    && mv /etc/zaqar/policy.json.sample /etc/zaqar/policy.json \
    && chown -R zaqar: /etc/zaqar

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block zaqar_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER zaqar
