---
- name: Pulling rsyncd image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ swift_rsyncd_image_full }}"
  when: inventory_hostname in groups['swift-account-server'] or
        inventory_hostname in groups['swift-container-server'] or
        inventory_hostname in groups['swift-object-server']

- name: Pulling swift-proxy-server image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ swift_proxy_server_image_full }}"
  when: inventory_hostname in groups['swift-proxy-server']

- name: Pulling swift-account image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ swift_account_image_full }}"
  when: inventory_hostname in groups['swift-account-server']

- name: Pulling swift-container image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ swift_container_image_full }}"
  when: inventory_hostname in groups['swift-container-server']

- name: Pulling swift-object image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ swift_object_image_full }}"
  when: inventory_hostname in groups['swift-object-server']
