FROM {{ namespace }}/{{ image_prefix }}prometheus-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block prometheus_openstack_exporter_header %}{% endblock %}

{% block prometheus_openstack_exporter_repository_version %}
ENV prometheus_openstack_exporter_version=0.0.7
{% endblock %}

{% block prometheus_openstack_exporter_install %}
RUN curl -sSL -o /tmp/prometheus_openstack_exporter.tar.gz https://github.com/Linaro/openstack-exporter/releases/download/v${prometheus_openstack_exporter_version}/openstack-exporter-${prometheus_openstack_exporter_version}.linux-{{debian_arch}}.tar.gz \
    && tar xvf /tmp/prometheus_openstack_exporter.tar.gz -C /opt/ \
    && rm -f /tmp/prometheus_openstack_exporter.tar.gz \
    && ln -s /opt/openstack-exporter* /opt/openstack-exporter
{% endblock %}

{% block prometheus_openstack_exporter_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER prometheus
