FROM {{ namespace }}/{{ image_prefix }}nova-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block nova_network_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

        {% set nova_network_packages = [
            'openstack-nova-network',
            'bridge-utils',
            'initscripts'
        ] %}

    {% elif base_distro in ['ubuntu'] %}

        {% set nova_network_packages = [
            'nova-network'
        ] %}

    {% endif %}
{% elif install_type == 'source' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

        {% set nova_network_packages = [
            'initscripts'
        ] %}

    {% endif %}

{{ macros.install_packages(nova_network_packages | customizable("packages")) }}

{% endif %}

{% block nova_network_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER nova
