FROM {{ namespace }}/{{ image_prefix }}trove-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        openstack-trove-guestagent \
  && yum clean all

    {% elif base_distro in ['ubuntu'] %}

RUN apt-get -y install --no-install-recommends \
        trove-guestagent \
    && apt-get clean

    {% endif %}
{% endif %}

{{ include_footer }}

USER trove
