FROM {{ namespace }}/{{ image_prefix }}trove-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block trove_guestagent_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
       {% set trove_guestagent_packages = ['openstack-trove-guestagent'] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set trove_guestagent_packages = ['trove-guestagent'] %}
    {% endif %}

{{ macros.install_packages(trove_guestagent_packages | customizable("packages")) }}

{% endif %}

{% block trove_guestagent_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER trove
