FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block venus_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='venus') }}

ADD venus-base-archive /venus-base-source

{% set venus_base_pip_packages = [
    '/venus'
] %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN ln -s venus-base-source/* venus \
    && {{ macros.install_pip(venus_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/venus \
    && cp -r /venus/etc/venus/* /etc/venus/ \
    && touch /usr/local/bin/kolla_venus_extend_start \
    && chmod 644 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_venus_extend_start

{% block venus_base_footer %}{% endblock %}
