FROM {{ namespace }}/{{ image_prefix }}skydive-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block skydive_analyzer_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% block skydive_analyzer_install %}
{# NOTE(mgoddard): CentOS 8 does not currently provide skydive packages #}
{% if base_package_type == 'rpm' and distro_package_manager == 'yum' %}
    {% set skydive_analyzer_packages = ['skydive-analyzer'] %}
{{ macros.install_packages(skydive_analyzer_packages | customizable("packages")) }}
{% endif %}
{% endblock %}

{% block skydive_analyzer_footer %}{% endblock %}

{% block footer %}{% endblock %}

USER skydive
