FROM {{ namespace }}/{{ image_prefix }}cyborg-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block cyborg_api_header %}{% endblock %}
{% import "macros.j2" as macros with context %}

{% set cyborg_api_packages = [
] %}
{{ macros.install_packages(cyborg_api_packages | customizable("packages")) }}

COPY extend_start.sh /usr/local/bin/kolla_cyborg_extend_start
RUN chmod 644 /usr/local/bin/kolla_cyborg_extend_start

{{ macros.kolla_patch_sources() }}

{% block cyborg_api_footer %}{% endblock %}
{% block footer %}{% endblock %}
