FROM {{ namespace }}/{{ image_prefix }}solum-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block solum_api_header %}{% endblock %}

COPY extend_start.sh /usr/local/bin/kolla_solum_extend_start
RUN chmod 644 /usr/local/bin/kolla_solum_extend_start

{% block solum_api_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER solum
