FROM {{ namespace }}/{{ image_prefix }}magnum-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block magnum_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_package_type == 'rpm' and base_distro != 'rhel' %}
       {% set magnum_api_packages = ['openstack-magnum-api'] %}
    {% elif base_package_type == 'rpm' and base_distro == 'rhel' %}
RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false
    {% elif base_package_type == 'deb' %}
       {% set magnum_api_packages = ['magnum-api'] %}
    {% endif %}
{{ macros.install_packages(magnum_api_packages | customizable("packages")) }}
{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_magnum_extend_start
RUN chmod 755 /usr/local/bin/kolla_magnum_extend_start

{% block magnum_api_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER magnum
