FROM {{ namespace }}/{{ image_prefix }}magnum-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install openstack-magnum-api \
    && yum clean all

    {% endif %}
{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_magnum_extend_start
RUN chmod 755 /usr/local/bin/kolla_magnum_extend_start

{{ include_footer }}

USER magnum
