FROM {{ namespace }}/{{ image_prefix }}swift-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block swift_rsyncd_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'rpm' %}
    {% set swift_rsyncd_packages = ['rsync'] %}
{% elif base_package_type == 'deb' %}
    {% set swift_rsyncd_packages = ['rsync'] %}
{% endif %}

{{ macros.install_packages(swift_rsyncd_packages | customizable("packages")) }}
COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block swift_rsyncd_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER swift
