FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

ADD murano.tar /
RUN ln -s /murano-* /murano

RUN cd /murano \
    && useradd --user-group murano \
    && pip install -r requirements.txt \
    && pip install --install-option="--install-scripts=/usr/bin" /murano \
    && mkdir -p /etc/murano /var/log/murano /home/murano \
    && cp -r /murano/etc/murano/* /etc/murano/ \
    && chown -R murano: /etc/murano /var/log/murano /home/murano \
    && rm -rf /root/.cache

{% endif %}
