FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

ADD ./murano.tar /
RUN ln -s /murano-* /murano

RUN cd /murano \
    && pip install -r requirements.txt \
    && pip install /murano \
    && mkdir /etc/murano \
    && cd /murano \
    && tox -e genconfig \
    && cp -r etc/murano/* /etc/murano/ \
    && rm -rf /root/.cache

{% endif %}
