FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block multipathd_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'rpm' %}
    {% set multipathd_packages = ['device-mapper-multipath'] %}
{% elif base_package_type == 'deb' %}
    {% set multipathd_packages = ['multipath-tools'] %}
{% endif %}

{{ macros.install_packages(multipathd_packages | customizable("packages")) }}

{% block multipathd_footer %}{% endblock %}
{% block footer %}{% endblock %}
