FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block multipathd_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
    {% set multipathd_packages = ['device-mapper-multipath'] %}
{% elif base_distro in ['ubuntu', 'debian'] %}
    {% set multipathd_packages = ['multipath-tools'] %}
{% endif %}

{{ macros.install_packages(multipathd_packages | customizable("packages")) }}

{% block multipathd_footer %}{% endblock %}
{% block footer %}{% endblock %}
