FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block multipathd_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
    {% set multipathd_packages = ['device-mapper-multipath'] %}
{% elif base_distro in ['debian', 'ubuntu'] %}
    {% set multipathd_packages = ['multipath-tools'] %}
{% endif %}

{{ macros.install_packages(multipathd_packages | customizable("packages")) }}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block multipathd_footer %}{% endblock %}
{% block footer %}{% endblock %}
