FROM {{ namespace }}/{{ image_prefix }}aodh-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block aodh_evaluator_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
       {% set aodh_evaluator_packages = ['openstack-aodh-evaluator'] %}
    {% elif base_distro in ['debian', 'ubuntu'] %}
        {% set aodh_evaluator_packages = ['aodh-evaluator'] %}
    {% endif %}
{{ macros.install_packages(aodh_evaluator_packages | customizable("packages")) }}

{% endif %}
{% block aodh_evaluator_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER aodh
