FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block etcd_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='etcd') }}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
    {% set etcd_packages = ['etcd'] %}
{% elif base_distro in ['ubuntu', 'debian'] %}
    {% set etcd_packages = ['etcd'] %}
{% endif %}
{{ macros.install_packages(etcd_packages | customizable("packages")) }}

COPY etcd_sudoers /etc/sudoers.d/kolla_etcd_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN chmod 755 /usr/local/bin/kolla_extend_start \
    && chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/kolla_etcd_sudoers

{% block etcd_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER etcd
