FROM {{ namespace }}/{{ image_prefix }}barbican-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block barbican_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

COPY extend_start.sh /usr/local/bin/kolla_barbican_extend_start

RUN chmod 644 /usr/local/bin/kolla_barbican_extend_start

{{ macros.kolla_patch_sources() }}

{% block barbican_api_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER barbican
