FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block openvswitch_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
    {% set openvswitch_base_packages = ['openvswitch'] %}

{% elif base_distro in ['ubuntu', 'debian'] %}
    {% set openvswitch_base_packages = ['openvswitch-switch'] %}

{% endif %}
{{ macros.install_packages(openvswitch_base_packages | customizable("packages")) }}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN touch /usr/local/bin/kolla_openvswitch_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_openvswitch_extend_start

{% block openvswitch_base_footer %}{% endblock %}
