FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block openvswitch_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.enable_extra_repos(['openvswitch']) }}

{% block ovs_install %}

{% if base_package_type == 'rpm' %}
    {% set openvswitch_base_packages = [
        'libibverbs',
        'openvswitch',
        'python3-netifaces',
        'python3-openvswitch',
        'tcpdump'
    ] %}
{% elif base_package_type == 'deb' %}
    {% set openvswitch_base_packages = [
        'openvswitch-switch',
        'python3-openvswitch',
        'python3-netifaces',
        'tcpdump'
    ] %}

{% endif %}
{{ macros.install_packages(openvswitch_base_packages | customizable("packages")) }}

{% endblock %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
COPY ovs_wrapper.sh /usr/local/bin/ovs_wrapper

# NOTE(hrw): Upstream moved tcpdump to /usr/bin/ in 4.99 version (used in Debian)
RUN if [ -e /usr/sbin/tcpdump ]; then mv /usr/sbin/tcpdump /usr/bin/tcpdump; fi \
    && touch /usr/local/bin/kolla_openvswitch_extend_start \
    && chmod 644 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_openvswitch_extend_start \
    && chmod 755 /usr/local/bin/ovs_wrapper

{% block openvswitch_base_footer %}{% endblock %}
