FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        openvswitch \
    && yum clean all

{% elif base_distro in ['ubuntu', 'debian'] %}

RUN apt-get -y install --no-install-recommends \
        openvswitch-switch \
    && apt-get clean

{% endif %}
