FROM {{ namespace }}/{{ image_prefix }}zun-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block zun_compute_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% endif %}

{% set zun_compute_packages = [
    'pciutils',
] %}

{{ macros.install_packages(zun_compute_packages | customizable("packages")) }}

{% block zun_compute_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER zun
