FROM {{ namespace }}/{{ image_prefix }}zun-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block zun_compute_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.enable_extra_repos(['ceph']) }}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% endif %}

{% set zun_compute_packages = [
    'ceph-common',
    'e2fsprogs',
    'pciutils',
    'xfsprogs',
] %}

{{ macros.install_packages(zun_compute_packages | customizable("packages")) }}

COPY zun_sudoers /etc/sudoers.d/kolla_zun_sudoers
COPY extend_start.sh /usr/local/bin/kolla_zun_extend_start

RUN chmod 755 /usr/local/bin/kolla_zun_extend_start \
    && chmod 750 /etc/sudoers.d \
    && chmod 640 /etc/sudoers.d/kolla_zun_sudoers

{% block zun_compute_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER zun
