FROM {{ namespace }}/{{ image_prefix }}octavia-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"
{% endblock %}

{% block octavia_worker_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.kolla_patch_sources() }}

{% block octavia_worker_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER octavia
