FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-openstack-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

# until packaging is fixed, all of this is required
# api: policy
RUN yum -y install \
        python-oslo-log \
        python-oslo-concurrency \
        python-oslo-policy \
    && yum clean all

    {% elif base_distro in ['ubuntu', 'debian'] %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

    {% endif %}
{% elif install_type == 'source' %}

ADD ironic-base-archive /ironic-base-source
RUN ln -s ironic-base-source/* ironic \
    && useradd --user-group ironic \
    && pip --no-cache-dir install /ironic \
    && mkdir -p /etc/ironic /var/log/ironic /home/ironic \
    && cp -r /ironic/etc/* /etc/ironic/ \
    && chown -R ironic: /etc/ironic /var/log/ironic /home/ironic

{% endif %}
