FROM {{ namespace }}/{{ image_prefix }}ovsdpdk:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block ovsdpdk_db_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

COPY extend_start.sh /usr/local/bin/kolla_ovsdpdk_extend_start
COPY start_ovsdb_server.sh /usr/local/bin/start-ovsdb-server
RUN chmod 644 /usr/local/bin/kolla_ovsdpdk_extend_start && \
    chmod 755 /usr/local/bin/start-ovsdb-server

{{ macros.kolla_patch_sources() }}

{% block ovsdpdk_db_footer %}{% endblock %}
{% block footer %}{% endblock %}
