FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block dragonflow_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='dragonflow') }}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

{% if base_package_type == 'rpm' %}
    {% set dragonflow_base_packages = [
       'zeromq-devel'
    ] %}

{% elif base_package_type == 'deb' %}
    {% set dragonflow_base_packages = [
       'libzmq3-dev'
    ] %}

{% endif %}

{{ macros.install_packages(dragonflow_base_packages | customizable("packages")) }}

{% set dragonflow_base_pip_packages = [
    '/dragonflow'
] %}

ADD dragonflow-base-archive /dragonflow-base-source
RUN ln -s dragonflow-base-source/* dragonflow \
    && {{ macros.install_pip(dragonflow_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/dragonflow \
    && cp -r /dragonflow/etc/* /etc/dragonflow/ \
    && chown -R dragonflow: /etc/dragonflow

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN touch /usr/local/bin/kolla_dragonflow_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_dragonflow_extend_start

{% block dragonflow_base_footer %}{% endblock %}
