FROM {{ namespace }}/{{ image_prefix }}designate-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block designate_mdns_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}
       {% set designate_mdns_packages = ['openstack-designate-mdns'] %}
    {% elif base_distro in ['ubuntu'] %}
       {% set designate_mdns_packages = ['designate-mdns'] %}
    {% endif %}
{{ macros.install_packages(designate_mdns_packages | customizable("packages")) }}
{% endif %}

{% block designate_mdns_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER designate
