FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block vitrage_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='vitrage') }}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

{% set vitrage_base_pip_packages = [
    '/vitrage'
] %}

ADD vitrage-base-archive /vitrage-base-source
RUN ln -s vitrage-base-source/* vitrage \
    && {{ macros.install_pip(vitrage_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/vitrage \
    && cp -r /vitrage/etc/vitrage/* /etc/vitrage/ \
    && chown -R vitrage: /etc/vitrage

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block vitrage_base_footer %}{% endblock %}
