FROM {{ namespace }}/{{ image_prefix }}ironic-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}
        {% set ironic_api_packages = ['openstack-ironic-api'] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set ironic_api_packages = ['ironic-api'] %}
    {% endif %}

{{ macros.install_packages(ironic_api_packages | customizable("packages")) }}

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block ironic_api_footer %}{% endblock %}
{{ include_footer }}

USER ironic
