FROM {{ namespace }}/{{ image_prefix }}ironic-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block ironic_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set ironic_api_packages = [
            'httpd',
            'mod_ssl',
            'mod_wsgi',
            'openstack-ironic-api'
        ] %}
    {% elif base_distro in ['debian', 'ubuntu'] %}
        {% set ironic_api_packages = [
            'apache2',
            'ironic-api',
            'libapache2-mod-wsgi'
        ] %}
    {% endif %}

{% elif install_type == 'source' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set ironic_api_packages = [
            'httpd',
            'mod_ssl',
            'mod_wsgi'
        ] %}
    {% elif base_distro in ['debian', 'ubuntu'] %}
        {% set ironic_api_packages = [
            'apache2',
            'libapache2-mod-wsgi'
        ] %}
    {% endif %}

{% endif %}

{{ macros.install_packages(ironic_api_packages | customizable("packages")) }}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
RUN sed -i -r 's,^(Listen 80),#\1,' /etc/httpd/conf/httpd.conf \
    && sed -i -r 's,^(Listen 443),#\1,' /etc/httpd/conf.d/ssl.conf

{% elif base_distro in ['debian', 'ubuntu'] %}
RUN echo > /etc/apache2/ports.conf

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_ironic_extend_start
RUN chmod 755 /usr/local/bin/kolla_ironic_extend_start

{% block ironic_api_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER ironic
