FROM {{ namespace }}/{{ image_prefix }}ironic-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block ironic_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_package_type == 'rpm' %}
        {% set ironic_api_packages = [
            'httpd',
            'mod_ssl',
            'openstack-ironic-api'
        ] %}
        {% if distro_python_version.startswith('3') %}
        {% set ironic_api_packages = ironic_api_packages + ['python3-mod_wsgi'] %}
        {% else %}
        {% set ironic_api_packages = ironic_api_packages + ['mod_wsgi'] %}
        {% endif %}
    {% elif base_package_type == 'deb' %}
        {% set ironic_api_packages = [
            'apache2',
            'ironic-api',
            'libapache2-mod-wsgi'
        ] %}
    {% endif %}

{% elif install_type == 'source' %}
    {% if base_package_type == 'rpm' %}
        {% set ironic_api_packages = [
            'httpd',
            'mod_ssl',
        ] %}
        {% if distro_python_version.startswith('3') %}
        {% set ironic_api_packages = ironic_api_packages + ['python3-mod_wsgi'] %}
        {% else %}
        {% set ironic_api_packages = ironic_api_packages + ['mod_wsgi'] %}
        {% endif %}
    {% elif base_package_type == 'deb' %}
        {% set ironic_api_packages = [
            'apache2',
            'libapache2-mod-wsgi'
        ] %}
    {% endif %}

{% endif %}

{{ macros.install_packages(ironic_api_packages | customizable("packages")) }}

{% if base_package_type == 'rpm' %}
RUN sed -i -r 's,^(Listen 80),#\1,' /etc/httpd/conf/httpd.conf \
    && sed -i -r 's,^(Listen 443),#\1,' /etc/httpd/conf.d/ssl.conf

{% elif base_package_type == 'deb' %}
RUN echo > /etc/apache2/ports.conf

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_ironic_extend_start
RUN chmod 755 /usr/local/bin/kolla_ironic_extend_start

{% block ironic_api_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER ironic
