FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block neutron_metadata_agent_ovn_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% block neutron_metadata_agent_ovn_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
