FROM {{ namespace }}/{{ image_prefix }}designate-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

# The bind9 package here is only to provide the rndc binary.
RUN yum -y install \
        bind \
        openstack-designate-pool-manager \
    && yum clean all

    {% elif base_distro in ['ubuntu'] %}

RUN apt-get -y install --no-install-recommends \
        bind9 \
        designate-pool-manager \
    && apt-get clean

    {% endif %}
{% endif %}

{{ include_footer }}

USER designate
