FROM {{ namespace }}/{{ image_prefix }}designate-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

# The bind9 package here is only to provide the rndc binary.
RUN yum install -y \
        openstack-designate-pool-manager \
        bind \
    && yum clean all

    {% elif base_distro in ['ubuntu'] %}

RUN apt-get install -y --no-install-recommends \
        designate-pool-manager \
        bind9 \
    && apt-get clean

    {% endif %}
{% endif %}

{{ include_footer }}

USER designate
