FROM {{ namespace }}/{{ image_prefix }}kube-base:{{ tag }}
MAINTAINER {{ maintainer }}

ENV KUBERNETES_COMPONENT=kube-scheduler

{% block kube_scheduler_amd64_header %}{% endblock %}

RUN true \
    && curl -L ${KUBERNETES_DOWNLOAD_ROOT}/${KUBERNETES_COMPONENT} -o /usr/bin/${KUBERNETES_COMPONENT} \
    && chmod +x /usr/bin/${KUBERNETES_COMPONENT}

# Clear any customisation by Kolla to entrypoint & command
ENTRYPOINT []
CMD []

{% block kube_scheduler_amd64_footer %}{% endblock %}
{% block footer %}{% endblock %}
