FROM {{ namespace }}/{{ image_prefix }}ceph-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block ceph_nfs_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}

        {% set ceph_nfs_packages = [
            'nfs-ganesha',
            'nfs-ganesha-ceph'
        ] %}
{% elif base_distro in ['ubuntu'] %}
        {% set ceph_nfs_packages = [
            'nfs-ganesha',
            'nfs-ganesha-ceph'
        ] %}

{% endif %}

{{ macros.install_packages(ceph_nfs_packages | customizable("packages")) }}

{% block ceph_nfs_footer %}{% endblock %}
{% block footer %}{% endblock %}
