FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block heka_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='heka', homedir='/var/cache/hekad') }}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
    {% set heka_packages = [
        'https://github.com/mozilla-services/heka/releases/download/v0.10.0/heka-0_10_0-linux-amd64.rpm'
    ] %}
RUN mkdir /etc/heka

{% elif base_distro in ['ubuntu', 'debian'] %}
    {% set heka_packages = [
        'https://github.com/mozilla-services/heka/releases/download/v0.10.0/heka_0.10.0_amd64.deb'
    ] %}
{% endif %}

{{ macros.install_packages(heka_packages | customizable("packages")) }}

COPY plugins/modules /usr/share/heka/lua_modules/
COPY plugins/decoders /usr/share/heka/lua_decoders/
COPY plugins/encoders /usr/share/heka/lua_encoders/

COPY heka_sudoers /etc/sudoers.d/kolla_heka_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN chmod 440 /etc/sudoers.d/kolla_heka_sudoers \
    && chmod 755 /usr/local/bin/kolla_extend_start \
    && chown -R heka: /usr/share/heka /etc/heka

{% block heka_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER heka
