FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net.kolla)

# NOTE(pbourke): This is emulating the Swift "all-in-one" setups where there are 3 disks/partitions
# on which to mirror data.  This is extremely inefficient and is really only to prove everything
# works in an AIO setup. For production deploys the Ansible provisioned setup should be used.
VOLUME [ "/srv/node/sdb1" ]
VOLUME [ "/srv/node/sdb2" ]
VOLUME [ "/srv/node/sdb3" ]

# Command needed to start the data container.
# Note: data containers do not need to be persistent.
CMD ["/bin/true"]
