FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net.kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install openstack-swift \
    && yum clean all

    {% endif %}
{% elif install_type == 'source' %}

ADD swift-base-archive /swift-base-source
RUN ln -s swift-base-source/* swift \
    && useradd --user-group swift \
    && pip --no-cache-dir install /swift \
    && mkdir -p /etc/swift /var/log/swift /home/swift \
    && cp -r /swift/etc/* /etc/swift/ \
    && chown -R swift: /etc/swift /var/log/swift /home/swift

{% endif %}

COPY config-swift.sh /usr/local/bin/kolla_config_swift
COPY build-swift-ring.py /usr/local/bin/kolla_build_swift_ring
RUN mkdir /opt/swift
