FROM {{ namespace }}/{{ image_prefix }}monasca-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block monasca_notification_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

ADD monasca-notification-archive /monasca-notification-source

{% set monasca_notification_pip_packages = [
    '/monasca-notification'
] %}

RUN ln -s monasca-notification-source/* monasca-notification \
    && {{ macros.install_pip(monasca_notification_pip_packages | customizable("pip_packages")) }}

{% block monasca_notification_footer %}{% endblock %}

{% block footer %}{% endblock %}

USER monasca
