FROM {{ namespace }}/{{ image_prefix }}trove-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block trove_taskmanager_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
       {% set trove_taskmanager_packages = ['openstack-trove-taskmanager'] %}
    {% elif base_distro in ['debian', 'ubuntu'] %}
        {% set trove_taskmanager_packages = ['trove-taskmanager'] %}
    {% endif %}

{{ macros.install_packages(trove_taskmanager_packages | customizable("packages")) }}

{% endif %}

{% block trove_taskmanager_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER trove
