FROM {{ namespace }}/{{ image_prefix }}sensu-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block sensu_client_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
    {% set sensu_client_packages = ['docker-client', 'osops-tools-monitoring-oschecks'] %}
{% elif base_distro in ['debian', 'ubuntu'] %}
    {% set sensu_client_packages = ['docker.io'] %}
{% else %}
RUN echo '{{ image_name }} not yet available for {{ base_distro }}' \
    && /bin/false
{% endif %}

{{ macros.install_packages(sensu_client_packages | customizable("packages")) }}

{% block sensu_client_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER sensu
