FROM {{ namespace }}/{{ image_prefix }}freezer-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block freezer_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% set freezer_api_packages = [
] %}

{{ macros.install_packages(freezer_api_packages | customizable("packages")) }}

ADD freezer-api-archive /freezer-api-source

{% set freezer_api_pip_packages = [
    '/freezer-api'
] %}

COPY extend_start.sh /usr/local/bin/kolla_freezer_extend_start

RUN ln -s freezer-api-source/* freezer-api \
    && {{ macros.install_pip(freezer_api_pip_packages | customizable("pip_packages")) }} \
    && cp -r /freezer-api/etc/freezer/* /etc/freezer/ \
    && chmod 644 /usr/local/bin/kolla_freezer_extend_start

{% block freezer_api_footer %}{% endblock %}
{% block footer %}{% endblock %}
