FROM {{ namespace }}/{{ image_prefix }}karbor-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block karbor_protection_header %}{% endblock %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% endif %}

{% block karbor_protection_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER karbor
