FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block kubetoolbox_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% set kubetoolbox_packages = [
   'jq',
   'ceph-common',
   'ipmitool'
] %}

{{ macros.install_packages(kubetoolbox_packages | customizable("packages")) }}

RUN curl -o /usr/bin/kubectl http://storage.googleapis.com/kubernetes-release/release/v1.4.0/bin/linux/amd64/kubectl \
    && chmod 755 /usr/bin/kubectl

{% block kubetoolbox_footer %}{% endblock %}
{% block footer %}{% endblock %}
