FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block telegraf_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='telegraf', homedir='/etc/telegraf') }}

{% set telegraf_packages = [
    'chrony',
    'net-tools',
    'telegraf'
] %}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
    {% set telegraf_packages = telegraf_packages + [
        'collectd',
        'python2-pip'
    ] %}
{% elif base_distro in ['debian', 'ubuntu'] %}
    {% set telegraf_packages = telegraf_packages + [
        'collectd-core',
        'python-pip'
    ] %}
{% endif %}

{{ macros.install_packages(telegraf_packages | customizable("packages")) }}

COPY telegraf_sudoers /etc/sudoers.d/kolla_telegraf_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/kolla_telegraf_sudoers \
    && chmod 755 /usr/local/bin/kolla_extend_start

{% block telegraf_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER telegraf
