FROM {{ namespace }}/{{ infra_image_prefix }}base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block telegraf_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='telegraf', homedir='/etc/telegraf') }}

{{ macros.enable_extra_repos(['influxdb', 'opstools']) }}

{% set telegraf_packages = [
    'chrony',
    'net-tools',
    'telegraf'
] %}

{% if base_package_type == 'rpm' %}
    {% set telegraf_packages = telegraf_packages + [
        'collectd',
        'python3-pip'
    ] %}
{% elif base_package_type == 'deb' %}
    {% set telegraf_packages = telegraf_packages + [
        'collectd-core',
        'python3-pip'
    ] %}
{% endif %}

{{ macros.install_packages(telegraf_packages | customizable("packages")) }}

COPY telegraf_sudoers /etc/sudoers.d/kolla_telegraf_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/kolla_telegraf_sudoers \
    && chmod 755 /usr/local/bin/kolla_extend_start

{% block telegraf_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER telegraf
