FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block rally_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}

{% if base_distro in ['fedora', 'centos', 'oraclelinux', 'rhel'] %}
    {% set rally_packages = ['openstack-rally'] %}
RUN useradd --user-group rally

{% elif base_distro in ['ubuntu'] %}
    {% set rally_packages = ['rally'] %}
{% endif %}
{{ macros.install_packages(rally_packages | customizable("packages")) }}
{% elif install_type == 'source' %}

ADD rally-archive /rally-source
RUN ln -s rally-source/* rally \
    && useradd --user-group rally \
    && /var/lib/kolla/venv/bin/pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt /rally \
    && mkdir -p /etc/rally /var/log/rally /home/rally \
    && chown -R rally: /etc/rally /var/log/rally /home/rally

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

RUN usermod -a -G kolla rally

{% block rally_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER rally
