FROM {{ namespace }}/{{ image_prefix }}prometheus-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block node_exporter_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% block node_exporter_install %}
ADD prometheus-node-exporter-archive /prometheus-node-exporter-source

RUN ln -s /prometheus-node-exporter-source/* prometheus-node-exporter \
    && mkdir -p /opt/node_exporter/ \
    && cp /prometheus-node-exporter/node_exporter /opt/node_exporter/
{% endblock %}

{{ macros.kolla_patch_sources() }}

{% block node_exporter_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER prometheus
