FROM {{ namespace }}/{{ image_prefix }}murano-base:{{ tag }}
MAINTAINER {{ maintainer }}
{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}
       {% set murano_api_packages = ['openstack-murano-api'] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set murano_api_packages = ['murano-api'] %}
    {% endif %}

{{ macros.install_packages(murano_api_packages | customizable("packages")) }}

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_murano_extend_start
RUN chmod 755 /usr/local/bin/kolla_murano_extend_start

{% block murano_api_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER murano
