FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block neutron_lbaas_agent_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% set neutron_lbaas_agent_packages = [
    'haproxy',
    'net-tools'
] %}
{{ macros.install_packages(neutron_lbaas_agent_packages | customizable("packages")) }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}

        {% set neutron_lbaas_agent_packages = [
            'openstack-neutron-lbaas'
        ] %}

    {% elif base_distro in ['ubuntu'] %}

        {% set neutron_lbaas_agent_packages = [
            'neutron-lbaas-common',
            'neutron-lbaasv2-agent',
            'python-neutron-lbaas'
        ] %}

    {% endif %}

{{ macros.install_packages(neutron_lbaas_agent_packages | customizable("packages")) }}

{% elif install_type == 'source' %}

ADD neutron-lbaas-agent-archive /neutron-lbaas-agent-source
RUN ln -s neutron-lbaas-agent-source/* neutron_lbaas \
    && /var/lib/kolla/venv/bin/pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt /neutron_lbaas \
    && cp /neutron_lbaas/etc/neutron/rootwrap.d/* /etc/neutron/rootwrap.d \
    && sed -i 's|^exec_dirs.*|exec_dirs=/var/lib/kolla/venv/bin,/sbin,/usr/sbin,/bin,/usr/bin,/usr/local/bin,/usr/local/sbin|g' /etc/neutron/rootwrap.conf

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_neutron_extend_start
RUN chmod 755 /usr/local/bin/kolla_neutron_extend_start

{% block neutron_lbaas_agent_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
