FROM {{ namespace }}/{{ image_prefix }}ceph-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block ceph_mon_header %}{% endblock %}

COPY fetch_ceph_keys.py /usr/bin/

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start /usr/bin/fetch_ceph_keys.py

{% block ceph_mon_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}
