FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-ceph-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

COPY start.sh /
COPY fetch_ceph_keys.py /usr/bin/

CMD ["/start.sh"]
