FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        hostname \
        https://github.com/rabbitmq/rabbitmq-server/releases/download/rabbitmq_v3_5_5/rabbitmq-server-3.5.5-3.noarch.rpm \
    && yum clean all \
    && rm -rf /var/lib/rabbitmq/*

{% elif base_distro in ['ubuntu', 'debian'] %}

RUN apt-get install -y --no-install-recommends rabbitmq-server \
    && apt-get clean \
    && rm -rf /var/lib/rabbitmq/*

{% endif %}

# NOTE(sdake): the /bin/true unblocks th rabbitmq-plugins tool. Not sure how
#              or why.  My suspicion is it sends a signal to the parent
#              process.
RUN /usr/lib/rabbitmq/bin/rabbitmq-plugins enable --offline rabbitmq_management \
    && /bin/true

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{{ include_footer }}
