FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block opensearch_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='opensearch', shell='/bin/bash', homedir='/usr/share/opensearch') }}

{% block opensearch_version %}

    {% if base_arch == 'x86_64' %}
        {% set arch_os='x64' %}
    {% elif base_arch == 'aarch64' %}
        {% set arch_os='arm64' %}
    {% endif %}

ARG opensearch_version=2.3.0
ARG opensearch_dashboards_url=https://artifacts.opensearch.org/releases/bundle/opensearch-dashboards/${opensearch_version}/opensearch-dashboards-${opensearch_version}-linux-{{ arch_os }}.tar.gz
{% endblock %}

ARG OPENSEARCH_DASHBOARDS_HOME=/usr/share/opensearch-dashboards

RUN mkdir -p $OPENSEARCH_DASHBOARDS_HOME && \
    curl -o /tmp/opensearch-dashboards.tgz ${opensearch_dashboards_url} && \
    tar -xzpf /tmp/opensearch-dashboards.tgz -C $OPENSEARCH_DASHBOARDS_HOME --strip-components=1 && \
    rm /tmp/opensearch-dashboards.tgz

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block opensearch_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER opensearch
