FROM {{ namespace }}/{{ image_prefix }}heat-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block heat_all_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_package_type == 'rpm' %}
       {% set heat_all_packages = [
            'openstack-heat-api',
            'openstack-heat-engine',
            'openstack-heat-monolith'
        ] %}
    {% elif base_package_type == 'deb' %}
RUN echo 'heat-all not yet available for {{ base_distro }}' && /bin/false
    {% endif %}
{{ macros.install_packages(heat_all_packages | customizable("packages")) }}

{% endif %}
{% block heat_all_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER heat
