FROM {{ namespace }}/{{ image_prefix }}designate-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block designate_backend_bind9_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}
       {% set designate_backend_bind9_packages = ['bind'] %}

{{ macros.install_packages(designate_backend_bind9_packages | customizable("packages")) }}
RUN mkdir -p /var/lib/kolla/ \
    && cp -pr /var/named /var/lib/kolla/var-named

    {% elif base_distro in ['ubuntu'] %}
       {% set designate_backend_bind9_packages = ['bind9'] %}

{{ macros.install_packages(designate_backend_bind9_packages | customizable("packages")) }}

    {% endif %}
{% endif %}

{% block designate_backend_bind9_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER designate
