FROM {{ namespace }}/{{ image_prefix }}designate-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net.kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum install -y bind \
    && yum clean all \
    && cp -pr /var/named /opt/kolla/var-named

    {% endif %}
{% endif %}

{{ include_footer }}
