FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-heat-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

# TODO(SamYaple): until packaging is fixed, all of the python clients below are required
# http://pkgs.fedoraproject.org/cgit/openstack-heat.git/tree/openstack-heat.spec#n248
RUN yum -y install \
        python-barbicanclient \
        python-zaqarclient \
        openstack-heat-engine \
    && yum clean all

    {% endif %}
{% endif %}

COPY start.sh /

CMD ["/start.sh"]

{{ include_footer }}
