FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block influxdb_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% set influxdb_packages = ['influxdb'] %}
{{ macros.install_packages(influxdb_packages | customizable("packages")) }}

COPY influxdb_sudoers /etc/sudoers.d/kolla_influxdb_sudoers
RUN chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/kolla_influxdb_sudoers \
    && usermod -a -G kolla influxdb

{% block influxdb_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER influxdb
