FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block mariadb_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='mysql') }}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
    {% set mariadb_packages = [
        'MariaDB-Galera-server',
        'MariaDB-client',
        'rsync',
        'galera',
        'socat',
        'hostname',
        'percona-xtrabackup',
        'pv',
        'tar',
        'expect'
    ] %}
{% elif base_distro in ['ubuntu', 'debian'] %}
    {% set mariadb_packages = [
        'mariadb-galera-server',
        'percona-xtrabackup',
        'socat',
        'expect'
    ] %}
{% endif %}

{{ macros.install_packages(mariadb_packages | customizable("packages")) }}
COPY mariadb_sudoers /etc/sudoers.d/kolla_mariadb_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start
COPY security_reset.expect /usr/local/bin/kolla_security_reset
RUN chmod 755 /usr/local/bin/kolla_extend_start \
    && chmod 755 /usr/local/bin/kolla_security_reset \
    && chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/kolla_mariadb_sudoers \
    && rm -rf /var/lib/mysql/*

{% block mariadb_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER mysql
