#!/bin/bash -e

ln -s /dev/stderr /var/log/mysql/mysqld.log
if [ ! -f /var/lib/mysql/.created ]; then
  function wait_for_mysqld_start {
    for i in {1..30}; do
      if echo 'select 1' | mysql -u root > /dev/null 2>&1; then
        return 0
      fi
      sleep 1
    done

    echo "MariaDB did not start in time"
    exit 1
  }

  host_ip=${HOST_IP:-127.0.0.1}
  password=${DB_ROOT_PASSWORD:-redhat}
  #keystone_pass=${KEYSTONE_PASSWORD:-redhat}
  #cinder_pass=${CINDER_PASSWORD:-redhat}
  #glance_pass=${KEYSTONE_PASSWORD:-redhat}
  #nova_pass=${KEYSTONE_PASSWORD:-redhat}
  #heat_pass=${KEYSTONE_PASSWORD:-redhat}
  #keystone_pass=${KEYSTONE_PASSWORD:-redhat}

  /usr/bin/mysql_install_db -u mysql

  /usr/libexec/mysqld &
  pid=$!

  wait_for_mysqld_start

  echo "Building OpenStack Database tables..."

  /usr/bin/mysqladmin -u root password $password

  touch /var/lib/mysql/.created
  kill -TERM $pid

  echo "Starting mysqld ..."
fi

exec /usr/libexec/mysqld
