FROM {{ namespace }}/{{ image_prefix }}gnocchi-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block gnocchi_statsd_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
       {% set gnocchi_statsd_packages = ['openstack-gnocchi-statsd'] %}
    {% endif %}
{{ macros.install_packages(gnocchi_statsd_packages | customizable("packages")) }}

{% endif %}
{% block gnocchi_statsd_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER gnocchi
