FROM {{ namespace }}/{{ image_prefix }}sahara-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block sahara_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
       {% set sahara_api_packages = ['openstack-sahara-api'] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set sahara_api_packages = ['sahara-api'] %}
    {% endif %}
{{ macros.install_packages(sahara_api_packages | customizable("packages")) }}
{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_sahara_extend_start
RUN chmod 755 /usr/local/bin/kolla_sahara_extend_start

{% block sahara_api_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER sahara
