FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block kuryr_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='kuryr') }}

ADD kuryr-base-archive /kuryr-base-source

{% set kuryr_base_pip_packages = [
    '/kuryr-base'
] %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

# NOTE(Jeffrey4l): remove kuryr-lib constraint in upper-constraints.txt file.
# Otherwise, it will be failed.
RUN ln -s kuryr-base-source/* kuryr-base \
    && {{ macros.upper_constraints_remove("kuryr-lib") }} \
    && {{ macros.install_pip(kuryr_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/kuryr \
    && chmod 644 /usr/local/bin/kolla_extend_start

{{ macros.kolla_patch_sources() }}

{% block kuryr_base_footer %}{% endblock %}
