FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

ADD kuryr-base-archive /kuryr-base-source
RUN ln -s kuryr-base-source/* kuryr-base \
    && /var/lib/kolla/venv/bin/pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt /kuryr-base

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

{% block kuryr_base_footer %}{% endblock %}
