FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net.kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux'] %}

RUN yum -y install \
    openstack-dashboard \
    httpd \
    mod_wsgi \
    && yum clean all \
    && chown -R apache:apache /usr/share/openstack-dashboard/static

# The chown is required because of this packaging bug:
# https://bugzilla.redhat.com/show_bug.cgi?id=1219006

    {% elif base_distro in ['ubuntu', 'debian'] %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

    {% endif %}

{% elif install_type == 'source' %}

ADD ./horizon.tar /
RUN ln -s /horizon-* /horizon

RUN yum install -y \
    httpd \
    mod_wsgi \
    && yum clean all

RUN cd /horizon \
    && useradd --user-group horizon \
    && pip install -r requirements.txt \
    && pip install /horizon \
    && mkdir -p /etc/openstack-dashboard /var/log/horizon /usr/share/openstack-dashboard/static \
    && chown -R apache:apache /usr/share/openstack-dashboard/static \
    && rm -rf /root/.cache

# The chown is required because of this packaging bug:
# https://bugzilla.redhat.com/show_bug.cgi?id=1219006

{% endif %}

COPY config-external.sh /opt/kolla/
COPY start.sh /

CMD ["/start.sh"]
