FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block neutron_metadata_agent_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['ubuntu', 'debian'] %}
    {% if install_type == 'binary' %}

        {% set neutron_metadata_agent_packages = [
            'neutron-metadata-agent'
        ] %}

    {% endif %}
{% endif %}

{{ macros.install_packages(neutron_metadata_agent_packages | customizable("packages")) }}

COPY neutron_sudoers /etc/sudoers.d/kolla_neutron_metadata_sudoers
COPY extend_start.sh /usr/local/bin/kolla_neutron_extend_start
RUN chmod 755 /usr/local/bin/kolla_neutron_extend_start \
    && chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/kolla_neutron_metadata_sudoers

{% block neutron_metadata_agent_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
