FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if base_distro in ['ubuntu', 'debian'] %}
    {% if install_type == 'binary' %}

RUN apt-get install -y --no-install-recommends \
        neutron-metadata-agent \
    && apt-get clean

    {% endif %}
{% endif %}

COPY neutron_sudoers /etc/sudoers.d/neutron_sudoers
COPY extend_start.sh /usr/local/bin/kolla_neutron_extend_start
RUN chmod 755 /usr/local/bin/kolla_neutron_extend_start \
    && chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/neutron_sudoers \
    && usermod -a -G kolla neutron

{{ include_footer }}

USER neutron
