FROM {{ namespace }}/{{ base_distro }}-{{ install_type  }}-cinder-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum install -y lvm2 \
    scsi-target-utils \
  && yum clean all

    {% endif %}
{% endif %}

COPY ./start.sh /

CMD ["/start.sh"]

{{ include_footer }}
