FROM {{ namespace }}/{{ image_prefix }}cinder-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum install -y \
        lvm2 \
        scsi-target-utils \
    && yum clean all

   {% elif base_distro in ['ubuntu'] %}

RUN apt-get install -y --no-install-recommends \
        cinder-volume \
    && apt-get clean

    {% endif %}
{% endif %}

{{ include_footer }}

USER cinder
