FROM {{ namespace }}/{{ image_prefix }}ovn-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"
{% endblock %}

{% block ovn_controller_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.kolla_enable_base_repos() }}

{% if base_package_type == 'rpm' %}

{{ macros.enable_extra_repos(['openvswitch']) }}

    {% set ovn_controller_packages = [
        'ovn${KOLLA_RPM_OVN_VERSION}-host'
    ] %}

{% elif base_package_type == 'deb' %}
    {% set ovn_controller_packages = [
        'ovn-host'
    ] %}

{% endif %}
{{ macros.install_packages(ovn_controller_packages | customizable("packages")) }}

COPY extend_start.sh /usr/local/bin/kolla_ovn_extend_start
RUN chmod 644 /usr/local/bin/kolla_ovn_extend_start

{{ macros.kolla_patch_sources() }}

{% block ovn_controller_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ macros.kolla_cleanup_repos() }}
