FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block neutron_openvswitch_agent_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}

        {% set neutron_openvswitch_agent_packages = [
            'openstack-neutron-openvswitch',
            'openvswitch'
        ] %}

    {% elif base_distro in ['ubuntu'] %}

        {% set neutron_openvswitch_agent_packages = [
            'neutron-plugin-openvswitch-agent',
            'openvswitch-switch'
        ] %}

    {% endif %}
{% endif %}

{{ macros.install_packages(neutron_openvswitch_agent_packages | customizable("packages")) }}

{% block neutron_openvswitch_agent_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
