FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-neutron-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net.kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

# Install required packages
RUN yum install -y \
        openstack-neutron-openvswitch \
        openvswitch \
    && yum clean all

    {% endif %}
{% elif install_type == 'source' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

# Install required packages
RUN yum install -y \
        openvswitch \
    && yum clean all

    {% endif %}
{% endif %}

COPY start.sh /
COPY config-external.sh /opt/kolla/

CMD ["/start.sh"]

{{ include_footer }}
