FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block neutron_openvswitch_agent_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.install_packages(neutron_openvswitch_agent_packages | customizable("packages")) }}

{{ macros.kolla_patch_sources() }}

{% block neutron_openvswitch_agent_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
