FROM {{ namespace }}/{{ image_prefix }}tacker-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block tacker_server_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}

    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set tacker_server_packages = [
            'openstack-tacker'
        ] %}

    {% elif base_distro in ['debian', 'ubuntu'] %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

    {% endif %}

{{ macros.install_packages(tacker_server_packages | customizable("packages")) }}

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_tacker_extend_start
RUN chmod 755 /usr/local/bin/kolla_tacker_extend_start

{% block tacker_server_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER tacker
