FROM {{ namespace }}/{{ image_prefix }}tacker-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"
{% endblock %}

{% block tacker_server_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

COPY extend_start.sh /usr/local/bin/kolla_tacker_extend_start
RUN chmod 644 /usr/local/bin/kolla_tacker_extend_start

{{ macros.kolla_patch_sources() }}

{% block tacker_server_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER tacker
