FROM {{ namespace }}/{{ image_prefix }}ceph-base:{{ tag }}
LABEL maintainer="{{ maintainer }}"

{% block ceph_mds_header %}{% endblock %}

{% block ceph_mds_footer %}{% endblock %}
{% block footer %}{% endblock %}
