FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block neutron_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.enable_extra_repos(['docker-ce', 'openvswitch', 'epel']) }}
{{ macros.configure_user(name='neutron') }}

{% if base_package_type == 'rpm' %}

    # FIXME(wszumski): iptables-nft is deprecated. We need to advise users
    # to migrate to some other firewall driver as we cannot rely on this
    # package forever, see: https://access.redhat.com/solutions/6739041.
    # iptables-legacy is not available from EPEL 10.
    {% set neutron_base_packages = [
        'conntrack-tools',
        'dnsmasq',
        'dnsmasq-utils',
        'docker-ce-cli',
        'haproxy',
        'iproute-tc',
        'ipset',
        'iptables',
        'iptables-nft',
        'iputils',
        'keepalived',
        'net-tools',
        'radvd',
        'uuid'
    ] %}
    {% if base_distro_tag.startswith('10') or base_distro_tag.startswith('stream10') %}
        {% set neutron_base_packages = neutron_base_packages + [
            'openvswitch3.5',
            'python3-openvswitch3.5'
        ] %}
    {% else %}
	# NOTE(wszumski): iptables-legacy lets us check and clear out legacy
	# iptables rules due to LP#2144562. This package is installed from the
	# EPEL repository.
        {% set neutron_base_packages = neutron_base_packages + [
            'openvswitch',
            'python3-openvswitch',
            'iptables-legacy',
        ] %}
    {% endif %}

{% elif base_package_type == 'deb' %}

    {% set neutron_base_packages = [
        'conntrack',
        'dnsmasq',
        'dnsmasq-utils',
        'docker-ce-cli',
        'haproxy',
        'iproute2',
        'ipset',
        'iptables',
        'iputils-arping',
        'iputils-ping',
        'keepalived',
        'net-tools',
        'openvswitch-switch',
        'python3-openvswitch',
        'radvd',
        'uuid-runtime'
    ] %}

{% endif %}

{{ macros.install_packages(neutron_base_packages | customizable("packages")) }}

{% if base_distro_tag.startswith('9') or base_distro_tag.startswith('stream9') %}
# NOTE(wszumski): Without this iptables-legacy is selected as default. This
# increases the priority from 10 to 200.
RUN update-alternatives --install /usr/sbin/iptables iptables /usr/sbin/iptables-nft 200 \
  --slave /usr/sbin/ip6tables ip6tables /usr/sbin/ip6tables-nft \
  --slave /usr/sbin/iptables-restore iptables-restore /usr/sbin/iptables-nft-restore \
  --slave /usr/sbin/iptables-save iptables-save /usr/sbin/iptables-nft-save \
  --slave /usr/sbin/ip6tables-restore ip6tables-restore /usr/sbin/ip6tables-nft-restore \
  --slave /usr/sbin/ip6tables-save ip6tables-save /usr/sbin/ip6tables-nft-save \
  && update-alternatives --auto iptables
{% endif %}

ADD neutron-base-archive /neutron-base-source
ADD plugins-archive /

{% set neutron_base_pip_packages = [
    '/neutron',
    'oslo-vmware',
    'tap-as-a-service'
] %}

{% set neutron_base_plugins_pip_packages = [
    '/plugins/*'
] %}

COPY neutron_sudoers /etc/sudoers.d/kolla_neutron_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN mkdir -p /usr/local/lib/neutron-wrappers /usr/local/etc/neutron-wrappers
COPY dnsmasq haproxy keepalived neutron-keepalived-state-change radvd copy-wrappers delete-wrappers /usr/local/lib/neutron-wrappers/
RUN chmod +x /usr/local/lib/neutron-wrappers/copy-wrappers \
    && chmod +x /usr/local/lib/neutron-wrappers/delete-wrappers

RUN ln -s neutron-base-source/* neutron \
    && {{ macros.install_pip(neutron_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/neutron \
    && cp -r /neutron/etc/* /etc/neutron/ \
    && cp -r /neutron/etc/neutron/* /etc/neutron/ \
    && cp /var/lib/kolla/venv/etc/pycadf/neutron_api_audit_map.conf /etc/neutron/ \
    && mv /etc/neutron/neutron/ /etc/neutron/plugins/ \
    && sed -i 's|^exec_dirs.*|exec_dirs=/var/lib/kolla/venv/bin,/sbin,/usr/sbin,/bin,/usr/bin,/usr/local/bin,/usr/local/sbin|g' /etc/neutron/rootwrap.conf \
    && if [ "$(ls /plugins)" ]; then \
        {{ macros.install_pip(neutron_base_plugins_pip_packages) }} \
        && for neutron_plugins in $(ls /plugins); do \
            if [ -d "/plugins/$neutron_plugins/etc/neutron/rootwrap.d" ]; then \
                cp /plugins/$neutron_plugins/etc/neutron/rootwrap.d/* /etc/neutron/rootwrap.d; \
            fi; \
        done; \
       fi \
    && chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/kolla_neutron_sudoers \
    && touch /usr/local/bin/kolla_neutron_extend_start \
    && chmod 644 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_neutron_extend_start

{{ macros.kolla_patch_sources() }}

{% block neutron_base_footer %}{% endblock %}
