FROM {{ namespace }}/{{ image_prefix }}monasca-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block monasca_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

ADD monasca-api-archive /monasca-api-source

{% set monasca_api_pip_packages = [
    '/monasca-api'
] %}

RUN ln -s monasca-api-source/* monasca-api \
    && {{ macros.install_pip(monasca_api_pip_packages | customizable("pip_packages")) }}

{% endif %}

{% block monasca_api_footer %}{% endblock %}

{% block footer %}{% endblock %}

USER monasca

