FROM {{ namespace }}/{{ image_prefix }}aodh-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"
{% endblock %}

{% block aodh_notifier_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.kolla_patch_sources() }}

{% block aodh_notifier_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER aodh
