FROM {{ namespace }}/{{ image_prefix }}mistral-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block mistral_executor_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% block mistral_executor_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER mistral
