FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block cron_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}
    {% set cron_packages = [
        'cronie',
        'logrotate'
    ] %}
{% elif base_distro in ['ubuntu', 'debian'] %}
    {% set cron_packages = [
        'cron',
        'logrotate'
    ] %}
{% endif %}

{{ macros.install_packages(cron_packages | customizable("packages")) }}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block cron_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}
