FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block cron_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'rpm' %}
    {% set cron_packages = [
        'cronie',
        'logrotate'
    ] %}

# NOTE(hrw): In RHEL 9 family it is done by systemd timer, we want cron to
# handle it.
COPY logrotate /etc/cron.daily/logrotate

{% elif base_package_type == 'deb' %}
    {% set cron_packages = [
        'cron',
        'logrotate'
    ] %}
{% endif %}

{{ macros.install_packages(cron_packages | customizable("packages")) }}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 644 /usr/local/bin/kolla_extend_start

{{ macros.kolla_patch_sources() }}

{% block cron_footer %}{% endblock %}
{% block footer %}{% endblock %}
