FROM {{ namespace }}/{{ image_prefix }}keystone-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block keystone_ssh_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='keystone', shell='/bin/bash') }}

{% if base_package_type == 'rpm' %}
    {% set keystone_ssh_packages = [
        'openssh-server',
        'rsync'
    ] %}

{% elif base_package_type == 'deb' %}
    {% set keystone_ssh_packages = [
        'openssh-server',
        'rsync'
    ] %}

RUN mkdir -p /var/run/sshd \
    && chmod 0755 /var/run/sshd

{% endif %}
{{ macros.install_packages(keystone_ssh_packages | customizable("packages")) }}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN sed -ri 's/session(\s+)required(\s+)pam_loginuid.so/session\1optional\2pam_loginuid.so/' /etc/pam.d/sshd \
    && chmod 644 /usr/local/bin/kolla_extend_start

{{ macros.kolla_patch_sources() }}

{% block keystone_ssh_footer %}{% endblock %}
{% block footer %}{% endblock %}
