FROM {{ namespace }}/{{ image_prefix }}keystone-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block keystone_ssh_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='keystone', shell='/bin/bash') }}

{% if base_package_type == 'rpm' %}
    {% set keystone_ssh_packages = [
        'openssh-server',
        'rsync'
    ] %}
{% elif base_package_type == 'deb' %}
    {% set keystone_ssh_packages = [
        'openssh-server',
        'rsync'
    ] %}

RUN mkdir -p /var/run/sshd \
    && chmod 0755 /var/run/sshd

{% endif %}
{{ macros.install_packages(keystone_ssh_packages | customizable("packages")) }}

RUN sed -ri 's/session(\s+)required(\s+)pam_loginuid.so/session\1optional\2pam_loginuid.so/' /etc/pam.d/sshd

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block keystone_ssh_footer %}{% endblock %}
{% block footer %}{% endblock %}
