FROM {{ namespace }}/{{ image_prefix }}monasca-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block monasca_persister_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

ADD monasca-persister-archive /monasca-persister-source
RUN ln -s monasca-persister-source/* monasca-persister \
    && /var/lib/kolla/venv/bin/pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt /monasca-persister

{% endif %}

{% block monasca_persister_footer %}{% endblock %}

{% block footer %}{% endblock %}

USER monasca

