FROM {{ namespace }}/{{ image_prefix }}monasca-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block monasca_persister_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

ADD monasca-persister-archive /monasca-persister-source

{% set monasca_persister_pip_packages = [
    '/monasca-persister',
    'influxdb',
    'elasticsearch',
    'cassandra-driver'
] %}

RUN ln -s monasca-persister-source/* monasca-persister \
    && {{ macros.install_pip(monasca_persister_pip_packages | customizable("pip_packages")) }}

{% endif %}

{% block monasca_persister_footer %}{% endblock %}

{% block footer %}{% endblock %}

USER monasca

