FROM {{ namespace }}/{{ image_prefix }}cyborg-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"
{% endblock %}

{% block cyborg_conductor_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.kolla_patch_sources() }}

{% block cyborg_conductor_footer %}{% endblock %}
{% block footer %}{% endblock %}
