FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block neutron_server_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% set neutron_server_pip_packages = [
    'networking-hyperv'
] %}

{% set neutron_server_plugins_pip_packages = [
    '/plugins/*'
] %}

ADD plugins-archive /

COPY extend_start.sh /usr/local/bin/kolla_neutron_extend_start

RUN {{ macros.install_pip(neutron_server_pip_packages | customizable("pip_packages")) }} \
    && if [ "$(ls /plugins)" ]; then \
           {{ macros.install_pip(neutron_server_plugins_pip_packages) }}; \
       fi \
    && chmod 644 /usr/local/bin/kolla_neutron_extend_start

{{ macros.kolla_patch_sources() }}

{% block neutron_server_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
