FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block neutron_server_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}

        {% set neutron_server_packages = [
            'openstack-neutron-vpnaas'
        ] %}

    {% elif base_distro in ['debian', 'ubuntu'] %}

        {% set neutron_server_packages = [
            'neutron-lbaasv2-agent',
            'python-neutron-dynamic-routing',
            'python-neutron-lbaas',
            'python-neutron-vpnaas'
        ] %}

    {% endif %}

{{ macros.install_packages(neutron_server_packages | customizable("packages")) }}

{% elif install_type == 'source' %}

    {% set neutron_server_pip_packages = [
            '"networking-hyperv>=5.0.0,<6.0.0"'
    ] %}

    {% set neutron_server_plugins_pip_packages = [
        '/plugins/*'
    ] %}

ADD plugins-archive /
RUN {{ macros.install_pip(neutron_server_pip_packages | customizable("pip_packages")) }} \
    && if [ "$(ls /plugins)" ]; then \
           {{ macros.install_pip(neutron_server_plugins_pip_packages) }}; \
       fi

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_neutron_extend_start
RUN chmod 755 /usr/local/bin/kolla_neutron_extend_start

{% block neutron_server_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
