FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block tgtd_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
    {% set tgtd_packages = ['scsi-target-utils'] %}

{{ macros.install_packages(tgtd_packages | customizable("packages")) }}
RUN sed -i '1 i include /var/lib/cinder/volumes/*' /etc/tgt/tgtd.conf

{% elif base_distro in ['ubuntu', 'debian'] %}
    {% set tgtd_packages = ['tgt'] %}

{{ macros.install_packages(tgtd_packages | customizable("packages")) }}
RUN sed -i '1 i include /var/lib/cinder/volumes/*' /etc/tgt/targets.conf

{% endif %}

{% block tgtd_footer %}{% endblock %}
{% block footer %}{% endblock %}
