FROM %%KOLLA_NAMESPACE%%/%%KOLLA_PREFIX%%base
MAINTAINER Kolla Project (https://launchpad.net/kolla)

# Command needed to start the data container.
# Note: data containers do not need to be persistent.
CMD ["/bin/sh"]
