FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block sensu_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='sensu') }}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
    {% set sensu_base_packages = ['sensu'] %}
{% elif base_distro in ['ubuntu'] %}
    {% set sensu_base_packages = ['sensu'] %}
{% else %}
RUN echo '{{ image_name }} not yet available for {{ base_distro }}' \
    && /bin/false
{% endif %}

{{ macros.install_packages(sensu_base_packages | customizable("packages")) }}

{% block sensu_base_footer %}{% endblock %}
