FROM {{ namespace }}/{{ image_prefix }}sensu-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block sensu_server_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'rpm' %}
    {% set sensu_server_packages = [
        'cyrus-sasl-devel',
        'gcc-c++',
        'make',
        'ruby-devel'
    ] %}
{% elif base_package_type == 'deb' %}
    {% set sensu_server_packages = [
        'build-essential',
        'libsasl2-dev'
    ] %}
{% endif %}

{{ macros.install_packages(sensu_server_packages | customizable("packages")) }}

{% block sensu_server_plugins_install %}

# Sensu plugins are all using semantic versioning.
# Let's cap them to the known major version that works with the ruby shipped on
# rhel/centos/oraclelinux (currently 2.0)
{% set sensu_plugins = [
    'mailer:"~>3"',
    'slack:"~>3"'
] %}

RUN sensu-install --plugins {{ sensu_plugins | customizable('plugins') | join (',') }}
{% endblock %}

{% block sensu_server_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER sensu
