#!/bin/bash

# Move to top level directory
REAL_PATH=$(python -c "import os,sys;print os.path.realpath('$0')")
cd "$(dirname "$REAL_PATH")/.."

. tools/validate-docker-execute.sh

KOLLA_IMAGES=$(docker images -a --filter "label=kolla_version" --format "{{.ID}}")

if [[ -z "$KOLLA_IMAGES" ]]; then
    echo "No images to cleanup, exit now."
    exit 0
fi

docker rmi -f $@ $KOLLA_IMAGES
