#!/bin/bash

# Move to top level directory
REAL_PATH=$(python -c "import os,sys;print os.path.realpath('$0')")
cd "$(dirname "$REAL_PATH")/.."

. tools/validate-docker-execute

docker rmi $@ $(docker images -a -q)
