#!/bin/bash

DOCKER=`find docker -type f -exec cat {} \; | wc -l`
DOC=`find doc -type f -exec cat {} \; | wc -l`
TESTS=`find tests -type f -exec cat {} \; | wc -l`
BUILD=`find kolla -type f -exec cat {} \; | wc -l`

SPECS=`find specs -type f -exec cat {} \; | wc -l`
ETC=`find etc -type f -exec cat {} \; | wc -l`
TOOLS=`find tools -type f -exec cat {} \; | wc -l`
DEVENV=`find contrib/dev -type f -exec cat {} \; | wc -l`

CORE=$(($DOCKER+$TESTS+$DOCS+$BUILD+$TOOLS))
SUPP=$(($DEVENV+$SPECS+$ETC))
TOTAL=$(($CORE+$SUPP))


echo "Build        $BUILD"
echo "Doc          $DOC"
echo "Etc          $ETC"
echo "Docker       $DOCKER"
echo "Specs        $SPECS"
echo "Tests        $TESTS"
echo "Tools        $TOOLS"
echo "Devenv       $DEVENV"
echo ""
echo "Core Code    $CORE"
echo "Support Code $SUPP"
echo "Total Code   $TOTAL"
