#!/bin/sh

REAL_PATH=$(python -c "import os,sys;print os.path.realpath('$0')")
cd "$(dirname "$REAL_PATH")/.."

pods='
rabbitmq
mariadb
keystone
glance
nova-controller
nova-compute
neutron-server
heat
mongodb
ceilometer-controller
zaqar
horizon
'

for pod in $pods; do
    kubectl create -f "k8s/pod/${pod}-pod.yaml"
done

