#!/bin/sh

cd $(git rev-parse --show-toplevel)

services='
ceilometer-api
glance-api
glance-registry
keystone-admin
keystone-public
mariadb
nova-api
nova-ec2-api
nova-libvirt
nova-metadata-api
rabbitmq
neutron-server
heat-api
zaqar-server
'

for svc in $services; do
    kubecfg -c "k8s/service/${svc}-service.yaml" create services
done

