#!/bin/sh

REAL_PATH=$(python -c "import os,sys;print os.path.realpath('$0')")
cd "$(dirname "$REAL_PATH")/.."

services='
ceilometer-api
glance-api
glance-registry
keystone-admin
keystone-public
mariadb
mongodb
nova-api
nova-ec2-api
nova-libvirt
nova-metadata-api
rabbitmq
neutron-server
heat-api
zaqar-server
horizon
'

for svc in $services; do
    kubectl create -f "k8s/service/${svc}-service.yaml"
done

