#!/bin/sh

REAL_PATH=$(python -c "import os,sys;print os.path.realpath('$0')")
cd "$(dirname "$REAL_PATH")/.."

services='
nova-compute
'

for svc in $services; do
    kubectl create -f "k8s/replication/${svc}-replication.yaml"
done

