#!/bin/sh

cd $(git rev-parse --show-toplevel)

pods='
rabbitmq
mariadb
keystone
glance
nova-controller
neutron-controller
heat
mongodb
ceilometer-controller
'

for pod in $pods; do
    kubecfg -c "k8s/pod/${pod}-pod.yaml" create pods
done

