#!/bin/sh

cd $(git rev-parse --show-toplevel)

services=$(kubectl get services | awk 'NR>1 {print $1}')

for service in $services; do
    kubectl delete -f "k8s/service/${service}-service.yaml" 2>/dev/null
done
