#!/bin/sh

REAL_PATH=$(python -c "import os,sys;print os.path.realpath('$0')")
cd "$(dirname "$REAL_PATH")/.."

services=$(kubectl get services | awk 'NR>1 {print $1}')

for service in $services; do
    kubectl delete -f "k8s/service/${service}-service.yaml" 2>/dev/null
done
