FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

{% set user = 'memcached' %}
    {% set memcached_packages = ['memcached']  %}
RUN {{ macros.install_packages(memcached_packages | customizable("packages")) }} \
    && usermod -a -G kolla {{ user }}

{% elif base_distro in ['ubuntu', 'debian'] %}

{% set user = 'memcache' %}
    {% set memcached_packages = ['memcached'] %}
RUN {{ macros.install_packages(memcached_packages | customizable("packages")) }} \
    && usermod -a -G kolla {{ user }}

{% endif %}

{% block memcached_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER {{ user }}
