FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block memcached_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='memcached', homedir='/run/memcache') }}

{% set memcached_packages = ['memcached'] %}
{{ macros.install_packages(memcached_packages | customizable("packages")) }}

{{ macros.kolla_patch_sources() }}

{% block memcached_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER memcached
