FROM {{ namespace }}/{{ image_prefix }}cloudkitty-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block cloudkitty_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}

        {% set cloudkitty_api_packages = [
                'httpd',
                'mod_ssl',
                'mod_wsgi',
                'openstack-cloudkitty-api',
        ] %}
{{ macros.install_packages(cloudkitty_api_packages | customizable("packages")) }}
RUN sed -i -r 's,^(Listen 80),#\1,' /etc/httpd/conf/httpd.conf \
    && sed -i -r 's,^(Listen 443),#\1,' /etc/httpd/conf.d/ssl.conf

    {% elif base_distro in ['debian', 'ubuntu'] %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

    {% endif %}

{% elif install_type == 'source' %}

    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set cloudkitty_api_packages = [
                'httpd',
                'mod_ssl',
                'mod_wsgi'
        ] %}
{{ macros.install_packages(cloudkitty_api_packages | customizable("packages")) }}
RUN sed -i -r 's,^(Listen 80),#\1,' /etc/httpd/conf/httpd.conf \
    && sed -i -r 's,^(Listen 443),#\1,' /etc/httpd/conf.d/ssl.conf

    {% elif base_distro in ['ubuntu', 'debian'] %}
        {% set cloudkitty_api_packages = [
                'apache2',
                'libapache2-mod-wsgi'
        ] %}
{{ macros.install_packages(cloudkitty_api_packages | customizable("packages")) }}
RUN echo > /etc/apache2/ports.conf

    {% endif %}

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_cloudkitty_extend_start
RUN chmod 755 /usr/local/bin/kolla_cloudkitty_extend_start

{% block cloudkitty_api_footer %}{% endblock %}
{% block footer %}{% endblock %}
