FROM {{ namespace }}/{{ image_prefix }}cloudkitty-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block cloudkitty_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_cloudkitty_extend_start
RUN chmod 755 /usr/local/bin/kolla_cloudkitty_extend_start

{% block cloudkitty_api_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER cloudkitty
