FROM {{ namespace }}/{{ image_prefix }}designate-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block designate_pool_manager_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

# The bind9 package here is only to provide the rndc binary.
{% if install_type == 'binary' %}
    {% if base_package_type == 'rpm' %}
       {% set designate_pool_manager_packages = [
            'bind',
            'openstack-designate-pool-manager'
        ] %}
    {% elif base_package_type == 'deb' %}
       {% set designate_pool_manager_packages = [
            'bind9',
            'designate-pool-manager'
        ] %}
    {% endif %}
{% elif install_type == 'source' %}
    {% if base_package_type == 'rpm' %}
       {% set designate_pool_manager_packages = [
            'bind'
        ] %}
    {% elif base_package_type == 'deb' %}
       {% set designate_pool_manager_packages = [
            'bind9'
        ] %}
    {% endif %}
{% endif %}
{{ macros.install_packages(designate_pool_manager_packages | customizable("packages")) }}

{% block designate_pool_manager_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER designate
