FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block barbican_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='barbican', groups='nfast,hsmusers') }}

{{ macros.install_packages(barbican_base_packages | customizable("packages")) }}

{% set barbican_base_pip_packages = [
    '/barbican',
    'pastedeploy',
    'python-barbicanclient',
] %}

ADD barbican-base-archive /barbican-base-source

COPY barbican_sudoers /etc/sudoers.d/kolla_barbican_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN ln -s barbican-base-source/* barbican \
    && {{ macros.install_pip(barbican_base_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/barbican \
    && cp -r /barbican/etc/barbican/* /etc/barbican/ \
    && chmod 750 /etc/sudoers.d \
    && chmod 640 /etc/sudoers.d/kolla_barbican_sudoers \
    && touch /usr/local/bin/kolla_barbican_extend_start \
    && chmod 644 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_barbican_extend_start

{{ macros.kolla_patch_sources() }}

{% block barbican_base_footer %}{% endblock %}
