FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block barbican_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='barbican') }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set barbican_base_packages = ['openstack-barbican-common'] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set barbican_base_packages = ['barbican-common'] %}
    {% endif %}

{{ macros.install_packages(barbican_base_packages | customizable("packages")) }}

{% elif install_type == 'source' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set barbican_base_packages = ['uwsgi-plugin-python'] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set barbican_base_packages = ['uwsgi-plugin-python'] %}
    {% endif %}

{{ macros.install_packages(barbican_base_packages | customizable("packages")) }}

ADD barbican-base-archive /barbican-base-source
RUN ln -s barbican-base-source/* barbican \
    && /var/lib/kolla/venv/bin/pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt  pastedeploy uwsgi MySQL-python python-barbicanclient /barbican \
    && mkdir -p /etc/barbican \
    && cp -r /barbican/etc/barbican/* /etc/barbican/ \
    && chown -R barbican: /etc/barbican

{% endif %}

COPY barbican_sudoers /etc/sudoers.d/kolla_barbican_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN chmod 750 /etc/sudoers.d \
    && chmod 640 /etc/sudoers.d/kolla_barbican_sudoers \
    && touch /usr/local/bin/kolla_barbican_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_barbican_extend_start

{% block barbican_base_footer %}{% endblock %}
