FROM {{ namespace }}/{{ image_prefix }}glance-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block glance_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'oraclelinux'] %}
    {% set glance_api_packages = ['qemu-img-ev'] %}
{% elif base_distro == 'rhel' %}
    {% set glance_api_packages = ['qemu-img'] %}
{% elif base_package_type == 'deb' %}
    {% set glance_api_packages = ['qemu-utils'] %}
{% endif %}

{{ macros.install_packages(glance_api_packages | customizable("packages")) }}

COPY extend_start.sh /usr/local/bin/kolla_glance_extend_start
RUN chmod 755 /usr/local/bin/kolla_glance_extend_start

{% block glance_api_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER glance
