FROM {{ namespace }}/{{ image_prefix }}glance-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

USER glance

{{ include_footer }}
