FROM {{ namespace }}/{{ image_prefix }}ceilometer-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block ceilometer_central_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}
        {% set ceilometer_central_packages = ['openstack-ceilometer-central'] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set ceilometer_central_packages = ['ceilometer-agent-central'] %}
    {% endif %}

{{ macros.install_packages(ceilometer_central_packages | customizable("packages")) }}

{% endif %}

{% block ceilometer_central_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER ceilometer
