FROM {{ namespace }}/{{ image_prefix }}gnocchi-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block gnocchi_metricd_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
       {% set gnocchi_metricd_packages = ['openstack-gnocchi-metricd'] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set gnocchi_metricd_packages = ['gnocchi-metricd'] %}
    {% endif %}
{{ macros.install_packages(gnocchi_metricd_packages | customizable("packages")) }}

{% endif %}
{% block gnocchi_metricd_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER gnocchi
