FROM {{ namespace }}/{{ image_prefix }}aodh-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block aodh_expirer_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
       {% set aodh_expirer_packages = ['openstack-aodh-expirer'] %}
    {% elif base_distro in ['debian', 'ubuntu'] %}
        {% set aodh_expirer_packages = ['aodh-expirer'] %}
    {% endif %}
{{ macros.install_packages(aodh_expirer_packages | customizable("packages")) }}

{% endif %}
{% block aodh_expirer_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER aodh
