FROM {{ namespace }}/{{ image_prefix }}aodh-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block aodh_expirer_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}
       {% set aodh_expirer_packages = ['openstack-aodh-expirer'] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set aodh_expirer_packages = ['aodh-expirer'] %}
    {% endif %}
{{ macros.install_packages(aodh_expirer_packages | customizable("packages")) }}

{% endif %}
{% block aodh_expirer_footer %}{% endblock %}
{% block footer %}{% endblock %}

{{ include_footer }}

USER aodh
