FROM {{ namespace }}/{{ image_prefix }}watcher-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block watcher_engine_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set watcher_engine_packages = ['openstack-watcher-decision-engine'] %}
    {% elif base_distro in ['debian', 'ubuntu'] %}
        {% set watcher_engine_packages = ['watcher-decision-engine'] %}
    {% endif %}
{{ macros.install_packages(watcher_engine_packages | customizable("packages")) }}
{% endif %}

{% block watcher_engine_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER watcher
