FROM {{ namespace }}/{{ image_prefix }}manila-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"
{% endblock %}

{% block manila_scheduler_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.kolla_patch_sources() }}

{% block manila_scheduler_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER manila
