FROM {{ namespace }}/{{ image_prefix }}manila-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block manila_scheduler_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_package_type == 'deb' %}

        {% set manila_scheduler_packages = [
                'manila-scheduler'
        ] %}

{{ macros.install_packages(manila_scheduler_packages | customizable("packages")) }}

    {% endif%}
{% endif%}

{% block manila_scheduler_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER manila
