FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['fedora', 'centos', 'oraclelinux'] %}

RUN yum -y install \
        openstack-glance \
        python-oslo-i18n \
    && yum clean all

    {% elif base_distro in ['ubuntu', 'debian'] %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

    {% endif %}
{% elif install_type == 'source' %}

ADD ./glance.tar /
RUN ln -s /glance-* /glance

RUN cd /glance \
    && useradd --user-group glance \
    && pip install -r requirements.txt \
    && pip install /glance \
    && mkdir /etc/glance /var/log/glance \
    && cp -r /glance/etc/* /etc/glance/ \
    && rm -rf /root/.cache

{% endif %}
