FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block mongodb_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}
    {% set mongodb_packages = [
            'mongodb',
            'mongodb-server'
    ] %}
{% elif base_distro in ['ubuntu', 'debian'] %}
    {% set mongodb_packages = [
            'mongodb-server'
    ] %}
{% endif %}

{{ macros.install_packages(mongodb_packages | customizable("packages")) }}

RUN mkdir -p /var/lib/mongodb /home/mongodb \
    && chown -R mongodb: /var/lib/mongodb /home/mongodb

COPY mongodb_sudoers /etc/sudoers.d/kolla_mongodb_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN usermod -a -G kolla mongodb \
    && chmod 755 /usr/local/bin/kolla_extend_start \
    && chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/kolla_mongodb_sudoers

{% block mongodb_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER mongodb
