FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block mongodb_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='mongodb') }}

{# NOTE(mgoddard): EPEL required for mongodb packages. Not provided by EPEL8 #}
{% if distro_package_manager == 'yum' %}
{{ macros.enable_extra_repos(['epel']) }}
{% endif %}

{% if base_package_type == 'rpm' %}
    {% set mongodb_packages = [
            'mongodb',
            'mongodb-server'
    ] %}
{% elif base_package_type == 'deb' %}
    {% set mongodb_packages = [
            'mongodb-server'
    ] %}
{% endif %}

{{ macros.install_packages(mongodb_packages | customizable("packages")) }}

COPY mongodb_sudoers /etc/sudoers.d/kolla_mongodb_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN chmod 755 /usr/local/bin/kolla_extend_start \
    && chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/kolla_mongodb_sudoers

{% block mongodb_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER mongodb
