FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        mongodb \
        mongodb-server \
    && yum clean all

{% elif base_distro in ['ubuntu', 'debian'] %}

RUN apt-get install -y --no-install-recommends mongodb-server \
    && apt-get clean

{% endif %}

RUN mkdir -p /data/db

VOLUME /data/db
VOLUME /var/log/mongodb

ENTRYPOINT exec /bin/mongod --dbpath /data/db --logpath /var/log/mongodb/mongo.log --noprealloc --smallfiles

{{ include_footer }}
