FROM {{ namespace }}/{{ image_prefix }}kuryr-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block kuryr_libnetwork_header %}{% endblock %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

ADD kuryr-libnetwork-archive /kuryr-libnetwork-source
RUN ln -s kuryr-libnetwork-source/* kuryr-libnetwork \
    && /var/lib/kolla/venv/bin/pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt /kuryr-libnetwork

{% endif %}

{% block kuryr_libnetwork_footer %}{% endblock %}
{% block footer %}{% endblock %}
