FROM {{ namespace }}/{{ image_prefix }}kuryr-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block kuryr_libnetwork_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'rpm' %}

{{ macros.enable_extra_repos(['openvswitch']) }}

    {% set kuryr_libnetwork_packages = [
        'openvswitch${KOLLA_RPM_OVS_VERSION}'
    ] %}

{% elif base_package_type == 'deb' %}

    {% set kuryr_libnetwork_packages = [
        'bridge-utils',
        'openvswitch-switch'
    ] %}

{% endif %}
{{ macros.install_packages(kuryr_libnetwork_packages | customizable("packages")) }}

ADD kuryr-libnetwork-archive /kuryr-libnetwork-source

{% set kuryr_libnetwork_pip_packages = [
    '/kuryr-libnetwork'
] %}

RUN ln -s kuryr-libnetwork-source/* kuryr-libnetwork \
    && {{ macros.install_pip(kuryr_libnetwork_pip_packages | customizable("pip_packages")) }}

{{ macros.kolla_patch_sources() }}

{% block kuryr_libnetwork_footer %}{% endblock %}
{% block footer %}{% endblock %}
