FROM {{ namespace }}/{{ image_prefix }}kuryr-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block kuryr_libnetwork_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

ADD kuryr-libnetwork-archive /kuryr-libnetwork-source

{% set kuryr_libnetwork_pip_packages = [
    '/kuryr-libnetwork'
] %}

RUN ln -s kuryr-libnetwork-source/* kuryr-libnetwork \
    && {{ macros.install_pip(kuryr_libnetwork_pip_packages | customizable("pip_packages")) }}

{% endif %}

{% block kuryr_libnetwork_footer %}{% endblock %}
{% block footer %}{% endblock %}
