---
- project:
    queue: kolla

- nodeset:
    name: kolla-centos-9-stream
    nodes:
      - name: primary
        label: centos-9-stream

- nodeset:
    name: kolla-rockylinux-9
    nodes:
      - name: primary
        label: rockylinux-9

- nodeset:
    name: kolla-ubuntu-jammy
    nodes:
      - name: primary
        label: ubuntu-jammy

- nodeset:
    name: kolla-ubuntu-noble
    nodes:
      - name: primary
        label: ubuntu-noble

- nodeset:
    name: kolla-debian-bookworm
    nodes:
      - name: primary
        label: debian-bookworm

- nodeset:
    name: kolla-centos-9-stream-aarch64
    nodes:
      - name: primary
        label: centos-9-stream-arm64

- nodeset:
    name: kolla-debian-bookworm-aarch64
    nodes:
      - name: primary
        label: debian-bookworm-arm64

- nodeset:
    name: kolla-rockylinux-9-aarch64
    nodes:
      - name: primary
        label: rockylinux-9-arm64

- nodeset:
    name: kolla-ubuntu-jammy-aarch64
    nodes:
      - name: primary
        label: ubuntu-jammy-arm64

- nodeset:
    name: kolla-ubuntu-noble-aarch64
    nodes:
      - name: primary
        label: ubuntu-noble-arm64

- job:
    name: kolla-base
    parent: base
    timeout: 10800
    post-timeout: 10800
    pre-run: tests/playbooks/pre.yml
    run: tests/playbooks/run.yml
    post-run: tests/playbooks/post.yml
    attempts: 5
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*
      - ^etc/.*
      - ^releasenotes/.*$
      - ^specs/.*$
      - ^test-requirements.txt$
      - ^\.zuul\.d/
      - ^\..+
      - ^contrib/
      - ^LICENSE$
      - ^tox\.ini$
    vars:
      publisher: false
      container_engine: "docker"
    extra-vars:
      kolla_logs_dir: "{{ zuul_output_dir }}/logs/kolla"
      kolla_build_logs_dir: "{{ kolla_logs_dir }}/build"
      virtualenv_path: "/tmp/kolla-virtualenv"

- job:
    name: kolla-base-podman
    parent: kolla-base
    vars:
      container_engine: "podman"
      configure_ephemeral_mountpoint: "/var/lib/containers"

- job:
    name: kolla-build-no-infra-wheels-base
    parent: kolla-base
    vars:
      use_infra_wheels_mirror: false
