---
- project:
    templates:
      - openstack-python3-jobs
      - openstack-python3-jobs-arm64
      - openstack-cover-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - periodic-stable-jobs
    check:
      jobs:
        - kolla-tox-genconfig
        - openstack-tox-py312
    check-arm64:
      jobs:
        - openstack-tox-py312-arm64
    gate:
      jobs:
        - kolla-tox-genconfig
