#!/bin/bash

set -e

rabbitmq-diagnostics -t 5 -q ping || exit 1
rabbitmq-diagnostics -t 5 -q status || exit 1
rabbitmq-diagnostics -t 5 -q check_running || exit 1
rabbitmq-diagnostics -t 5 -q check_local_alarms || exit 1
rabbitmq-diagnostics -t 5 -q check_port_connectivity || exit 1
rabbitmq-diagnostics -t 5 -q check_virtual_hosts || exit 1
