FROM {{ namespace }}/{{ base_distro }}-{{ install_type  }}-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['fedora', 'centos', 'oraclelinux'] %}

RUN yum -y install openstack-cinder \
    python-automaton \
  && yum clean all \
  && sed -i "s|udev_rules = 1|udev_rules = 0|g" /etc/lvm/lvm.conf \
  && sed -i "s|udev_sync = 1|udev_sync = 0|g" /etc/lvm/lvm.conf

# NOTE(sdake): The sed operations make LVM tools work inside a container - see
# https://groups.google.com/forum/#!topic/docker-user/n4Xtvsb4RAw

     {% elif base_distro in ['ubuntu', 'debian'] %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
  && /bin/false

    {% endif %}
{% elif install_type == 'source' %}

ADD ./cinder.tar /
RUN ln -s /cinder-* /cinder

RUN cd /cinder \
    && useradd --user-group cinder \
    && pip install -r requirements.txt \
    && pip install /cinder \
    && mkdir /etc/cinder /var/log/cinder \
    && cp -r /cinder/etc/cinder/* /etc/cinder/ \
    && chown -R cinder: /etc/cinder /var/log/cinder \
    && rm -rf /root/.cache \
    && sed -i "s|udev_rules = 1|udev_rules = 0|g" /etc/lvm/lvm.conf \
    && sed -i "s|udev_sync = 1|udev_sync = 0|g" /etc/lvm/lvm.conf

# NOTE(sdake): The sed operations make LVM tools work inside a container - see
# https://groups.google.com/forum/#!topic/docker-user/n4Xtvsb4RAw

{% endif %}
