FROM {{ namespace }}/{{ image_prefix }}novajoin-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block novajoin_server_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_package_type != 'rpm'  %}
RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false
    {% endif %}
{% endif %}

{% block novajoin_server_footer %}{% endblock %}
{% block footer %}{% endblock %}
