FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block kubernetes_entrypoint_header %}{% endblock %}

{% block kubernetes_entrypoint_install_binary %}
RUN curl -Lo /usr/local/bin/kubernetes-entrypoint https://github.com/stackanetes/kubernetes-entrypoint/releases/download/v0.1.1/kubernetes-entrypoint \
    && chmod 755 /usr/local/bin/kubernetes-entrypoint
{% endblock %}

{% block kubernetes_entrypoint_footer %}{% endblock %}
{% block footer %}{% endblock %}
CMD /usr/local/bin/kubernetes-entrypoint
