FROM {{ namespace }}/{{ image_prefix }}sahara-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block sahara_engine_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'rpm' %}
    {% set sahara_engine_packages = ['nc'] %}
{% elif base_package_type == 'deb' %}
    {% set sahara_engine_packages = ['netcat'] %}
{% endif %}

{{ macros.install_packages(sahara_engine_packages | customizable("packages")) }}

{% block sahara_engine_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER sahara
