FROM {{ namespace }}/{{ image_prefix }}sahara-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block sahara_engine_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set sahara_engine_packages = [
            'nc',
            'openstack-sahara-engine',
        ] %}
    {% elif base_distro in ['debian', 'ubuntu'] %}
        {% set sahara_engine_packages = [
            'netcat',
            'sahara-engine',
        ] %}
    {% endif %}
{% elif install_type == 'source' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
       {% set sahara_engine_packages = ['nc'] %}
    {% elif base_distro in ['debian', 'ubuntu'] %}
        {% set sahara_engine_packages = ['netcat'] %}
    {% endif %}
{% endif %}

{{ macros.install_packages(sahara_engine_packages | customizable("packages")) }}

{% block sahara_engine_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER sahara
