FROM {{ namespace }}/{{ image_prefix }}openvswitch-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block openvswitch_vswitchd_header %}{% endblock %}

COPY extend_start.sh /usr/local/bin/kolla_openvswitch_extend_start
RUN chmod 755 /usr/local/bin/kolla_openvswitch_extend_start

{% block openvswitch_vswitchd_footer %}{% endblock %}
{% block footer %}{% endblock %}
