FROM {{ namespace }}/{{ image_prefix }}karbor-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block karbor_api_header %}{% endblock %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_karbor_extend_start
RUN chmod 755 /usr/local/bin/kolla_karbor_extend_start

{% block karbor_api_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER karbor
