FROM {{ namespace }}/{{ image_prefix }}manila-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block manila_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['ubuntu'] %}

        {% set manila_api_packages = [
                'manila-api'
        ] %}

{{ macros.install_packages(manila_api_packages | customizable("packages")) }}

    {% endif%}
{% endif%}

COPY extend_start.sh /usr/local/bin/kolla_manila_extend_start
RUN chmod 755 /usr/local/bin/kolla_manila_extend_start

{% block manila_api_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER manila
