FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if base_distro in ['fedora', 'centos', 'oraclelinux'] %}

RUN yum -y install \
        git \
        gcc \
        libffi-devel \
        libxml2-devel \
        libxslt-devel \
        MySQL-python \
        openssl-devel \
        python-devel \
        openssh-clients \
    && yum clean all

RUN pip install -U pip wheel

{% elif base_distro in ['ubuntu', 'debian'] %}

RUN apt-get install -y --no-install-recommends git

{% endif %}

RUN pip install shade

RUN git clone https://github.com/ansible/ansible.git \
    && cd ansible \
    && git submodule update --init --recursive \
    && pip install .

{% if base_distro in ['ubuntu', 'debian'] %}

# TODO(SamYaple): Ubuntu installs pip packages to /usr/local/bin/ rather than
#                 /usr/bin This can be removed once the bin paths are generic
RUN ln -s /usr/local/bin/ansible /usr/bin/ansible

{% endif %}

RUN mkdir -p /etc/ansible /usr/share/ansible \
    && echo 'localhost ansible_connection=local' > /etc/ansible/hosts

COPY kolla_keystone_service.py kolla_keystone_user.py /usr/share/ansible/
