FROM {{ namespace }}/{{ image_prefix }}prometheus-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block prometheus_openstack_network_exporter_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% block prometheus_openstack_network_exporter_install %}
ADD prometheus-openstack-network-exporter-archive /prometheus-openstack-network-exporter-source

RUN mkdir /opt/openstack-network-exporter \
    && cp /prometheus-openstack-network-exporter-source /opt/openstack-network-exporter/openstack-network-exporter \
    && chmod 0755 /opt/openstack-network-exporter/openstack-network-exporter
{% endblock %}

{{ macros.kolla_patch_sources() }}

{% block prometheus_openstack_network_exporter_footer %}{% endblock %}
{% block footer %}{% endblock %}

# NOTE: OVN/OVS are running as root. Since we need to read sockets owned by
# these services we don't switch to the Prometheus user here.
