---
- name: Pulling mistral-api image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ mistral_api_image_full }}"
  when: inventory_hostname in groups['mistral-api']

- name: Pulling mistral-engine image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ mistral_engine_image_full }}"
  when: inventory_hostname in groups['mistral-engine']

- name: Pulling mistral-executor image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ mistral_executor_image_full }}"
  when: inventory_hostname in groups['mistral-executor']
