---
- name: Creating the Mistral service and endpoint
  command: docker exec -t kolla_toolbox /usr/bin/ansible localhost
    -m kolla_keystone_service
    -a "service_name=mistral
        service_type=workflowv2
        description='Openstack Workflow'
        endpoint_region={{ openstack_region_name }}
        url='{{ item.url }}'
        interface='{{ item.interface }}'
        region_name={{ openstack_region_name }}
        auth={{ '{{ openstack_mistral_auth }}' }}"
    -e "{'openstack_mistral_auth':{{ openstack_mistral_auth }}}"
  register: mistral_endpoint
  changed_when: "{{ mistral_endpoint.stdout.find('localhost | SUCCESS => ') != -1 and (mistral_endpoint.stdout.split('localhost | SUCCESS => ')[1]|from_json).changed }}"
  until: mistral_endpoint.stdout.split()[2] == 'SUCCESS'
  retries: 10
  delay: 5
  run_once: True
  with_items:
    - {'interface': 'admin', 'url': '{{ mistral_admin_endpoint }}'}
    - {'interface': 'internal', 'url': '{{ mistral_internal_endpoint }}'}
    - {'interface': 'public', 'url': '{{ mistral_public_endpoint }}'}

- name: Creating the Mistral project, user, and role
  command: docker exec -t kolla_toolbox /usr/bin/ansible localhost
    -m kolla_keystone_user
    -a "project=service
        user=mistral
        password={{ mistral_keystone_password }}
        role=admin
        region_name={{ openstack_region_name }}
        auth={{ '{{ openstack_mistral_auth }}' }}"
    -e "{'openstack_mistral_auth':{{ openstack_mistral_auth }}}"
  register: mistral_user
  changed_when: "{{ mistral_user.stdout.find('localhost | SUCCESS => ') != -1 and (mistral_user.stdout.split('localhost | SUCCESS => ')[1]|from_json).changed }}"
  until: mistral_user.stdout.split()[2] == 'SUCCESS'
  retries: 10
  delay: 5
  run_once: True
