FROM {{ namespace }}/{{ image_prefix }}nova-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install openstack-nova-spicehtml5proxy \
    && yum clean all

    {% endif %}
{% elif install_type == 'source' %}

ADD nova-spicehtml5proxy-archive /usr/share/nova-spicehtml5proxy-source
RUN cd /usr/share && ln -s nova-spicehtml5proxy-source/* spice-html5

{% endif %}

{{ include_footer }}
