FROM {{ namespace }}/{{ image_prefix }}nova-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block nova_spicehtml5proxy_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

        {% set nova_spicehtml5proxy_packages = [
            'openstack-nova-spicehtml5proxy',
            'spice-html5'
        ] %}

    {% elif base_distro in ['ubuntu'] %}

        {% set nova_spicehtml5proxy_packages = [
            'nova-spiceproxy'
        ] %}

    {% endif %}

{{ macros.install_packages(nova_spicehtml5proxy_packages | customizable("packages")) }}

{% elif install_type == 'source' %}

ADD nova-spicehtml5proxy-archive /usr/share/nova-spicehtml5proxy-source
RUN cd /usr/share \
    && ln -s nova-spicehtml5proxy-source/* spice-html5

{% endif %}

{% block nova_spicehtml5proxy_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER nova
