FROM {{ namespace }}/{{ image_prefix }}nova-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block nova_spicehtml5proxy_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_package_type == 'rpm' %}

        {% set nova_spicehtml5proxy_packages = [
            'openstack-nova-spicehtml5proxy',
            'spice-html5'
        ] %}

        {% if distro_python_version.startswith('3') %}
        {% set nova_spicehtml5proxy_packages = nova_spicehtml5proxy_packages + [
            'python3-numpy',
        ] %}
        {% else %}
        {% set nova_spicehtml5proxy_packages = nova_spicehtml5proxy_packages + [
            'numpy',
        ] %}
        {% endif %}

    {% elif base_package_type == 'deb' %}

        {% set nova_spicehtml5proxy_packages = [
            'nova-spiceproxy',
            'websockify'
        ] %}

    {% endif %}

{% elif install_type == 'source' %}
    {% if base_package_type == 'rpm' %}

        {% set nova_spicehtml5proxy_packages = [
            'numpy',
            'spice-html5'
        ] %}

    {% elif base_package_type == 'deb' %}

        {% set nova_spicehtml5proxy_packages = [
            'spice-html5',
            'websockify'
        ] %}

    {% endif %}
{% endif %}

{{ macros.install_packages(nova_spicehtml5proxy_packages | customizable("packages")) }}

{% block nova_spicehtml5proxy_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER nova
