FROM {{ namespace }}/{{ image_prefix }}monasca-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block monasca_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

ADD monasca-statsd-archive /monasca-statsd-source
# NOTE(SamYaple): <=1.3.0 do not have any packages in requirements.txt and that
# breaks pip. So removing constraints file.
RUN ln -s monasca-statsd-source/* monasca-statsd \
    && /var/lib/kolla/venv/bin/pip --no-cache-dir install --upgrade /monasca-statsd

{% endif %}

{% block monasca_api_footer %}{% endblock %}

{% block footer %}{% endblock %}

USER monasca

