FROM {{ namespace }}/{{ image_prefix }}aodh-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block aodh_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
       {% set aodh_api_packages = ['openstack-aodh-api'] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set aodh_api_packages = ['aodh-api'] %}
    {% endif %}
{{ macros.install_packages(aodh_api_packages | customizable("packages")) }}
{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_aodh_extend_start
RUN chmod 755 /usr/local/bin/kolla_aodh_extend_start

{% block aodh_api_footer %}{% endblock %}
{% block footer %}{% endblock %}
