FROM {{ namespace }}/{{ image_prefix }}aodh-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block aodh_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
       {% set aodh_api_packages = ['openstack-aodh-api'] %}
    {% elif base_distro in ['debian', 'ubuntu'] %}
        {% set aodh_api_packages = ['aodh-api'] %}
    {% endif %}
{{ macros.install_packages(aodh_api_packages | customizable("packages")) }}

    {% if base_distro in ['debian', 'ubuntu'] %}
RUN rm -rf /etc/apache2/sites-enabled/aodh-api.conf
    {% endif %}
{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_aodh_extend_start
RUN chmod 755 /usr/local/bin/kolla_aodh_extend_start

{% block aodh_api_footer %}{% endblock %}
{% block footer %}{% endblock %}
