FROM {{ namespace }}/{{ image_prefix }}prometheus-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block prometheus_ovn_exporter_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% block prometheus_ovn_exporter_install %}

ADD prometheus-ovn-exporter-archive /prometheus-ovn-exporter-source

RUN cp /prometheus-ovn-exporter-source/* /opt/
{% endblock %}

{{ macros.kolla_patch_sources() }}

{% block prometheus_ovn_exporter_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER prometheus
