FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block opendaylight_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='odl') }}

{% if install_type == 'binary' %}
    {% set opendaylight_packages = ['opendaylight'] %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}

      {% if opendaylight_repo is not defined %}
        {% set opendaylight_repo = 'opendaylight.repo' %}
      {% endif %}
COPY {{ opendaylight_repo }} /etc/yum.repos.d/

    {% elif base_distro in ['debian', 'ubuntu'] %}
        {% if base_distro in 'debian' %}
            {% if odl_release_deb_url is not defined %}
                {% set odl_release_deb_url = 'http://download.opensuse.org/repositories/home:/akshitajha/Debian_8.0/' %}
            {% endif %}
RUN sh -c "echo 'deb {{ odl_release_deb_url }} /' > /etc/apt/sources.list.d/opendaylight.list"
        {% endif %}

# NOTE(egonzalez): ODL fails to install in debian family images with
# existing odl user. First install odl and then allow usage of
# install_packages macro for custom configs.
        {% block debian_opendaylight_install_fix_block %}
            {{ macros.debian_opendaylight_existing_user_fix() }}
        {% endblock %}
    {% endif %}

{{ macros.install_packages(opendaylight_packages | customizable("packages")) }}

{% elif install_type == 'source' %}
{% block opendaylight_source_install %}
RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false
{% endblock %}
{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block opendaylight_footer %}{% endblock %}
{% block footer %}{% endblock %}
