FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block opendaylight_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='odl') }}

{{ macros.enable_extra_repos(['opendaylight']) }}

{% block opendaylight_install %}

{% if base_package_type == 'rpm' %}
    {% set opendaylight_packages = [
        'java-1.8.0-openjdk-headless',
        'opendaylight',
    ] %}
{% elif base_package_type == 'deb' %}

    {% if base_distro == 'debian' %}
        {% set java_version = '11' %}
    {% elif base_distro == 'ubuntu' %}
        {% set java_version = '8' %}
    {% endif %}

    {% set opendaylight_packages = [
        'opendaylight',
        'openjdk-' + java_version + '-jre-headless',
    ] %}
{% endif %}

{{ macros.install_packages(opendaylight_packages | customizable("packages")) }}

{% endblock %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block opendaylight_footer %}{% endblock %}
{% block footer %}{% endblock %}
