FROM {{ namespace }}/{{ image_prefix }}senlin-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block senlin_health_manager_header %}{% endblock %}

{% block senlin_health_manager_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER senlin
