FROM {{ namespace }}/{{ image_prefix }}heat-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block heat_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}
       {% set heat_api_packages = ['openstack-heat-api'] %}
    {% elif base_distro in ['ubuntu'] %}
        {% set heat_api_packages = ['heat-api'] %}
    {% endif %}
{{ macros.install_packages(heat_api_packages | customizable("packages")) }}
{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_heat_extend_start
RUN chmod 755 /usr/local/bin/kolla_heat_extend_start

{% block heat_api_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER heat
