FROM {{ namespace }}/{{ image_prefix }}heat-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}"
{% endblock %}

{% block heat_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

COPY extend_start.sh /usr/local/bin/kolla_heat_extend_start
RUN chmod 644 /usr/local/bin/kolla_heat_extend_start

{{ macros.kolla_patch_sources() }}

{% block heat_api_footer %}{% endblock %}
{% block footer %}{% endblock %}
