FROM {{ namespace }}/{{ image_prefix }}kube-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

ENV KUBERNETES_COMPONENT=kube-discovery

{% block kube_discovery_header %}{% endblock %}

{% block kube_discovery_install %}
# To match upstream we load the binary to /usr/local/bin
RUN true \
    && curl -L ${KUBERNETES_DOWNLOAD_ROOT}/${KUBERNETES_COMPONENT} -o /usr/local/bin/${KUBERNETES_COMPONENT} \
    && chmod +x /usr/local/bin/${KUBERNETES_COMPONENT}
{% endblock %}

# Clear any customisation by Kolla to entrypoint & command
ENTRYPOINT []
CMD []

{% block kube_discovery_footer %}{% endblock %}
{% block footer %}{% endblock %}
