FROM {{ namespace }}/{{ image_prefix }}vitrage-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block vitrage_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

COPY extend_start.sh /usr/local/bin/kolla_vitrage_extend_start
RUN chmod 644 /usr/local/bin/kolla_vitrage_extend_start

{% block vitrage_api_footer %}{% endblock %}
{% block footer %}{% endblock %}
