FROM {{ namespace }}/{{ base_distro }}-{{ install_type }}-base:{{ tag }}
MAINTAINER Kolla Project (https://launchpad.net/kolla)

{% if install_type == 'binary' %}
    {% if base_distro in ['fedora', 'centos', 'oraclelinux'] %}

RUN yum -y install \
        openstack-nova-common \
        python-keystoneclient \
        python-cinderclient \
        python-nova \
        bridge-utils \
    && yum clean all

    {% elif base_distro in ['ubuntu', 'debian'] %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

    {% endif %}
{% elif install_type == 'source' %}
    {% if base_distro in ['fedora', 'centos', 'oraclelinux'] %}

RUN yum -y install \
        bridge-utils \
    && yum clean all

    {% elif base_distro in ['ubuntu', 'debian'] %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

    {% endif %}

RUN pip install \
    python-cinderclient \
    python-keystoneclient

ADD ./nova.tar /
RUN ln -s /nova-* /nova

RUN cd /nova \
    && useradd --user-group nova \
    && pip install -r requirements.txt \
    && pip install /nova \
    && tox -egenconfig \
    && mkdir /etc/nova /var/log/nova \
    && cp -r /nova/etc/nova/* /etc/nova/ \
    && chown -R nova: /etc/nova /var/log/nova \
    && rm -rf /root/.cache

{% endif %}
